// Code generated by cmd/osgen; DO NOT EDIT.

package transforms

import (
	"io"
	"net/http"
	"strconv"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/osapi"
)

// PutReq represents the request for the transforms.put operation.
//
// Create an index transform, or update a transform if `if_seq_no` and `if_primary_term` are provided.
//
// PUT /_plugins/_transform/{id}
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/im-plugin/index-transforms/transforms-apis/#create-a-transform-job
type PutReq struct {
	// ID specifies the path segment for the request URL.
	ID string

	// Body is the request payload, typically JSON-encoded.
	Body io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params PutParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r PutReq) GetRequest() (*http.Request, error) {
	path, err := ospath.TransformsPutPath{
		ID: r.ID,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodPut,
		path,
		r.Body,
		r.Params.get(),
		r.Header,
	)
}

// PutParams represents query parameters for the PutReq.
type PutParams struct {
	// Only perform the operation if the document has this primary term.
	IfPrimaryTerm int

	// Only perform the operation if the document has this sequence number.
	IfSeqNo int

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r PutParams) get() map[string]string {
	params := make(map[string]string, 2)

	if r.IfPrimaryTerm != 0 {
		params["if_primary_term"] = strconv.Itoa(r.IfPrimaryTerm)
	}

	if r.IfSeqNo != 0 {
		params["if_seq_no"] = strconv.Itoa(r.IfSeqNo)
	}

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// PutResp represents the response for the transforms.put operation.
//
// Create an index transform, or update a transform if `if_seq_no` and `if_primary_term` are provided.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/im-plugin/index-transforms/transforms-apis/#create-a-transform-job
type PutResp struct {
	// The unique identifier for a resource.
	ID *string `json:"_id,omitempty"`

	PrimaryTerm *int64 `json:"_primary_term,omitempty"`

	// The sequence number of the document.
	SeqNo *int64 `json:"_seq_no,omitempty"`

	Version   *int64                     `json:"_version,omitempty"`
	Transform *osapi.TransformsTransform `json:"transform,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r PutResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}
