// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package ml

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
	"github.com/opensearch-project/opensearch-go/v5/opensearchapi"
)

// SearchConnectorsReq represents the request for the ml.search_connectors operation.
//
// Searches for standalone connectors.
//
// Path: /_plugins/_ml/connectors/_search
//
// Methods: GET, POST
//
// Available: >= 2.11.0.
type SearchConnectorsReq struct {

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *MLSearchConnectorsBody

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *SearchConnectorsParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r SearchConnectorsReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.MLSearchConnectorsPath{}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		bodyData, err := json.Marshal(r.Body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// SearchConnectorsParams represents query parameters for the SearchConnectorsReq.
type SearchConnectorsParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
}

func (r SearchConnectorsParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// SearchConnectorsResp represents the response for the SearchConnectors operation.
// The response body has a dynamic schema and is captured as raw JSON.
//
// Searches for standalone connectors.
type SearchConnectorsResp struct {
	Body     json.RawMessage `json:"-"`
	response *opensearch.Response
}

// UnmarshalJSON captures the raw response body.
//
//nolint:unparam // error return required by json.Unmarshaler; raw passthrough never fails
func (r *SearchConnectorsResp) UnmarshalJSON(b []byte) error {
	r.Body = append(r.Body[:0], b...)
	return nil
}

// MarshalJSON returns the raw response body for comparison testing.
//
//nolint:unparam // error return required by json.Marshaler; raw passthrough never fails
func (r SearchConnectorsResp) MarshalJSON() ([]byte, error) {
	if r.Body == nil {
		return build.NullJSON, nil
	}
	return r.Body, nil
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r SearchConnectorsResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r SearchConnectorsResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// MLSearchConnectorsBody is a typed component of the ml.search_connectors operation.
type MLSearchConnectorsBody struct {
	Query *opensearchapi.CommonQueryDSLQueryContainer `json:"query,omitempty"`

	// The number of connectors to return.
	Size *int64 `json:"size,omitempty"`

	// The sort order.
	Sort *MLSearchConnectorsBodySort `json:"sort,omitempty"`
}

// MLSearchConnectorsBodySort is a discriminated union type (try-each, newest version first).
// Use Type() to determine which branch was decoded, then call
// the corresponding accessor.
type MLSearchConnectorsBodySort struct {
	typ   MLSearchConnectorsBodySortType
	raw   json.RawMessage
	value any
}

// MLSearchConnectorsBodySortType discriminates the branches of MLSearchConnectorsBodySort.
type MLSearchConnectorsBodySortType int

const (
	MLSearchConnectorsBodySortUnknownType MLSearchConnectorsBodySortType = iota
	MLSearchConnectorsBodySortStringType
	MLSearchConnectorsBodySortStringMapType
	MLSearchConnectorsBodySortFieldSortMapType
	MLSearchConnectorsBodySortOptionsType
)

// Type returns which union branch was populated during decoding.
// Returns MLSearchConnectorsBodySortUnknownType if the value has not been decoded.
func (u *MLSearchConnectorsBodySort) Type() MLSearchConnectorsBodySortType { return u.typ }

// RawJSON returns the union's JSON bytes. After decoding these are borrowed
// from the response buffer: valid only while the owning response value is
// reachable, must not be mutated, and must be copied if retained beyond it.
func (u *MLSearchConnectorsBodySort) RawJSON() json.RawMessage { return u.raw }

// SetRaw stages pre-encoded JSON for marshaling. MarshalJSON emits raw
// verbatim when no typed branch is set. Use the NewMLSearchConnectorsBodySortFrom*
// constructors to populate a typed branch instead; SetRaw is the typed
// escape hatch for callers that already have wire-format bytes.
func (u *MLSearchConnectorsBodySort) SetRaw(raw json.RawMessage) {
	u.raw = raw
	u.value = nil
	u.typ = MLSearchConnectorsBodySortUnknownType
}

// String returns the string branch value.
func (u *MLSearchConnectorsBodySort) String() string {
	if v, ok := u.value.(*string); ok {
		return *v
	}
	var zero string
	return zero
}

// NewMLSearchConnectorsBodySortFromString returns a MLSearchConnectorsBodySort populated with v
// on the String branch.
func NewMLSearchConnectorsBodySortFromString(v string) MLSearchConnectorsBodySort {
	return MLSearchConnectorsBodySort{
		typ:   MLSearchConnectorsBodySortStringType,
		value: &v,
	}
}

// StringMap returns the map[string]string branch value.
func (u *MLSearchConnectorsBodySort) StringMap() map[string]string {
	if v, ok := u.value.(*map[string]string); ok {
		return *v
	}
	var zero map[string]string
	return zero
}

// NewMLSearchConnectorsBodySortFromStringMap returns a MLSearchConnectorsBodySort populated with v
// on the StringMap branch.
func NewMLSearchConnectorsBodySortFromStringMap(v map[string]string) MLSearchConnectorsBodySort {
	return MLSearchConnectorsBodySort{
		typ:   MLSearchConnectorsBodySortStringMapType,
		value: &v,
	}
}

// FieldSortMap returns the map[string]opensearchapi.FieldSort branch value.
func (u *MLSearchConnectorsBodySort) FieldSortMap() map[string]opensearchapi.FieldSort {
	if v, ok := u.value.(*map[string]opensearchapi.FieldSort); ok {
		return *v
	}
	var zero map[string]opensearchapi.FieldSort
	return zero
}

// NewMLSearchConnectorsBodySortFromFieldSortMap returns a MLSearchConnectorsBodySort populated with v
// on the FieldSortMap branch.
func NewMLSearchConnectorsBodySortFromFieldSortMap(v map[string]opensearchapi.FieldSort) MLSearchConnectorsBodySort {
	return MLSearchConnectorsBodySort{
		typ:   MLSearchConnectorsBodySortFieldSortMapType,
		value: &v,
	}
}

// Options returns the opensearchapi.SortOptions branch value.
func (u *MLSearchConnectorsBodySort) Options() opensearchapi.SortOptions {
	if v, ok := u.value.(*opensearchapi.SortOptions); ok {
		return *v
	}
	var zero opensearchapi.SortOptions
	return zero
}

// NewMLSearchConnectorsBodySortFromOptions returns a MLSearchConnectorsBodySort populated with v
// on the Options branch.
func NewMLSearchConnectorsBodySortFromOptions(v opensearchapi.SortOptions) MLSearchConnectorsBodySort {
	return MLSearchConnectorsBodySort{
		typ:   MLSearchConnectorsBodySortOptionsType,
		value: &v,
	}
}

func (u *MLSearchConnectorsBodySort) UnmarshalJSON(data []byte) error {
	u.raw = data
	u.value = nil
	u.typ = MLSearchConnectorsBodySortUnknownType
	if len(data) == 0 || bytes.Equal(data, build.NullJSON) {
		return nil
	}
	// Pass 1: branches that declare required (discriminator) fields. A branch
	// is eligible only when the payload carries every required key, so a more
	// specific branch (e.g. an error sub-response keyed by "error") is not
	// absorbed by a structurally permissive success branch. encoding/json does
	// not enforce a schema's "required" set, hence the explicit key probe.
	// Pass 2: permissive branches with no required fields, tried newest-first.
	{
		var v string
		if err := json.Unmarshal(data, &v); err == nil {
			u.typ = MLSearchConnectorsBodySortStringType
			u.value = &v
			return nil
		}
	}
	{
		var v map[string]string
		if err := json.Unmarshal(data, &v); err == nil {
			u.typ = MLSearchConnectorsBodySortStringMapType
			u.value = &v
			return nil
		}
	}
	{
		var v map[string]opensearchapi.FieldSort
		if err := json.Unmarshal(data, &v); err == nil {
			u.typ = MLSearchConnectorsBodySortFieldSortMapType
			u.value = &v
			return nil
		}
	}
	{
		var v opensearchapi.SortOptions
		if err := json.Unmarshal(data, &v); err == nil {
			u.typ = MLSearchConnectorsBodySortOptionsType
			u.value = &v
			return nil
		}
	}
	return fmt.Errorf("MLSearchConnectorsBodySort: no branch matched JSON: %s", data[:min(len(data), 64)])
}

func (u MLSearchConnectorsBodySort) MarshalJSON() ([]byte, error) {
	if u.value != nil {
		return json.Marshal(u.value)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return build.NullJSON, nil
}
