// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package security

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi"
)

// GetRolesReq represents the request for the security.get_roles operation.
//
// Retrieves all roles.
//
// GET /_plugins/_security/api/roles
//
// Available: >= 1.0.0.
//
// Not available on: amazon-managed, amazon-serverless.
//
// See: https://opensearch.org/docs/latest/security/access-control/api/#get-roles
type GetRolesReq struct {

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *GetRolesParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r GetRolesReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.SecurityGetRolesPath{}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// GetRolesParams represents query parameters for the GetRolesReq.
type GetRolesParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
}

func (r GetRolesParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// GetRolesResp represents the response for the GetRoles operation.
// The response body is a JSON object keyed by resource name.
//
// Retrieves all roles.
//
// See: https://opensearch.org/docs/latest/security/access-control/api/#get-roles
type GetRolesResp struct {
	Entries  map[string]opensearchapi.SecurityRole `json:"-"`
	response *opensearch.Response
}

// UnmarshalJSON decodes the response body as a string-keyed map.
func (r *GetRolesResp) UnmarshalJSON(b []byte) error {
	return json.Unmarshal(b, &r.Entries)
}

// MarshalJSON encodes the response body for comparison testing.
func (r GetRolesResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(r.Entries)
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r GetRolesResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r GetRolesResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
