// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package security

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi"
)

// ReloadHTTPCertificatesReq represents the request for the security.reload_http_certificates operation.
//
// Reloads the HTTP communication certificates.
//
// PUT /_plugins/_security/api/ssl/http/reloadcerts
//
// Available: >= 2.8.0.
//
// Not available on: amazon-managed, amazon-serverless.
//
// See: https://opensearch.org/docs/latest/security/access-control/api/#reload-http-certificates
type ReloadHTTPCertificatesReq struct {

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *ReloadHTTPCertificatesParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r ReloadHTTPCertificatesReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.SecurityReloadHTTPCertificatesPath{}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// ReloadHTTPCertificatesParams represents query parameters for the ReloadHTTPCertificatesReq.
type ReloadHTTPCertificatesParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
}

func (r ReloadHTTPCertificatesParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// ReloadHTTPCertificatesResp represents the response for the security.reload_http_certificates operation.
//
// Reloads the HTTP communication certificates.
//
// Available: >= 2.8.0.
//
// See: https://opensearch.org/docs/latest/security/access-control/api/#reload-http-certificates
type ReloadHTTPCertificatesResp struct {
	// The message returned as part of an `OK` response.
	Message *string `json:"message,omitempty"`

	Status json.RawMessage `json:"status"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r ReloadHTTPCertificatesResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r ReloadHTTPCertificatesResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
