// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package security

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi"
)

// WhoAmIProtectedReq represents the request for the security.who_am_i_protected operation.
//
// Gets the identity information for the user currently logged in. To use this operation, you must have access to this endpoint when authorization at REST layer is enabled.
//
// GET /_plugins/_security/whoamiprotected
//
// Available: >= 2.11.0.
//
// Not available on: amazon-managed, amazon-serverless.
type WhoAmIProtectedReq struct {

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *WhoAmIProtectedParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r WhoAmIProtectedReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.SecurityWhoAmIProtectedPath{}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// WhoAmIProtectedParams represents query parameters for the WhoAmIProtectedReq.
type WhoAmIProtectedParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
}

func (r WhoAmIProtectedParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// WhoAmIProtectedResp represents the response for the security.who_am_i_protected operation.
//
// Gets the identity information for the user currently logged in. To use this operation, you must have access to this endpoint when authorization at REST layer is enabled.
//
// Available: >= 2.11.0.
type WhoAmIProtectedResp struct {
	Dn                       json.RawMessage `json:"dn"`
	IsAdmin                  *bool           `json:"is_admin,omitempty"`
	IsNodeCertificateRequest *bool           `json:"is_node_certificate_request,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r WhoAmIProtectedResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r WhoAmIProtectedResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
