// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package security

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/osapi"
)

// ChangePasswordReq represents the request for the security.change_password operation.
//
// Changes the password for the current user.
//
// PUT /_plugins/_security/api/account
//
// Available: >= 1.0.0.
//
// Not available on: amazon-managed, amazon-serverless.
//
// See: https://opensearch.org/docs/latest/security/access-control/api/#change-password
type ChangePasswordReq struct {

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *osapi.SecurityChangePasswordRequestContent

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *ChangePasswordParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r ChangePasswordReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.SecurityChangePasswordPath{}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		// Body contains a credential field whose JSON tag (e.g. "password")
		// matches gosec G117. The marshal here intentionally serializes the
		// credential because the OpenSearch security API requires it on the
		// wire; suppress the lint at the call site.
		bodyData, err := json.Marshal(r.Body) //nolint:gosec // G117: legitimate credential field for security API
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// ChangePasswordParams represents query parameters for the ChangePasswordReq.
type ChangePasswordParams struct {
	osapi.TimeoutParams
	osapi.DebugParams
}

func (r ChangePasswordParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// ChangePasswordResp represents the response for the security.change_password operation.
//
// Changes the password for the current user.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/security/access-control/api/#change-password
type ChangePasswordResp struct {
	// The message returned as part of an `OK` response.
	Message *string `json:"message,omitempty"`

	Status json.RawMessage `json:"status"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r ChangePasswordResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r ChangePasswordResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
