// Code generated by cmd/osgen; DO NOT EDIT.

package security

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// FlushCacheReq represents the request for the security.flush_cache operation.
//
// Flushes the Security plugin's user, authentication, and authorization cache.
//
// DELETE /_plugins/_security/api/cache
//
// Available: >= 1.0.0.
//
// Not available on: amazon-managed, amazon-serverless.
//
// See: https://opensearch.org/docs/latest/security/access-control/api/#flush-cache
type FlushCacheReq struct {

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params FlushCacheParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r FlushCacheReq) GetRequest() (*http.Request, error) {
	path, err := ospath.SecurityFlushCachePath{}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodDelete,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// FlushCacheParams represents query parameters for the FlushCacheReq.
type FlushCacheParams struct {

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r FlushCacheParams) get() map[string]string {
	params := make(map[string]string, 0)

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// FlushCacheResp represents the response for the security.flush_cache operation.
//
// Flushes the Security plugin's user, authentication, and authorization cache.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/security/access-control/api/#flush-cache
type FlushCacheResp struct {
	// The nessage returned as part of an `OK` response.
	Message *string `json:"message,omitempty"`

	Status *json.RawMessage `json:"status,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r FlushCacheResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}
