// Code generated by cmd/osgen; DO NOT EDIT.

package sm

import (
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/osapi"
)

// ExplainPolicyReq represents the request for the sm.explain_policy operation.
//
// Explains the state of the snapshot management policy.
//
// GET /_plugins/_sm/policies/{policy_name}/_explain
//
// Available: >= 2.1.0.
type ExplainPolicyReq struct {
	// PolicyName specifies the path segment for the request URL.
	PolicyName string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params ExplainPolicyParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r ExplainPolicyReq) GetRequest() (*http.Request, error) {
	path, err := ospath.SmExplainPolicyPath{
		PolicyName: r.PolicyName,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodGet,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// ExplainPolicyParams represents query parameters for the ExplainPolicyReq.
type ExplainPolicyParams struct {

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r ExplainPolicyParams) get() map[string]string {
	params := make(map[string]string, 0)

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// ExplainPolicyResp represents the response for the sm.explain_policy operation.
//
// Explains the state of the snapshot management policy.
//
// Available: >= 2.1.0.
type ExplainPolicyResp struct {
	Policies []osapi.SmExplainedPolicy `json:"policies,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r ExplainPolicyResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}
