// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package sm_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v4/osapi/plugins/sm"
)

func TestGetPoliciesReq_GetRequest(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name       string
		req        sm.GetPoliciesReq
		wantMethod string
		wantPath   string
		wantErr    bool
	}{
		{
			name:       "empty request",
			req:        sm.GetPoliciesReq{},
			wantMethod: "GET",
			wantPath:   "/_plugins/_sm/policies",
			wantErr:    false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			httpReq, err := tt.req.GetRequest()
			if tt.wantErr {
				require.Error(t, err)
				return
			}
			require.NoError(t, err)
			require.Equal(t, tt.wantMethod, httpReq.Method)
			require.Equal(t, tt.wantPath, httpReq.URL.Path)
		})
	}
}
