// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package ltr

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
	"github.com/opensearch-project/opensearch-go/v5/opensearchapi"
)

// GetFeatureReq represents the request for the ltr.get_feature operation.
//
// Get a feature from the default feature store.
//
// GET /_ltr/_feature/{id}
//
// Available: >= 2.19.0.
type GetFeatureReq struct {
	// ID specifies the path segment for the request URL.
	ID string

	// Store specifies the path segment for the request URL.
	Store string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *GetFeatureParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r GetFeatureReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.LTRGetFeaturePath{
		ID:    r.ID,
		Store: r.Store,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// GetFeatureParams represents query parameters for the GetFeatureReq.
type GetFeatureParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
}

func (r GetFeatureParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// GetFeatureResp represents the response for the GetFeature operation.
// The response body has a dynamic schema and is captured as raw JSON.
//
// Get a feature from the default feature store.
type GetFeatureResp struct {
	Body     json.RawMessage `json:"-"`
	response *opensearch.Response
}

// UnmarshalJSON captures the raw response body.
//
//nolint:unparam // error return required by json.Unmarshaler; raw passthrough never fails
func (r *GetFeatureResp) UnmarshalJSON(b []byte) error {
	r.Body = append(r.Body[:0], b...)
	return nil
}

// MarshalJSON returns the raw response body for comparison testing.
//
//nolint:unparam // error return required by json.Marshaler; raw passthrough never fails
func (r GetFeatureResp) MarshalJSON() ([]byte, error) {
	if r.Body == nil {
		return build.NullJSON, nil
	}
	return r.Body, nil
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r GetFeatureResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r GetFeatureResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
