// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package ism

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestRetryIndexParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params RetryIndexParams
		want   map[string]string
	}{
		{name: "empty", params: RetryIndexParams{}, want: nil},
		{
			name:   "index",
			params: RetryIndexParams{Indices: []string{"a", "b"}},
			want:   map[string]string{"index": "a,b"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
