// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package ism

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"strings"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/osapi"
)

// ChangePolicyReq represents the request for the ism.change_policy operation.
//
// Updates the managed index policy to a new policy.
//
// POST /_plugins/_ism/change_policy
//
// See: https://opensearch.org/docs/latest/im-plugin/ism/api/#update-managed-index-policy
type ChangePolicyReq struct {
	// Index specifies the list of path segments for the request URL.
	Index []string

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *osapi.IsmChangePolicyRequest

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *ChangePolicyParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r ChangePolicyReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.IsmChangePolicyPath{
		Index: r.Index,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		bodyData, err := json.Marshal(r.Body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// ChangePolicyParams represents query parameters for the ChangePolicyReq.
type ChangePolicyParams struct {
	osapi.TimeoutParams
	osapi.DebugParams
	Index []string
}

func (r ChangePolicyParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	if len(r.Index) > 0 {
		set("index", strings.Join(r.Index, ","))
	}

	return params
}

// ChangePolicyResp represents the response for the ism.change_policy operation.
//
// Updates the managed index policy to a new policy.
//
// See: https://opensearch.org/docs/latest/im-plugin/ism/api/#update-managed-index-policy
type ChangePolicyResp struct {
	// The list of indices that failed to update.
	FailedIndices []osapi.IsmFailedIndex `json:"failed_indices,omitempty"`

	// Whether there were any failures.
	Failures *bool `json:"failures,omitempty"`

	// The number of updated indices.
	UpdatedIndices *float64 `json:"updated_indices,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r ChangePolicyResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r ChangePolicyResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
