// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build integration

package ism_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi/plugins/ism"
	plugintest "github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi/plugins/ism/internal/ismtest"
	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi/testutil"
)

func TestExistsPolicy(t *testing.T) {
	t.Skip("requires existing ISM policy") //nolint:gocritic // FIXME: implement proper test fixture
	client, err := plugintest.NewClient(t)
	require.NoError(t, err)
	name := testutil.MustUniqueString(t, "test-exists-policy")

	t.Run("success", func(t *testing.T) {
		resp, err := client.ExistsPolicy(t.Context(), ism.ExistsPolicyReq{PolicyID: name})
		require.NoError(t, err)
		require.NotNil(t, resp)
		require.Greater(t, resp.StatusCode, 0)
	})
}
