// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package flow_framework

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/osapi"
)

// SearchStateReq represents the request for the flow_framework.search_state operation.
//
// Search for workflows by using a query matching a field.
//
// Path: /_plugins/_flow_framework/workflow/state/_search
//
// Methods: POST, GET
//
// Available: >= 2.12.0.
//
// See: https://opensearch.org/docs/latest/automating-configurations/api/search-workflow-state/
type SearchStateReq struct {

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *FlowFrameworkCommonSearchWorkflowRequest

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *SearchStateParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r SearchStateReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.FlowFrameworkSearchStatePath{}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		bodyData, err := json.Marshal(r.Body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// SearchStateParams represents query parameters for the SearchStateReq.
type SearchStateParams struct {
	osapi.TimeoutParams
	osapi.DebugParams
}

func (r SearchStateParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// SearchStateResp represents the response for the SearchState operation.
// The response body has a dynamic schema and is captured as raw JSON.
//
// Search for workflows by using a query matching a field.
//
// See: https://opensearch.org/docs/latest/automating-configurations/api/search-workflow-state/
type SearchStateResp struct {
	Body     json.RawMessage `json:"-"`
	response *opensearch.Response
}

// UnmarshalJSON captures the raw response body.
//
//nolint:unparam // error return required by json.Unmarshaler; raw passthrough never fails
func (r *SearchStateResp) UnmarshalJSON(b []byte) error {
	r.Body = append(r.Body[:0], b...)
	return nil
}

// MarshalJSON returns the raw response body for comparison testing.
//
//nolint:unparam // error return required by json.Marshaler; raw passthrough never fails
func (r SearchStateResp) MarshalJSON() ([]byte, error) {
	if r.Body == nil {
		return build.NullJSON, nil
	}
	return r.Body, nil
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r SearchStateResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r SearchStateResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
