// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package ml

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi"
)

// ExecuteAlgorithmReq represents the request for the ml.execute_algorithm operation.
//
// Execute an algorithm.
//
// POST /_plugins/_ml/_execute/{algorithm_name}
//
// Available: >= 2.0.0.
type ExecuteAlgorithmReq struct {
	// AlgorithmName specifies the path segment for the request URL.
	AlgorithmName string

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *MlExecuteAlgorithmBody

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *ExecuteAlgorithmParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r ExecuteAlgorithmReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.MlExecuteAlgorithmPath{
		AlgorithmName: r.AlgorithmName,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		bodyData, err := json.Marshal(r.Body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// ExecuteAlgorithmParams represents query parameters for the ExecuteAlgorithmReq.
type ExecuteAlgorithmParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
}

func (r ExecuteAlgorithmParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// ExecuteAlgorithmResp represents the response for the ExecuteAlgorithm operation.
// The response body has a dynamic schema and is captured as raw JSON.
//
// Execute an algorithm.
type ExecuteAlgorithmResp struct {
	Body     json.RawMessage `json:"-"`
	response *opensearch.Response
}

// UnmarshalJSON captures the raw response body.
//
//nolint:unparam // error return required by json.Unmarshaler; raw passthrough never fails
func (r *ExecuteAlgorithmResp) UnmarshalJSON(b []byte) error {
	r.Body = append(r.Body[:0], b...)
	return nil
}

// MarshalJSON returns the raw response body for comparison testing.
//
//nolint:unparam // error return required by json.Marshaler; raw passthrough never fails
func (r ExecuteAlgorithmResp) MarshalJSON() ([]byte, error) {
	if r.Body == nil {
		return build.NullJSON, nil
	}
	return r.Body, nil
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r ExecuteAlgorithmResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r ExecuteAlgorithmResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// MlExecuteAlgorithmBody is a typed component of the ml.execute_algorithm operation.
type MlExecuteAlgorithmBody struct {
	Aggregations []opensearchapi.MlAggregation `json:"aggregations,omitempty"`

	// The attribute field names
	AttributeFieldNames []string `json:"attribute_field_names,omitempty"`

	// The end time.
	EndTime *int64 `json:"end_time,omitempty"`

	// The index name.
	IndexName *string `json:"index_name,omitempty"`

	// The input data.
	InputData []float64 `json:"input_data,omitempty"`

	// The metrics input.
	Metrics [][]float64 `json:"metrics,omitempty"`

	// The minimum time interval.
	MinTimeInterval *int64 `json:"min_time_interval,omitempty"`

	// The number of outputs.
	NumOutputs *int64 `json:"num_outputs,omitempty"`

	// The calculator operation.
	Operation *string `json:"operation,omitempty"`

	// The start time.
	StartTime *int64 `json:"start_time,omitempty"`

	// The time field name.
	TimeFieldName *string `json:"time_field_name,omitempty"`
}
