// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package ml

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/osapi"
)

// GetMemoryReq represents the request for the ml.get_memory operation.
//
// Get a memory.
//
// GET /_plugins/_ml/memory/{memory_id}
//
// Available: >= 2.12.0.
type GetMemoryReq struct {
	// MemoryID specifies the path segment for the request URL.
	MemoryID string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *GetMemoryParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r GetMemoryReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.MlGetMemoryPath{
		MemoryID: r.MemoryID,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// GetMemoryParams represents query parameters for the GetMemoryReq.
type GetMemoryParams struct {
	osapi.TimeoutParams
	osapi.DebugParams
}

func (r GetMemoryParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// GetMemoryResp represents the response for the ml.get_memory operation.
//
// Get a memory.
//
// Available: >= 2.12.0.
type GetMemoryResp struct {
	// Additional information query.
	AdditionalInfo map[string]json.RawMessage `json:"additional_info,omitempty"`

	// The create time.
	CreateTime *string `json:"create_time,omitempty"`

	// The name of a resource or configuration element.
	MemoryID *string `json:"memory_id,omitempty"`

	// The name of a resource or configuration element.
	Name *string `json:"name,omitempty"`

	Type *string `json:"type,omitempty"`

	// The updated time.
	UpdatedTime *string `json:"updated_time,omitempty"`

	// The username of the user.
	User *string `json:"user,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r GetMemoryResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r GetMemoryResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
