// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package ml

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi"
)

// GetProfileTasksReq represents the request for the ml.get_profile_tasks operation.
//
// Get a profile tasks.
//
// GET /_plugins/_ml/profile/tasks
//
// Available: >= 2.4.0.
type GetProfileTasksReq struct {
	// TaskID specifies the path segment for the request URL.
	TaskID string

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *opensearchapi.MlProfileRequest

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *GetProfileTasksParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r GetProfileTasksReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.MlGetProfileTasksPath{
		TaskID: r.TaskID,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		bodyData, err := json.Marshal(r.Body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// GetProfileTasksParams represents query parameters for the GetProfileTasksReq.
type GetProfileTasksParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
}

func (r GetProfileTasksParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// GetProfileTasksResp represents the response for the ml.get_profile_tasks operation.
//
// Get a profile tasks.
//
// Available: >= 2.4.0.
type GetProfileTasksResp struct {
	Nodes map[string]opensearchapi.MlNode `json:"nodes,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r GetProfileTasksResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r GetProfileTasksResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
