// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package ml_test

import (
	"net/http"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi/plugins/ml"
)

func TestSearchAgenticMemoryReq_GetRequest(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name       string
		req        ml.SearchAgenticMemoryReq
		wantMethod string
		wantPath   string
		wantErr    bool
	}{
		{
			name:       "missing required fields",
			req:        ml.SearchAgenticMemoryReq{},
			wantMethod: "",
			wantPath:   "",
			wantErr:    true,
		},
		{
			name:       "all path fields",
			req:        ml.SearchAgenticMemoryReq{MemoryContainerID: "test-memorycontainerid", Type: "test-type"},
			wantMethod: http.MethodGet,
			wantPath:   "/_plugins/_ml/memory_containers/test-memorycontainerid/memories/test-type/_search",
			wantErr:    false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			httpReq, err := tt.req.GetRequest(tt.wantMethod)
			if tt.wantErr {
				require.Error(t, err)
				return
			}
			require.NoError(t, err)
			require.Equal(t, tt.wantMethod, httpReq.Method)
			require.Equal(t, tt.wantPath, httpReq.URL.Path)
		})
	}
}
