// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package ml_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi/plugins/ml"
)

func TestSearchTasksReq_GetRequest(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name       string
		req        ml.SearchTasksReq
		wantMethod string
		wantPath   string
		wantErr    bool
	}{
		{
			name:       "empty request",
			req:        ml.SearchTasksReq{},
			wantMethod: "GET",
			wantPath:   "/_plugins/_ml/tasks/_search",
			wantErr:    false,
		},
		{
			name:       "body triggers POST",
			req:        ml.SearchTasksReq{Body: &ml.MlSearchTasksBody{}},
			wantMethod: "POST",
			wantPath:   "/_plugins/_ml/tasks/_search",
			wantErr:    false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			httpReq, err := tt.req.GetRequest(tt.wantMethod)
			if tt.wantErr {
				require.Error(t, err)
				return
			}
			require.NoError(t, err)
			require.Equal(t, tt.wantMethod, httpReq.Method)
			require.Equal(t, tt.wantPath, httpReq.URL.Path)
		})
	}
}
