// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package ml

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi"
)

// SearchAgenticMemoryReq represents the request for the ml.search_agentic_memory operation.
//
// Search for memories of a specific type within a memory container.
//
// GET /_plugins/_ml/memory_containers/{memory_container_id}/memories/{type}/_search
//
// Available: >= 3.3.0.
type SearchAgenticMemoryReq struct {
	// MemoryContainerID specifies the path segment for the request URL.
	MemoryContainerID string

	// Type specifies the path segment for the request URL.
	Type string

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *MlSearchAgenticMemoryBody

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *SearchAgenticMemoryParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r SearchAgenticMemoryReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.MlSearchAgenticMemoryPath{
		MemoryContainerID: r.MemoryContainerID,
		Type:              r.Type,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		bodyData, err := json.Marshal(r.Body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// SearchAgenticMemoryParams represents query parameters for the SearchAgenticMemoryReq.
type SearchAgenticMemoryParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
}

func (r SearchAgenticMemoryParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// SearchAgenticMemoryResp represents the response for the ml.search_agentic_memory operation.
//
// Search for memories of a specific type within a memory container.
//
// Available: >= 3.3.0.
type SearchAgenticMemoryResp struct {
	Shards *opensearchapi.ShardStatistics `json:"_shards,omitempty"`
	Hits   opensearchapi.MlSearchHits     `json:"hits"`

	// Whether the search timed out.
	TimedOut *bool `json:"timed_out,omitempty"`

	// The time taken to execute the search.
	Took *int `json:"took,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r SearchAgenticMemoryResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r SearchAgenticMemoryResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// MlSearchAgenticMemoryBody is a typed component of the ml.search_agentic_memory operation.
type MlSearchAgenticMemoryBody struct {
	Query *opensearchapi.CommonQueryDSLQueryContainer `json:"query,omitempty"`

	// The number of memory containers to return.
	Size *int64 `json:"size,omitempty"`

	Sort *MlSearchAgenticMemoryBodySort `json:"sort,omitempty"`
}

// MlSearchAgenticMemoryBodySort is a typed component of the ml.search_agentic_memory operation.
type MlSearchAgenticMemoryBodySort struct {
}
