// Code generated by cmd/osgen; DO NOT EDIT.

package rollups

import (
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// StartReq represents the request for the rollups.start operation.
//
// Starts the execution of an index rollup job.
//
// POST /_plugins/_rollup/jobs/{id}/_start
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/im-plugin/index-rollups/rollup-api/#start-or-stop-an-index-rollup-job
type StartReq struct {
	// ID specifies the path segment for the request URL.
	ID string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params StartParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r StartReq) GetRequest() (*http.Request, error) {
	path, err := ospath.RollupsStartPath{
		ID: r.ID,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodPost,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// StartParams represents query parameters for the StartReq.
type StartParams struct {

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r StartParams) get() map[string]string {
	params := make(map[string]string, 0)

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// StartResp represents the response for the rollups.start operation.
//
// Starts the execution of an index rollup job.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/im-plugin/index-rollups/rollup-api/#start-or-stop-an-index-rollup-job
type StartResp struct {
	// For a successful response, this value is always true. On failure, an
	// exception is returned instead.
	Acknowledged bool `json:"acknowledged"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r StartResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}
