// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package replication

import (
	"bytes"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi"
)

// FollowerStatsReq represents the request for the replication.follower_stats operation.
//
// Retrieves information about any follower (syncing) indexes on a specified cluster.
//
// GET /_plugins/_replication/follower_stats
//
// Available: >= 1.1.0.
//
// See: https://opensearch.org/docs/latest/tuning-your-cluster/replication-plugin/api/#get-follower-cluster-stats
type FollowerStatsReq struct {

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *FollowerStatsParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r FollowerStatsReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.ReplicationFollowerStatsPath{}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// FollowerStatsParams represents query parameters for the FollowerStatsReq.
type FollowerStatsParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
}

func (r FollowerStatsParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// FollowerStatsResp represents the response for the replication.follower_stats operation.
//
// Retrieves information about any follower (syncing) indexes on a specified cluster.
//
// Available: >= 1.1.0.
//
// See: https://opensearch.org/docs/latest/tuning-your-cluster/replication-plugin/api/#get-follower-cluster-stats
type FollowerStatsResp struct {
	// The number of failed read requests during replication.
	FailedReadRequests *float64 `json:"failed_read_requests,omitempty"`

	// The number of failed write requests during replication.
	FailedWriteRequests *float64 `json:"failed_write_requests,omitempty"`

	// The current checkpoint of the follower index.
	FollowerCheckpoint *float64 `json:"follower_checkpoint,omitempty"`

	IndexStats map[string]opensearchapi.ReplicationIndexFollowerStatus `json:"index_stats,omitempty"`

	// The current checkpoint of the leader index.
	LeaderCheckpoint *float64 `json:"leader_checkpoint,omitempty"`

	// The number of indexes currently bootstrapping.
	NumBootstrappingIndices *float64 `json:"num_bootstrapping_indices,omitempty"`

	// The number of indexes that have failed replication.
	NumFailedIndices *float64 `json:"num_failed_indices,omitempty"`

	// The number of active index-level replication tasks.
	NumIndexTasks *float64 `json:"num_index_tasks,omitempty"`

	// The number of indexes currently paused.
	NumPausedIndices *float64 `json:"num_paused_indices,omitempty"`

	// The number of active shard-level replication tasks.
	NumShardTasks *float64 `json:"num_shard_tasks,omitempty"`

	// The number of indexes currently syncing.
	NumSyncingIndices *float64 `json:"num_syncing_indices,omitempty"`

	// The total number of operations read during replication.
	OperationsRead *float64 `json:"operations_read,omitempty"`

	// The total number of operations written during replication.
	OperationsWritten *float64 `json:"operations_written,omitempty"`

	// The number of throttled read requests during replication.
	ThrottledReadRequests *float64 `json:"throttled_read_requests,omitempty"`

	// The number of throttled write requests during replication.
	ThrottledWriteRequests *float64 `json:"throttled_write_requests,omitempty"`

	// Certain APIs may return values, including numbers such as epoch
	// timestamps, as strings. This setting captures this behavior while
	// keeping the semantics of the field type. Depending on the target
	// language, code generators can keep the union or remove it and leniently
	// parse strings to the target type.
	TotalWriteTimeMillis *opensearchapi.ReplicationFollowerStatusTotalWriteTimeMillis `json:"total_write_time_millis,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r FollowerStatsResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r FollowerStatsResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
