// Code generated by cmd/osgen; DO NOT EDIT.

package knn

import (
	"io"
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// TrainModelReq represents the request for the knn.train_model operation.
//
// Create and train a model that can be used for initializing k-NN native library indexes during indexing.
//
// POST /_plugins/_knn/models/_train
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/search-plugins/knn/api/#train-model
type TrainModelReq struct {
	// ModelID specifies the path segment for the request URL.
	ModelID string

	// Body is the request payload, typically JSON-encoded.
	Body io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params TrainModelParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r TrainModelReq) GetRequest() (*http.Request, error) {
	path, err := ospath.KnnTrainModelPath{
		ModelID: r.ModelID,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodPost,
		path,
		r.Body,
		r.Params.get(),
		r.Header,
	)
}

// TrainModelParams represents query parameters for the TrainModelReq.
type TrainModelParams struct {
	// Preferred node to execute training.
	Preference string

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r TrainModelParams) get() map[string]string {
	params := make(map[string]string, 1)

	if r.Preference != "" {
		params["preference"] = r.Preference
	}

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// TrainModelResp represents the response for the knn.train_model operation.
//
// Create and train a model that can be used for initializing k-NN native library indexes during indexing.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/search-plugins/knn/api/#train-model
type TrainModelResp struct {
	ModelID string `json:"model_id"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r TrainModelResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}
