// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package wlm

import (
	"bytes"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/osapi"
)

// GetQueryGroupReq represents the request for the wlm.get_query_group operation.
//
// Retrieves the specified query group. If no query group is specified, all query groups in the cluster are retrieved.
//
// GET /_wlm/query_group
//
// Available: >= 2.17.0.
type GetQueryGroupReq struct {
	// Name specifies the path segment for the request URL.
	Name string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *GetQueryGroupParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r GetQueryGroupReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.WlmGetQueryGroupPath{
		Name: r.Name,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// GetQueryGroupParams represents query parameters for the GetQueryGroupReq.
type GetQueryGroupParams struct {
	osapi.TimeoutParams
	osapi.DebugParams
}

func (r GetQueryGroupParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// GetQueryGroupResp represents the response for the wlm.get_query_group operation.
//
// Retrieves the specified query group. If no query group is specified, all query groups in the cluster are retrieved.
//
// Available: >= 2.17.0.
type GetQueryGroupResp struct {
	QueryGroups []osapi.WlmQueryGroupResponse `json:"query_groups,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r GetQueryGroupResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r GetQueryGroupResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
