// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package ism

import (
	"bytes"
	"io"
	"net/http"
	"strconv"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
	"github.com/opensearch-project/opensearch-go/v5/opensearchapi"
)

// PutPolicyReq represents the request for the ism.put_policy operation.
//
// Creates or updates a policy.
//
// PUT /_plugins/_ism/policies/{policy_id}
//
// See: https://opensearch.org/docs/latest/im-plugin/ism/api/#create-policy
type PutPolicyReq struct {
	// PolicyID specifies the path segment for the request URL.
	PolicyID string

	// Body is the request payload, typically JSON-encoded.
	Body io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *PutPolicyParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r PutPolicyReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.ISMPutPolicyPath{
		PolicyID: r.PolicyID,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		r.Body,
		params,
		r.Header,
	)
}

// PutPolicyParams represents query parameters for the PutPolicyReq.
type PutPolicyParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
	// Only perform the operation if the document has this primary term.
	IfPrimaryTerm int

	// Only perform the operation if the document has this sequence number.
	IfSeqNo int
}

func (r PutPolicyParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	if r.IfPrimaryTerm != 0 {
		set("if_primary_term", strconv.Itoa(r.IfPrimaryTerm))
	}

	if r.IfSeqNo != 0 {
		set("if_seq_no", strconv.Itoa(r.IfSeqNo))
	}

	return params
}

// PutPolicyResp represents the response for the ism.put_policy operation.
//
// Creates or updates a policy.
//
// See: https://opensearch.org/docs/latest/im-plugin/ism/api/#create-policy
type PutPolicyResp struct {
	opensearchapi.ISMMetadata
	Policy *opensearchapi.ISMPolicyEnvelope `json:"policy,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r PutPolicyResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r PutPolicyResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
