// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build integration

package ism_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v5/opensearchapi"
	"github.com/opensearch-project/opensearch-go/v5/opensearchapi/plugins/ism"
	plugintest "github.com/opensearch-project/opensearch-go/v5/opensearchapi/plugins/ism/internal/ismtest"
	"github.com/opensearch-project/opensearch-go/v5/opensearchapi/testutil"
)

func TestRetryIndex(t *testing.T) {
	t.Skip("requires index with ISM policy attached") //nolint:gocritic // FIXME: implement proper test fixture
	client, err := plugintest.NewClient(t)
	require.NoError(t, err)

	osClient, err := testutil.NewClient(t)
	require.NoError(t, err)

	index := testutil.MustUniqueString(t, "test-retry-index")
	name := testutil.MustUniqueString(t, "test-retry-index")
	t.Cleanup(func() {
		_, _ = osClient.Indices.Delete(context.Background(), &opensearchapi.IndicesDeleteReq{Index: []string{index}})
	})

	_, err = osClient.Indices.Create(t.Context(), opensearchapi.IndicesCreateReq{Index: index})
	require.NoError(t, err)

	t.Run("success", func(t *testing.T) {
		resp, err := client.RetryIndex(t.Context(), &ism.RetryIndexReq{Params: &ism.RetryIndexParams{Index: []string{name}}, Index: []string{index}, Body: &opensearchapi.ISMRetryIndexRequest{}})
		require.NoError(t, err)
		require.NotNil(t, resp)
		testutil.CompareRawJSONwithParsedJSON(t, resp, resp.Inspect().Response)
	})

	t.Run("inspect", func(t *testing.T) {
		failingClient, err := plugintest.CreateFailingClient(t)
		require.NoError(t, err)

		res, err := failingClient.RetryIndex(t.Context(), &ism.RetryIndexReq{Index: []string{index}, Body: &opensearchapi.ISMRetryIndexRequest{}})
		require.Error(t, err)
		require.NotNil(t, res)
		plugintest.VerifyInspect(t, res.Inspect())
	})
}
