// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package security

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
	"github.com/opensearch-project/opensearch-go/v5/opensearchapi"
)

// DeleteActionGroupReq represents the request for the security.delete_action_group operation.
//
// Deletes the specified action group.
//
// DELETE /_plugins/_security/api/actiongroups/{action_group}
//
// Available: >= 1.0.0.
//
// Not available on: amazon-managed, amazon-serverless.
//
// See: https://opensearch.org/docs/latest/security/access-control/api/#delete-action-group
type DeleteActionGroupReq struct {
	// ActionGroup specifies the path segment for the request URL.
	ActionGroup string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *DeleteActionGroupParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r DeleteActionGroupReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.SecurityDeleteActionGroupPath{
		ActionGroup: r.ActionGroup,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// DeleteActionGroupParams represents query parameters for the DeleteActionGroupReq.
type DeleteActionGroupParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
}

func (r DeleteActionGroupParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// DeleteActionGroupResp represents the response for the security.delete_action_group operation.
//
// Deletes the specified action group.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/security/access-control/api/#delete-action-group
type DeleteActionGroupResp struct {
	// The message returned as part of an `OK` response.
	Message *string `json:"message,omitempty"`

	Status json.RawMessage `json:"status"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r DeleteActionGroupResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r DeleteActionGroupResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
