// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package opensearchapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
)

// CatCountReq represents the request for the cat.count operation.
//
// Provides quick access to the document count of the entire cluster or of an individual index.
//
// GET /_cat/count
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/cat/cat-count/
type CatCountReq struct {
	// Indices specifies the list of path segments for the request URL.
	Indices []string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *CatCountParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r CatCountReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.CatCountPath{
		Indices: r.Indices,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	} else {
		// This operation defaults the format query param (the typed Resp
		// only decodes that format). The default lives in Params.get(), so
		// build it from a zero-value Params when the caller passes none.
		params = CatCountParams{}.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// CatCountParams represents query parameters for the CatCountReq.
type CatCountParams struct {
	TimeoutParams
	DebugParams
}

func (r CatCountParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)
	if r.Format == "" {
		set("format", "json")
	}

	return params
}

// CatCountResp represents the response for the CatCount operation.
// The response body is a JSON array of records.
//
// Provides quick access to the document count of the entire cluster or of an individual index.
//
// See: https://opensearch.org/docs/latest/api-reference/cat/cat-count/
type CatCountResp struct {
	Records  []CatCountRecord `json:"-"`
	response *opensearch.Response
}

// UnmarshalJSON decodes the response body as an array of records.
func (r *CatCountResp) UnmarshalJSON(b []byte) error {
	return json.Unmarshal(b, &r.Records)
}

// MarshalJSON encodes the response body for comparison testing.
func (r CatCountResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(r.Records)
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r CatCountResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r CatCountResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// CatCountRecord is a typed component of the cat.count operation.
type CatCountRecord struct {
	// the document count
	Count *string `json:"count,omitempty"`

	// Certain APIs may return values, including numbers such as epoch
	// timestamps, as strings. This setting captures this behavior while
	// keeping the semantics of the field type. Depending on the target
	// language, code generators can keep the union or remove it and leniently
	// parse strings to the target type.
	Epoch *CatCountRecordEpoch `json:"epoch,omitempty"`

	// Time of day, expressed as HH:MM:SS.
	Timestamp *string `json:"timestamp,omitempty"`
}

// Certain APIs may return values, including numbers such as epoch timestamps, as strings. This setting captures
// this behavior while keeping the semantics of the field type.
//
// Depending on the target language, code generators can keep the union or remove it and leniently parse
// strings to the target type.
// Use Type() to determine which branch was decoded, then call
// the corresponding accessor.
type CatCountRecordEpoch struct {
	typ   CatCountRecordEpochType
	raw   json.RawMessage
	value any
}

// CatCountRecordEpochType discriminates the branches of CatCountRecordEpoch.
type CatCountRecordEpochType int

const (
	CatCountRecordEpochUnknownType CatCountRecordEpochType = iota
	CatCountRecordEpochInt64Type
	CatCountRecordEpochStringType
)

// Type returns which union branch was populated during decoding.
// Returns CatCountRecordEpochUnknownType if the value has not been decoded.
func (u *CatCountRecordEpoch) Type() CatCountRecordEpochType { return u.typ }

// RawJSON returns the union's JSON bytes. After decoding these are borrowed
// from the response buffer: valid only while the owning response value is
// reachable, must not be mutated, and must be copied if retained beyond it.
func (u *CatCountRecordEpoch) RawJSON() json.RawMessage { return u.raw }

// SetRaw stages pre-encoded JSON for marshaling. MarshalJSON emits raw
// verbatim when no typed branch is set. Use the NewCatCountRecordEpochFrom*
// constructors to populate a typed branch instead; SetRaw is the typed
// escape hatch for callers that already have wire-format bytes.
func (u *CatCountRecordEpoch) SetRaw(raw json.RawMessage) {
	u.raw = raw
	u.value = nil
	u.typ = CatCountRecordEpochUnknownType
}

// Int64 returns the int64 branch value.
func (u *CatCountRecordEpoch) Int64() int64 {
	if v, ok := u.value.(*int64); ok {
		return *v
	}
	var zero int64
	return zero
}

// NewCatCountRecordEpochFromInt64 returns a CatCountRecordEpoch populated with v
// on the Int64 branch.
func NewCatCountRecordEpochFromInt64(v int64) CatCountRecordEpoch {
	return CatCountRecordEpoch{
		typ:   CatCountRecordEpochInt64Type,
		value: &v,
	}
}

// String returns the string branch value.
func (u *CatCountRecordEpoch) String() string {
	if v, ok := u.value.(*string); ok {
		return *v
	}
	var zero string
	return zero
}

// NewCatCountRecordEpochFromString returns a CatCountRecordEpoch populated with v
// on the String branch.
func NewCatCountRecordEpochFromString(v string) CatCountRecordEpoch {
	return CatCountRecordEpoch{
		typ:   CatCountRecordEpochStringType,
		value: &v,
	}
}

func (u *CatCountRecordEpoch) UnmarshalJSON(data []byte) error {
	u.raw = data
	u.value = nil
	u.typ = CatCountRecordEpochUnknownType
	if len(data) == 0 || bytes.Equal(data, build.NullJSON) {
		return nil
	}
	switch {
	case data[0] >= '0' && data[0] <= '9' || data[0] == '-':
		var v int64
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.typ = CatCountRecordEpochInt64Type
		u.value = &v
	case data[0] == '"':
		var v string
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.typ = CatCountRecordEpochStringType
		u.value = &v
	default:
		return fmt.Errorf("CatCountRecordEpoch: unexpected JSON token: %s", data[:1])
	}
	return nil
}

func (u CatCountRecordEpoch) MarshalJSON() ([]byte, error) {
	if u.value != nil {
		return json.Marshal(u.value)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return build.NullJSON, nil
}

// Count provides quick access to the document count of the entire cluster or of an individual index.
//
// GET /_cat/count
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/cat/cat-count/
func (c catClient) Count(ctx context.Context, req *CatCountReq) (*CatCountResp, error) {
	if req == nil {
		req = &CatCountReq{}
	}

	var (
		data CatCountResp
		err  error
	)
	if data.response, err = request(
		ctx,
		c.apiClient,
		http.MethodGet,
		req, &data,
	); err != nil {
		return &data, err
	}
	return &data, nil
}
