// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package opensearchapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
)

// ClusterRemoteInfoReq represents the request for the cluster.remote_info operation.
//
// Returns the information about configured remote clusters.
//
// GET /_remote/info
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/remote-info/
type ClusterRemoteInfoReq struct {

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *ClusterRemoteInfoParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r ClusterRemoteInfoReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.ClusterRemoteInfoPath{}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// ClusterRemoteInfoParams represents query parameters for the ClusterRemoteInfoReq.
type ClusterRemoteInfoParams struct {
	TimeoutParams
	DebugParams
}

func (r ClusterRemoteInfoParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// ClusterRemoteInfoResp represents the response for the ClusterRemoteInfo operation.
// The response body is a JSON object keyed by resource name.
//
// Returns the information about configured remote clusters.
//
// See: https://opensearch.org/docs/latest/api-reference/remote-info/
type ClusterRemoteInfoResp struct {
	Entries  map[string]ClusterRemoteInfoCluster `json:"-"`
	response *opensearch.Response
}

// UnmarshalJSON decodes the response body as a string-keyed map.
func (r *ClusterRemoteInfoResp) UnmarshalJSON(b []byte) error {
	return json.Unmarshal(b, &r.Entries)
}

// MarshalJSON encodes the response body for comparison testing.
func (r ClusterRemoteInfoResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(r.Entries)
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r ClusterRemoteInfoResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r ClusterRemoteInfoResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// ClusterRemoteInfoClusterRemoteSniffInfo is a typed component of the cluster.remote_info operation.
type ClusterRemoteInfoClusterRemoteSniffInfo struct {
	Connected bool `json:"connected"`

	// InitialConnectTimeout is a duration. Units can be `nanos`, `micros`,
	// `ms` (milliseconds), `s` (seconds), `m` (minutes), `h` (hours) and `d`
	// (days). Also accepts `0` without a unit and `-1` to indicate an
	// unspecified value.
	InitialConnectTimeout string `json:"initial_connect_timeout"`

	MaxConnectionsPerCluster int      `json:"max_connections_per_cluster"`
	Mode                     string   `json:"mode"`
	NumNodesConnected        int64    `json:"num_nodes_connected"`
	Seeds                    []string `json:"seeds"`
	SkipUnavailable          bool     `json:"skip_unavailable"`
}

// ClusterRemoteInfoClusterRemoteProxyInfo is a typed component of the cluster.remote_info operation.
type ClusterRemoteInfoClusterRemoteProxyInfo struct {
	Connected bool `json:"connected"`

	// InitialConnectTimeout is a duration. Units can be `nanos`, `micros`,
	// `ms` (milliseconds), `s` (seconds), `m` (minutes), `h` (hours) and `d`
	// (days). Also accepts `0` without a unit and `-1` to indicate an
	// unspecified value.
	InitialConnectTimeout string `json:"initial_connect_timeout"`

	MaxProxySocketConnections int    `json:"max_proxy_socket_connections"`
	Mode                      string `json:"mode"`
	NumProxySocketsConnected  int    `json:"num_proxy_sockets_connected"`
	ProxyAddress              string `json:"proxy_address"`
	ServerName                string `json:"server_name"`
	SkipUnavailable           bool   `json:"skip_unavailable"`
}

// ClusterRemoteInfoCluster is a oneOf union whose branch the payload names itself.
//
// The OpenAPI spec declares a discriminator on ClusterRemoteInfoCluster: the mode
// property carries the branch name, so UnmarshalJSON reads that one property and
// decodes exactly that branch -- it never guesses, and a mode naming
// no known branch is an error rather than a silent mis-decode.
//
// Use Type() to learn which branch was decoded, then call the corresponding
// accessor.

type ClusterRemoteInfoCluster struct {
	typ   ClusterRemoteInfoClusterType
	raw   json.RawMessage
	value any
}

// ClusterRemoteInfoClusterType names which branch of ClusterRemoteInfoCluster is set.
type ClusterRemoteInfoClusterType int

const (
	ClusterRemoteInfoClusterUnknownType ClusterRemoteInfoClusterType = iota
	ClusterRemoteInfoClusterClusterRemoteSniffInfoType
	ClusterRemoteInfoClusterClusterRemoteProxyInfoType
)

// String names the branch, for diagnostics. Returns "unknown" when no branch has
// been decoded.
func (t ClusterRemoteInfoClusterType) String() string {
	switch t {
	case ClusterRemoteInfoClusterClusterRemoteSniffInfoType:
		return "ClusterRemoteSniffInfo"
	case ClusterRemoteInfoClusterClusterRemoteProxyInfoType:
		return "ClusterRemoteProxyInfo"
	default:
		return "unknown"
	}
}

// Type returns which union branch was populated during decoding.
// Returns ClusterRemoteInfoClusterUnknownType if the value has not been decoded.
func (u *ClusterRemoteInfoCluster) Type() ClusterRemoteInfoClusterType { return u.typ }

// RawJSON returns the union's JSON bytes. After decoding these are borrowed
// from the response buffer: valid only while the owning response value is
// reachable, must not be mutated, and must be copied if retained beyond it.
func (u *ClusterRemoteInfoCluster) RawJSON() json.RawMessage { return u.raw }

// SetRaw stages pre-encoded JSON for marshaling. MarshalJSON emits raw
// verbatim when no typed branch is set. Use the NewClusterRemoteInfoClusterFrom*
// constructors to populate a typed branch instead; SetRaw is the typed
// escape hatch for callers that already have wire-format bytes.
func (u *ClusterRemoteInfoCluster) SetRaw(raw json.RawMessage) {
	u.raw = raw
	u.value = nil
	u.typ = ClusterRemoteInfoClusterUnknownType
}

// ClusterRemoteSniffInfo returns the ClusterRemoteInfoClusterRemoteSniffInfo branch value. It returns a
// *UnionBranchError when the union holds a different branch, naming the branch
// that is set; the returned value is the zero ClusterRemoteInfoClusterRemoteSniffInfo in that case,
// which is indistinguishable from a decoded one, so check the error.
func (u *ClusterRemoteInfoCluster) ClusterRemoteSniffInfo() (ClusterRemoteInfoClusterRemoteSniffInfo, error) {
	if v, ok := u.value.(*ClusterRemoteInfoClusterRemoteSniffInfo); ok {
		return *v, nil
	}
	var zero ClusterRemoteInfoClusterRemoteSniffInfo
	return zero, &UnionBranchError{Union: "ClusterRemoteInfoCluster", Want: "ClusterRemoteSniffInfo", Got: u.typ.String()}
}

// NewClusterRemoteInfoClusterFromClusterRemoteSniffInfo returns a ClusterRemoteInfoCluster populated with v
// on the ClusterRemoteSniffInfo branch.
//
// It sets v.Mode to "sniff" so the value marshals with the
// discriminator the spec requires, and so the result decodes back to this branch.
func NewClusterRemoteInfoClusterFromClusterRemoteSniffInfo(v ClusterRemoteInfoClusterRemoteSniffInfo) ClusterRemoteInfoCluster {
	v.Mode = "sniff"
	return ClusterRemoteInfoCluster{
		typ:   ClusterRemoteInfoClusterClusterRemoteSniffInfoType,
		value: &v,
	}
}

// ClusterRemoteProxyInfo returns the ClusterRemoteInfoClusterRemoteProxyInfo branch value. It returns a
// *UnionBranchError when the union holds a different branch, naming the branch
// that is set; the returned value is the zero ClusterRemoteInfoClusterRemoteProxyInfo in that case,
// which is indistinguishable from a decoded one, so check the error.
func (u *ClusterRemoteInfoCluster) ClusterRemoteProxyInfo() (ClusterRemoteInfoClusterRemoteProxyInfo, error) {
	if v, ok := u.value.(*ClusterRemoteInfoClusterRemoteProxyInfo); ok {
		return *v, nil
	}
	var zero ClusterRemoteInfoClusterRemoteProxyInfo
	return zero, &UnionBranchError{Union: "ClusterRemoteInfoCluster", Want: "ClusterRemoteProxyInfo", Got: u.typ.String()}
}

// NewClusterRemoteInfoClusterFromClusterRemoteProxyInfo returns a ClusterRemoteInfoCluster populated with v
// on the ClusterRemoteProxyInfo branch.
//
// It sets v.Mode to "proxy" so the value marshals with the
// discriminator the spec requires, and so the result decodes back to this branch.
func NewClusterRemoteInfoClusterFromClusterRemoteProxyInfo(v ClusterRemoteInfoClusterRemoteProxyInfo) ClusterRemoteInfoCluster {
	v.Mode = "proxy"
	return ClusterRemoteInfoCluster{
		typ:   ClusterRemoteInfoClusterClusterRemoteProxyInfoType,
		value: &v,
	}
}

func (u *ClusterRemoteInfoCluster) UnmarshalJSON(data []byte) error {
	u.raw = data
	u.value = nil
	u.typ = ClusterRemoteInfoClusterUnknownType
	if len(data) == 0 || bytes.Equal(data, build.NullJSON) {
		return nil
	}
	discriminator, present, err := build.JSONDiscriminator(data, "mode")
	if err != nil {
		return fmt.Errorf("ClusterRemoteInfoCluster: reading mode discriminator: %w", err)
	}
	if !present {
		return fmt.Errorf("ClusterRemoteInfoCluster: payload has no mode discriminator: %s", data[:min(len(data), 64)])
	}
	switch discriminator {
	case "sniff":
		var v ClusterRemoteInfoClusterRemoteSniffInfo
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.typ = ClusterRemoteInfoClusterClusterRemoteSniffInfoType
		u.value = &v
	case "proxy":
		var v ClusterRemoteInfoClusterRemoteProxyInfo
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.typ = ClusterRemoteInfoClusterClusterRemoteProxyInfoType
		u.value = &v
	default:
		return fmt.Errorf("ClusterRemoteInfoCluster: unknown mode discriminator %q", discriminator)
	}
	return nil
}

func (u ClusterRemoteInfoCluster) MarshalJSON() ([]byte, error) {
	if u.value != nil {
		return json.Marshal(u.value)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return build.NullJSON, nil
}

// RemoteInfo returns the information about configured remote clusters.
//
// GET /_remote/info
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/remote-info/
func (c ClusterClient) RemoteInfo(ctx context.Context, req *ClusterRemoteInfoReq) (*ClusterRemoteInfoResp, error) {
	if req == nil {
		req = &ClusterRemoteInfoReq{}
	}

	var (
		data ClusterRemoteInfoResp
		err  error
	)
	if data.response, err = request(
		ctx,
		c.apiClient,
		http.MethodGet,
		req, &data,
	); err != nil {
		return &data, err
	}
	return &data, nil
}
