// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.
//
// Modifications Copyright OpenSearch Contributors. See
// GitHub history for details.

/*
Package opensearchapi provides a strongly-typed client for the OpenSearch REST API.

The package is generated by cmd/osgen from the OpenSearch API specification. Each API
operation has a Req type carrying path, query, and body parameters, a Resp type for the
decoded response, and (where applicable) a Params type for optional query parameters.
Operations are grouped into sub-clients that mirror the OpenSearch namespaces, such as
client.Cat, client.Cluster, client.Indices, client.Document, and client.Snapshot.

Create a client with NewClient or NewDefaultClient:

	client, err := opensearchapi.NewClient(opensearchapi.Config{
	  Client: opensearch.Config{
	    Addresses: []string{"https://localhost:9200"},
	    Username:  "admin",
	    Password:  "myStrongPassword123!",
	  },
	})
	if err != nil {
	  log.Fatal(err)
	}

Invoke an operation by calling its method with a context and a Req value:

	resp, err := client.Indices.Create(ctx, opensearchapi.IndicesCreateReq{Index: "movies"})

OpenSearch is a distributed system in which operations may partially succeed. By default
the client surfaces partial failures as errors; see the ../guides/usage-error_handling.md guide
for the canonical reference on partial-failure types and helpers. The ../guides/README.md
index outlines additional documentation resources covering client usage, response
handling, bulk requests, request router configuration, and more.

Plugin APIs (k-NN, ML, ISM, security, and others) live in the plugins package and wrap
the same shared opensearch.Client.
*/
package opensearchapi
