// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.
//
// Modifications Copyright OpenSearch Contributors. See
// GitHub history for details.

/*
Package opensearchapi provides a strongly-typed client for the OpenSearch REST API.

The package is generated by cmd/osgen from the OpenSearch API specification. Each API
operation has a Req type carrying path, query, and body parameters, a Resp type for the
decoded response, and (where applicable) a Params type for optional query parameters.
Every operation is invoked as a method on the top-level [Client] or on one of its
sub-clients (see [Client] and the Sub-clients section below).

This overview shows how to construct a client and apply the API. For task-oriented,
end-to-end guides (indexing, search, bulk, routing, error handling, and more) see the
[Guides] directory in the repository; each guide is the canonical reference for its topic.

# Client Creation

Create a client with [NewClient], or [NewDefaultClient] to read connection settings from
the standard OPENSEARCH_* environment variables:

	client, err := opensearchapi.NewClient(opensearchapi.Config{
	  Client: opensearch.Config{
	    Addresses: []string{"https://localhost:9200"},
	    Username:  "admin",
	    Password:  "myStrongPassword123!",
	  },
	})
	if err != nil {
	  log.Fatal(err)
	}

# Invoking Operations

Invoke an operation by calling its method with a context and a Req value. The method
returns the operation's typed Resp:

	resp, err := client.Indices.Create(ctx, opensearchapi.IndicesCreateReq{Index: "movies"})
	if err != nil {
	  log.Fatal(err)
	}

Index a document, then read it back, through the document sub-client:

	_, err = client.Doc.Index(ctx, opensearchapi.IndexReq{
	  Index:      "movies",
	  DocumentID: "1",
	  Body:       strings.NewReader(`{"title": "Moneyball"}`),
	})

	got, err := client.Doc.Get(ctx, opensearchapi.GetReq{Index: "movies", DocumentID: "1"})

Optional query parameters live on the Req's Params field. Every Resp also exposes the raw
transport response via its Inspect method for status codes, headers, and the unparsed body.

# Sub-clients

Operations are partitioned across the top-level Client and a set of sub-clients reached
through exported fields on Client. The partition is exclusive: a sub-client exposes only
its own operations, and the Client's own methods are not promoted onto sub-clients (nor the
reverse). Each sub-client below has its own godoc page listing its full method set; the
canonical field is listed first, with backward-compatibility aliases in parentheses:

  - client.Doc (alias client.Document) reaches [DocumentClient]: single-document and bulk operations (Get, Index, Bulk, Update, MGet, ...)
  - client.Index (aliases client.Indices, client.Indexes) reaches [IndicesClient]: index lifecycle, mappings, settings, aliases, templates
  - client.Cat reaches [CatClient]: compact human-readable cluster/index/node tables (Health, Indices, Nodes, Shards, ...)
  - client.Cluster reaches [ClusterClient]: cluster health, state, settings, routing, component templates
  - client.Nodes reaches [NodesClient]: per-node info, stats, usage, hot threads
  - client.Snapshot reaches [SnapshotClient]: snapshots and snapshot repositories
  - client.Ingest reaches [IngestClient]: ingest pipelines
  - client.Tasks reaches [TasksClient]: task management (List, Get, Cancel)
  - client.Dangling reaches [DanglingClient]: dangling index recovery
  - client.PIT (alias client.PointInTime) reaches [PointInTimeClient]: point-in-time search contexts
  - client.Scroll reaches [ScrollClient]: scroll search contexts
  - client.SearchPipeline reaches [SearchPipelineClient]: search pipelines

The Index and Snapshot sub-clients also carry nested sub-clients that predate the flat
methods and are retained for backward compatibility: client.Index.Alias, .Mapping, and
.Settings ([AliasClient], [MappingClient], [SettingsClient]), and
client.Snapshot.Repository ([RepositoryClient]). Their methods are deprecated in favor of
the equivalent flat methods on the parent (e.g. prefer client.Index.GetAlias over
client.Index.Alias.Get).

The top-level Client itself holds the cross-cutting query and search operations that do not
belong to a single resource family: Search, MSearch, SearchTemplate, Explain, Count,
FieldCaps, Reindex, DeleteByQuery, UpdateByQuery, the script operations (PutScript,
GetScript, ...), Info, and Ping. See [Client] for the full list.

A few method names appear on both Client and a sub-client. Client.Bulk, Client.MGet, and
Client.Update are backward-compatibility forwarders to the canonical methods on client.Doc.
Client.Count, Client.Info, and Client.Restore are distinct operations from the same-named
sub-client methods (they take different request types): Client.Count counts documents by
query while CatClient.Count returns a cat table; Client.Info returns cluster info while
NodesClient.Info returns node info; Client.Restore is a remote-store restore while
SnapshotClient.Restore restores a snapshot.

# Partial Failures

OpenSearch is a distributed system in which operations may partially succeed. By default the
client surfaces partial failures as errors, which a caller detects with a type switch over
[Errors]. The [Error Handling guide] is the canonical reference for the typed error model, the
error mask, and the recommended handling pattern.

# Plugin APIs

Plugin APIs (k-NN, ML, ISM, security, and others) live in the plugins packages and wrap the
same shared opensearch.Client. Each plugin package exposes its own Client and, where the
plugin has multiple resource families, its own sub-clients following the same model as above.

[Guides]: https://github.com/opensearch-project/opensearch-go/tree/main/guides
[Error Handling guide]: https://github.com/opensearch-project/opensearch-go/blob/main/guides/usage-error_handling.md
*/
package opensearchapi
