// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package opensearchapi

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
	"time"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
)

// IndicesSplitReq represents the request for the indices.split operation.
//
// Allows you to split an existing index into a new index with more primary shards.
//
// Path: /{index}/_split/{target}
//
// Methods: POST, PUT
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/index-apis/split/
type IndicesSplitReq struct {
	// Index specifies the path segment for the request URL.
	Index string

	// Target specifies the path segment for the request URL.
	Target string

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *IndicesSplitBody

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *IndicesSplitParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r IndicesSplitReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.IndicesSplitPath{
		Index:  r.Index,
		Target: r.Target,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		bodyData, err := json.Marshal(r.Body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// IndicesSplitParams represents query parameters for the IndicesSplitReq.
type IndicesSplitParams struct {
	TimeoutParams
	DebugParams
	// whether or not to copy settings from the source index.
	//
	// Default: false.
	CopySettings *bool

	// Explicit task execution timeout, only useful when `wait_for_completion`
	// is false, defaults to `1h`.
	TaskExecutionTimeout time.Duration

	// The number of shard copies that must be active before proceeding with
	// the operation. Set to `all` or any positive integer up to the total
	// number of shards in the index (`number_of_replicas+1`).
	WaitForActiveShards string

	// Should this request wait until the operation has completed before
	// returning.
	//
	// Available: >= 2.7.0.
	//
	// Default: true.
	WaitForCompletion *bool
}

func (r IndicesSplitParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	if r.CopySettings != nil {
		set("copy_settings", strconv.FormatBool(*r.CopySettings))
	}

	if r.TaskExecutionTimeout != 0 {
		set("task_execution_timeout", formatDuration(r.TaskExecutionTimeout))
	}

	if r.WaitForActiveShards != "" {
		set("wait_for_active_shards", r.WaitForActiveShards)
	}

	if r.WaitForCompletion != nil {
		set("wait_for_completion", strconv.FormatBool(*r.WaitForCompletion))
	}

	return params
}

// IndicesSplitResp represents the response for the indices.split operation.
//
// Allows you to split an existing index into a new index with more primary shards.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/index-apis/split/
type IndicesSplitResp struct {
	AcknowledgedRespBase
	Index              string `json:"index"`
	ShardsAcknowledged bool   `json:"shards_acknowledged"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r IndicesSplitResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r IndicesSplitResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// IndicesSplitBody is a typed component of the indices.split operation.
//
// The configuration for the target index (`settings` and `aliases`)
type IndicesSplitBody struct {
	// Aliases for the resulting index.
	Aliases map[string]IndicesAlias `json:"aliases,omitempty"`

	// Configuration options for the target index.
	Settings map[string]json.RawMessage `json:"settings,omitempty"`
}

// Split allows you to split an existing index into a new index with more primary shards.
//
// Path: /{index}/_split/{target}
//
// Methods: POST, PUT
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/index-apis/split/
func (c indicesClient) Split(ctx context.Context, req IndicesSplitReq) (*IndicesSplitResp, error) {
	var (
		data IndicesSplitResp
		err  error
	)
	if data.response, err = request(
		ctx,
		c.apiClient,
		http.MethodPost,
		req, &data,
	); err != nil {
		return &data, err
	}
	return &data, nil
}
