// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build integration

package opensearchapi_test

import (
	"context"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v5/opensearchapi"
	"github.com/opensearch-project/opensearch-go/v5/opensearchapi/testutil"
)

func TestIndicesExistsTemplate(t *testing.T) {
	client, err := testutil.NewClient(t)
	require.NoError(t, err)

	index := testutil.MustUniqueString(t, "test-indices-exists-template")
	name := testutil.MustUniqueString(t, "test-indices-exists-template")
	t.Cleanup(func() {
		_, _ = client.Indices.Delete(context.Background(), &opensearchapi.IndicesDeleteReq{Index: []string{index}})
	})

	_, err = client.Indices.PutTemplate(t.Context(), opensearchapi.IndicesPutTemplateReq{
		Name:       name,
		BodyReader: strings.NewReader(`{"index_patterns":["` + name + `-*"]}`),
	})
	require.NoError(t, err)
	t.Cleanup(func() {
		_, _ = client.Indices.DeleteTemplate(context.Background(), opensearchapi.IndicesDeleteTemplateReq{Name: name})
	})

	t.Run("success", func(t *testing.T) {
		resp, err := client.Index.ExistsTemplate(t.Context(), &opensearchapi.IndicesExistsTemplateReq{Name: []string{name}})
		require.NoError(t, err)
		require.NotNil(t, resp)
		require.Greater(t, resp.StatusCode, 0)
	})
}
