// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package opensearchapi

import (
	"bytes"
	"context"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
)

// IndicesDeleteAliasReq represents the request for the indices.delete_alias operation.
//
// Deletes an alias.
//
// DELETE /{index}/_alias/{name}
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/im-plugin/index-alias/#delete-aliases
type IndicesDeleteAliasReq struct {
	// Indices specifies the list of path segments for the request URL.
	Indices []string

	// Name specifies the list of path segments for the request URL.
	Name []string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *IndicesDeleteAliasParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r IndicesDeleteAliasReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.IndicesDeleteAliasPath{
		Indices: r.Indices,
		Name:    r.Name,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// IndicesDeleteAliasParams represents query parameters for the IndicesDeleteAliasReq.
type IndicesDeleteAliasParams struct {
	TimeoutParams
	DebugParams
}

func (r IndicesDeleteAliasParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// IndicesDeleteAliasResp represents the response for the indices.delete_alias operation.
//
// Deletes an alias.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/im-plugin/index-alias/#delete-aliases
type IndicesDeleteAliasResp struct {
	// For a successful response, this value is always true. On failure, an
	// exception is returned instead.
	Acknowledged bool `json:"acknowledged"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r IndicesDeleteAliasResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r IndicesDeleteAliasResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// DeleteAlias deletes an alias.
//
// DELETE /{index}/_alias/{name}
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/im-plugin/index-alias/#delete-aliases
func (c indicesClient) DeleteAlias(ctx context.Context, req *IndicesDeleteAliasReq) (*IndicesDeleteAliasResp, error) {
	if req == nil {
		req = &IndicesDeleteAliasReq{}
	}

	var (
		data IndicesDeleteAliasResp
		err  error
	)
	if data.response, err = request(
		ctx,
		c.apiClient,
		http.MethodDelete,
		req, &data,
	); err != nil {
		return &data, err
	}
	return &data, nil
}

// Deprecated: use IndicesDeleteAlias via the parent client instead.
func (c aliasClient) Delete(ctx context.Context, req *IndicesDeleteAliasReq) (*IndicesDeleteAliasResp, error) {
	if req == nil {
		req = &IndicesDeleteAliasReq{}
	}

	var (
		data IndicesDeleteAliasResp
		err  error
	)
	if data.response, err = request(
		ctx,
		c.apiClient,
		http.MethodDelete,
		req, &data,
	); err != nil {
		return &data, err
	}
	return &data, nil
}
