// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package opensearchapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strconv"
	"strings"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
)

// IndicesPutMappingReq represents the request for the indices.put_mapping operation.
//
// Updates the index mappings.
//
// Path: /{index}/_mapping
//
// Methods: POST, PUT
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/index-apis/put-mapping/
type IndicesPutMappingReq struct {
	// Indices specifies the list of path segments for the request URL.
	Indices []string

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *IndicesPutMappingBody

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *IndicesPutMappingParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r IndicesPutMappingReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.IndicesPutMappingPath{
		Indices: r.Indices,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		bodyData, err := json.Marshal(r.Body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// IndicesPutMappingParams represents query parameters for the IndicesPutMappingReq.
type IndicesPutMappingParams struct {
	TimeoutParams
	DebugParams
	// If `false`, the request returns an error if any wildcard expression,
	// index alias, or `_all` value targets only missing or closed indexes.
	// This behavior applies even if the request targets other open indexes.
	AllowNoIndices *bool

	// Type of index that wildcard patterns can match. If the request can
	// target data streams, this argument determines whether wildcard
	// expressions match hidden data streams. Supports comma-separated values,
	// such as `open,hidden`. Valid values are: `all`, `open`, `closed`,
	// `hidden`, `none`.
	ExpandWildcards []string

	// If `false`, the request returns an error if it targets a missing or
	// closed index.
	IgnoreUnavailable *bool

	// If `true`, the mappings are applied only to the current write index for
	// the target.
	//
	// Default: false.
	WriteIndexOnly *bool
}

func (r IndicesPutMappingParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	if r.AllowNoIndices != nil {
		set("allow_no_indices", strconv.FormatBool(*r.AllowNoIndices))
	}

	if len(r.ExpandWildcards) > 0 {
		set("expand_wildcards", strings.Join(r.ExpandWildcards, ","))
	}

	if r.IgnoreUnavailable != nil {
		set("ignore_unavailable", strconv.FormatBool(*r.IgnoreUnavailable))
	}

	if r.WriteIndexOnly != nil {
		set("write_index_only", strconv.FormatBool(*r.WriteIndexOnly))
	}

	return params
}

// IndicesPutMappingResp represents the response for the indices.put_mapping operation.
//
// Updates the index mappings.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/index-apis/put-mapping/
type IndicesPutMappingResp struct {
	AcknowledgedRespBase
	Shards *ShardStatistics `json:"_shards,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r IndicesPutMappingResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r IndicesPutMappingResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// IndicesPutMappingBody is a typed component of the indices.put_mapping operation.
//
// The mapping definition
type IndicesPutMappingBody struct {
	FieldNames *CommonMappingFieldNamesField `json:"_field_names,omitempty"`

	// Meta is the custom metadata attached to a resource.
	Meta map[string]json.RawMessage `json:"_meta,omitempty"`

	Routing *CommonMappingRoutingField `json:"_routing,omitempty"`
	Source  *CommonMappingSourceField  `json:"_source,omitempty"`

	// DateDetection. Controls whether dynamic date detection is enabled.
	DateDetection *bool `json:"date_detection,omitempty"`

	Dynamic *CommonMappingDynamic `json:"dynamic,omitempty"`

	// DynamicDateFormats. If date detection is enabled then new string fields
	// are checked against `dynamic_date_formats` and if the value matches then
	// a new date field is added instead of string.
	DynamicDateFormats []string `json:"dynamic_date_formats,omitempty"`

	// DynamicTemplates. Specify dynamic templates for the mapping.
	DynamicTemplates *IndicesPutMappingBodyDynamicTemplates `json:"dynamic_templates,omitempty"`

	// NumericDetection. Automatically map strings into numeric data types for
	// all fields.
	NumericDetection *bool `json:"numeric_detection,omitempty"`

	// Properties. Mapping for a field. For new fields, this mapping can
	// include: - Field name - Field data type - Mapping parameters
	Properties map[string]CommonMappingProperty `json:"properties,omitempty"`
}

//
// Specify dynamic templates for the mapping.
// The spec declares no discriminator, but each branch is a different JSON token
// class (object, array, string, number, boolean), so the payload's first byte
// selects one.
//
// Use Type() to determine which branch was decoded, then call
// the corresponding accessor.

type IndicesPutMappingBodyDynamicTemplates struct {
	typ   IndicesPutMappingBodyDynamicTemplatesType
	raw   json.RawMessage
	value any
}

// IndicesPutMappingBodyDynamicTemplatesType names which branch of IndicesPutMappingBodyDynamicTemplates is set.
type IndicesPutMappingBodyDynamicTemplatesType int

const (
	IndicesPutMappingBodyDynamicTemplatesUnknownType IndicesPutMappingBodyDynamicTemplatesType = iota
	IndicesPutMappingBodyDynamicTemplatesMapType
	IndicesPutMappingBodyDynamicTemplatesArrayType
)

// String names the branch, for diagnostics. Returns "unknown" when no branch has
// been decoded.
func (t IndicesPutMappingBodyDynamicTemplatesType) String() string {
	switch t {
	case IndicesPutMappingBodyDynamicTemplatesMapType:
		return "Map"
	case IndicesPutMappingBodyDynamicTemplatesArrayType:
		return "Array"
	default:
		return "unknown"
	}
}

// Type returns which union branch was populated during decoding.
// Returns IndicesPutMappingBodyDynamicTemplatesUnknownType if the value has not been decoded.
func (u *IndicesPutMappingBodyDynamicTemplates) Type() IndicesPutMappingBodyDynamicTemplatesType {
	return u.typ
}

// RawJSON returns the union's JSON bytes. After decoding these are borrowed
// from the response buffer: valid only while the owning response value is
// reachable, must not be mutated, and must be copied if retained beyond it.
func (u *IndicesPutMappingBodyDynamicTemplates) RawJSON() json.RawMessage { return u.raw }

// SetRaw stages pre-encoded JSON for marshaling. MarshalJSON emits raw
// verbatim when no typed branch is set. Use the NewIndicesPutMappingBodyDynamicTemplatesFrom*
// constructors to populate a typed branch instead; SetRaw is the typed
// escape hatch for callers that already have wire-format bytes.
func (u *IndicesPutMappingBodyDynamicTemplates) SetRaw(raw json.RawMessage) {
	u.raw = raw
	u.value = nil
	u.typ = IndicesPutMappingBodyDynamicTemplatesUnknownType
}

// Map returns the map[string]json.RawMessage branch value. It returns a
// *UnionBranchError when the union holds a different branch, naming the branch
// that is set; the returned value is the zero map[string]json.RawMessage in that case,
// which is indistinguishable from a decoded one, so check the error.
func (u *IndicesPutMappingBodyDynamicTemplates) Map() (map[string]json.RawMessage, error) {
	if v, ok := u.value.(*map[string]json.RawMessage); ok {
		return *v, nil
	}
	var zero map[string]json.RawMessage
	return zero, &UnionBranchError{Union: "IndicesPutMappingBodyDynamicTemplates", Want: "Map", Got: u.typ.String()}
}

// NewIndicesPutMappingBodyDynamicTemplatesFromMap returns a IndicesPutMappingBodyDynamicTemplates populated with v
// on the Map branch.
func NewIndicesPutMappingBodyDynamicTemplatesFromMap(v map[string]json.RawMessage) IndicesPutMappingBodyDynamicTemplates {
	return IndicesPutMappingBodyDynamicTemplates{
		typ:   IndicesPutMappingBodyDynamicTemplatesMapType,
		value: &v,
	}
}

// Array returns the []map[string]CommonMappingDynamicTemplate branch value. It returns a
// *UnionBranchError when the union holds a different branch, naming the branch
// that is set; the returned value is the zero []map[string]CommonMappingDynamicTemplate in that case,
// which is indistinguishable from a decoded one, so check the error.
func (u *IndicesPutMappingBodyDynamicTemplates) Array() ([]map[string]CommonMappingDynamicTemplate, error) {
	if v, ok := u.value.(*[]map[string]CommonMappingDynamicTemplate); ok {
		return *v, nil
	}
	var zero []map[string]CommonMappingDynamicTemplate
	return zero, &UnionBranchError{Union: "IndicesPutMappingBodyDynamicTemplates", Want: "Array", Got: u.typ.String()}
}

// NewIndicesPutMappingBodyDynamicTemplatesFromArray returns a IndicesPutMappingBodyDynamicTemplates populated with v
// on the Array branch.
func NewIndicesPutMappingBodyDynamicTemplatesFromArray(v []map[string]CommonMappingDynamicTemplate) IndicesPutMappingBodyDynamicTemplates {
	return IndicesPutMappingBodyDynamicTemplates{
		typ:   IndicesPutMappingBodyDynamicTemplatesArrayType,
		value: &v,
	}
}

func (u *IndicesPutMappingBodyDynamicTemplates) UnmarshalJSON(data []byte) error {
	u.raw = data
	u.value = nil
	u.typ = IndicesPutMappingBodyDynamicTemplatesUnknownType
	if len(data) == 0 || bytes.Equal(data, build.NullJSON) {
		return nil
	}
	switch {
	case data[0] == '{':
		var v map[string]json.RawMessage
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.typ = IndicesPutMappingBodyDynamicTemplatesMapType
		u.value = &v
	case data[0] == '[':
		var v []map[string]CommonMappingDynamicTemplate
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.typ = IndicesPutMappingBodyDynamicTemplatesArrayType
		u.value = &v
	default:
		return fmt.Errorf("IndicesPutMappingBodyDynamicTemplates: unexpected JSON token: %s", data[:1])
	}
	return nil
}

func (u IndicesPutMappingBodyDynamicTemplates) MarshalJSON() ([]byte, error) {
	if u.value != nil {
		return json.Marshal(u.value)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return build.NullJSON, nil
}

// PutMapping updates the index mappings.
//
// Path: /{index}/_mapping
//
// Methods: POST, PUT
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/index-apis/put-mapping/
func (c IndicesClient) PutMapping(ctx context.Context, req *IndicesPutMappingReq) (*IndicesPutMappingResp, error) {
	if req == nil {
		req = &IndicesPutMappingReq{}
	}

	var (
		data IndicesPutMappingResp
		err  error
	)
	if data.response, err = request(
		ctx,
		c.apiClient,
		http.MethodPost,
		req, &data,
	); err != nil {
		return &data, err
	}
	return &data, nil
}

// Deprecated: use IndicesPutMapping via the parent client instead.
func (c MappingClient) Put(ctx context.Context, req *IndicesPutMappingReq) (*IndicesPutMappingResp, error) {
	if req == nil {
		req = &IndicesPutMappingReq{}
	}

	var (
		data IndicesPutMappingResp
		err  error
	)
	if data.response, err = request(
		ctx,
		c.apiClient,
		http.MethodPost,
		req, &data,
	); err != nil {
		return &data, err
	}
	return &data, nil
}
