// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package opensearchapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"strconv"
	"strings"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
)

// IndicesCloseReq represents the request for the indices.close operation.
//
// Closes an index.
//
// POST /{index}/_close
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/index-apis/close-index/
type IndicesCloseReq struct {
	// Indices specifies the list of path segments for the request URL.
	Indices []string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *IndicesCloseParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r IndicesCloseReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.IndicesClosePath{
		Indices: r.Indices,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// IndicesCloseParams represents query parameters for the IndicesCloseReq.
type IndicesCloseParams struct {
	TimeoutParams
	DebugParams
	// If `false`, the request returns an error if any wildcard expression,
	// index alias, or `_all` value targets only missing or closed indexes.
	// This behavior applies even if the request targets other open indexes.
	AllowNoIndices *bool

	// Type of index that wildcard patterns can match. If the request can
	// target data streams, this argument determines whether wildcard
	// expressions match hidden data streams. Supports comma-separated values,
	// such as `open,hidden`. Valid values are: `all`, `open`, `closed`,
	// `hidden`, `none`.
	ExpandWildcards []string

	// If `false`, the request returns an error if it targets a missing or
	// closed index.
	IgnoreUnavailable *bool

	// The number of shard copies that must be active before proceeding with
	// the operation. Set to `all` or any positive integer up to the total
	// number of shards in the index (`number_of_replicas+1`).
	WaitForActiveShards string
}

func (r IndicesCloseParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	if r.AllowNoIndices != nil {
		set("allow_no_indices", strconv.FormatBool(*r.AllowNoIndices))
	}

	if len(r.ExpandWildcards) > 0 {
		set("expand_wildcards", strings.Join(r.ExpandWildcards, ","))
	}

	if r.IgnoreUnavailable != nil {
		set("ignore_unavailable", strconv.FormatBool(*r.IgnoreUnavailable))
	}

	if r.WaitForActiveShards != "" {
		set("wait_for_active_shards", r.WaitForActiveShards)
	}

	return params
}

// IndicesCloseResp represents the response for the indices.close operation.
//
// Closes an index.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/index-apis/close-index/
type IndicesCloseResp struct {
	AcknowledgedRespBase
	Indices            map[string]IndicesCloseIndexResult `json:"indices"`
	ShardsAcknowledged bool                               `json:"shards_acknowledged"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r IndicesCloseResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r IndicesCloseResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// IndicesCloseIndexResult is a typed component of the indices.close operation.
//
// The result of a close index operation.
type IndicesCloseIndexResult struct {
	// Whether the index was successfully closed.
	Closed bool `json:"closed"`

	// The status of individual shards during the close operation.
	Shards map[string]IndicesCloseShardResult `json:"shards,omitempty"`
}

// IndicesCloseShardResult is a typed component of the indices.close operation.
//
// The result of closing shards in an index.
type IndicesCloseShardResult struct {
	// The list of failures that occurred while closing shards.
	Failures []ShardFailure `json:"failures"`
}

// Close closes an index.
//
// POST /{index}/_close
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/index-apis/close-index/
func (c indicesClient) Close(ctx context.Context, req *IndicesCloseReq) (*IndicesCloseResp, error) {
	if req == nil {
		req = &IndicesCloseReq{}
	}

	var (
		data IndicesCloseResp
		err  error
	)
	if data.response, err = do(
		ctx,
		c.apiClient,
		http.MethodPost,
		req, &data,
	); err != nil {
		return &data, err
	}
	return &data, nil
}
