// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package opensearchapi

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
)

// PutScriptReq represents the request for the put_script operation.
//
// Creates or updates a script.
//
// Path: /_scripts/{id}
//
// Methods: POST, PUT
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/script-apis/create-stored-script/
type PutScriptReq struct {
	// ID specifies the path segment for the request URL.
	ID string

	// Context specifies the path segment for the request URL.
	Context string

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *PutScriptBody

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *PutScriptParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r PutScriptReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.PutScriptPath{
		ID:      r.ID,
		Context: r.Context,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		bodyData, err := json.Marshal(r.Body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// PutScriptParams represents query parameters for the PutScriptReq.
type PutScriptParams struct {
	TimeoutParams
	DebugParams
	// Context in which the script or search template should run. To prevent
	// errors, the API immediately compiles the script or template in this
	// context.
	Context string
}

func (r PutScriptParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	if r.Context != "" {
		set("context", r.Context)
	}

	return params
}

// PutScriptResp represents the response for the put_script operation.
//
// Creates or updates a script.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/script-apis/create-stored-script/
type PutScriptResp struct {
	// For a successful response, this value is always true. On failure, an
	// exception is returned instead.
	Acknowledged bool `json:"acknowledged"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r PutScriptResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r PutScriptResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// PutScriptBody is a typed component of the put_script operation.
//
// The document
type PutScriptBody struct {
	// The definition of a stored script.
	Script StoredScript `json:"script"`
}

// PutScript creates or updates a script.
//
// Path: /_scripts/{id}
//
// Methods: POST, PUT
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/script-apis/create-stored-script/
func (c Client) PutScript(ctx context.Context, req PutScriptReq) (*PutScriptResp, error) {
	var (
		data PutScriptResp
		err  error
	)
	if data.response, err = request(
		ctx,
		&c,
		http.MethodPost,
		req, &data,
	); err != nil {
		return &data, err
	}
	return &data, nil
}
