// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build integration

package opensearchapi_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v5/opensearchapi"
	osapitest "github.com/opensearch-project/opensearch-go/v5/opensearchapi/internal/osapitest"
	"github.com/opensearch-project/opensearch-go/v5/opensearchapi/testutil"
)

func TestReindex(t *testing.T) {
	t.Skip("requires source index with documents") //nolint:gocritic // FIXME: implement proper test fixture
	client, err := testutil.NewClient(t)
	require.NoError(t, err)

	t.Run("success", func(t *testing.T) {
		resp, err := client.Reindex(t.Context(), &opensearchapi.ReindexReq{Body: &opensearchapi.ReindexBody{}})
		require.NoError(t, err)
		require.NotNil(t, resp)
		testutil.CompareRawJSONwithParsedJSON(t, resp, resp.Inspect().Response)
	})

	t.Run("inspect", func(t *testing.T) {
		failingClient, err := osapitest.CreateFailingClient(t)
		require.NoError(t, err)

		res, err := failingClient.Reindex(t.Context(), &opensearchapi.ReindexReq{Body: &opensearchapi.ReindexBody{}})
		require.Error(t, err)
		require.NotNil(t, res)
		osapitest.VerifyInspect(t, res.Inspect())
	})
}
