// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package opensearchapi

import (
	"bytes"
	"context"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
)

// SnapshotVerifyRepositoryReq represents the request for the snapshot.verify_repository operation.
//
// Verifies a repository.
//
// POST /_snapshot/{repository}/_verify
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/snapshots/verify-snapshot-repository/
type SnapshotVerifyRepositoryReq struct {
	// Repository specifies the path segment for the request URL.
	Repository string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *SnapshotVerifyRepositoryParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r SnapshotVerifyRepositoryReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.SnapshotVerifyRepositoryPath{
		Repository: r.Repository,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// SnapshotVerifyRepositoryParams represents query parameters for the SnapshotVerifyRepositoryReq.
type SnapshotVerifyRepositoryParams struct {
	TimeoutParams
	DebugParams
}

func (r SnapshotVerifyRepositoryParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// SnapshotVerifyRepositoryResp represents the response for the snapshot.verify_repository operation.
//
// Verifies a repository.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/snapshots/verify-snapshot-repository/
type SnapshotVerifyRepositoryResp struct {
	Nodes map[string]SnapshotVerifyRepositoryCompactNodeInfo `json:"nodes"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r SnapshotVerifyRepositoryResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r SnapshotVerifyRepositoryResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// SnapshotVerifyRepositoryCompactNodeInfo is a typed component of the snapshot.verify_repository operation.
type SnapshotVerifyRepositoryCompactNodeInfo struct {
	// The name of the node that verified the repository.
	Name string `json:"name"`
}

// VerifyRepository verifies a repository.
//
// POST /_snapshot/{repository}/_verify
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/snapshots/verify-snapshot-repository/
func (c SnapshotClient) VerifyRepository(ctx context.Context, req SnapshotVerifyRepositoryReq) (*SnapshotVerifyRepositoryResp, error) {
	var (
		data SnapshotVerifyRepositoryResp
		err  error
	)
	if data.response, err = request(
		ctx,
		c.apiClient,
		http.MethodPost,
		req, &data,
	); err != nil {
		return &data, err
	}
	return &data, nil
}

// Deprecated: use SnapshotVerifyRepository via the parent client instead.
func (c RepositoryClient) Verify(ctx context.Context, req SnapshotVerifyRepositoryReq) (*SnapshotVerifyRepositoryResp, error) {
	var (
		data SnapshotVerifyRepositoryResp
		err  error
	)
	if data.response, err = request(
		ctx,
		c.apiClient,
		http.MethodPost,
		req, &data,
	); err != nil {
		return &data, err
	}
	return &data, nil
}
