// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package flow_framework

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
	"github.com/opensearch-project/opensearch-go/v5/opensearchapi"
)

// SearchStateReq represents the request for the flow_framework.search_state operation.
//
// Search for workflows by using a query matching a field.
//
// Path: /_plugins/_flow_framework/workflow/state/_search
//
// Methods: POST, GET
//
// Available: >= 2.12.0.
//
// See: https://opensearch.org/docs/latest/automating-configurations/api/search-workflow-state/
type SearchStateReq struct {

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *FlowFrameworkCommonSearchWorkflowRequest

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *SearchStateParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r SearchStateReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.FlowFrameworkSearchStatePath{}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		bodyData, err := json.Marshal(r.Body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// SearchStateParams represents query parameters for the SearchStateReq.
type SearchStateParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
}

func (r SearchStateParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// SearchStateResp represents the response for the flow_framework.search_state operation.
//
// Search for workflows by using a query matching a field.
//
// Available: >= 2.12.0.
//
// See: https://opensearch.org/docs/latest/automating-configurations/api/search-workflow-state/
type SearchStateResp struct {
	Shards *FlowFrameworkCommonShards    `json:"_shards,omitempty"`
	Hits   *FlowFrameworkCommonStateHits `json:"hits,omitempty"`

	// TimedOut. Whether the request timed out.
	TimedOut *bool `json:"timed_out,omitempty"`

	// Took is the amount of time in milliseconds that the request took to
	// complete.
	Took *int `json:"took,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r SearchStateResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r SearchStateResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// FlowFrameworkCommonStateHits is a typed component of the flow_framework.search_state operation.
type FlowFrameworkCommonStateHits struct {
	// Hits is the list of search hits.
	Hits []FlowFrameworkCommonStateItems `json:"hits,omitempty"`

	MaxScore *float32                  `json:"max_score"`
	Total    *FlowFrameworkCommonTotal `json:"total,omitempty"`
}

// FlowFrameworkCommonStateItems is a typed component of the flow_framework.search_state operation.
type FlowFrameworkCommonStateItems struct {
	// ID is the document ID.
	ID *string `json:"_id,omitempty"`

	// Index is the index name where the document resides.
	Index *string `json:"_index,omitempty"`

	// PrimaryTerm is the primary term of the document.
	PrimaryTerm *int `json:"_primary_term,omitempty"`

	// Score is the score of the search hit.
	Score *float32 `json:"_score,omitempty"`

	// SeqNo is the sequence number of the document.
	SeqNo *int `json:"_seq_no,omitempty"`

	Source *FlowFrameworkCommonSearchStateResponse `json:"_source,omitempty"`

	// Version is the version of the document.
	Version *int `json:"_version,omitempty"`
}

// FlowFrameworkCommonSearchStateResponse is a typed component of the flow_framework.search_state operation.
type FlowFrameworkCommonSearchStateResponse struct {
	// ProvisionEndTime. When the provisioning operation completed.
	ProvisionEndTime *string `json:"provision_end_time,omitempty"`

	// ProvisionStartTime. When the provisioning operation started.
	ProvisionStartTime *string `json:"provision_start_time,omitempty"`

	// ProvisioningProgress is the current progress status of the provisioning
	// operation.
	ProvisioningProgress *string `json:"provisioning_progress,omitempty"`

	ResourcesCreated *FlowFrameworkCommonSearchStateRespResourcesCreated `json:"resources_created,omitempty"`

	// State is the current state of the workflow.
	State *string `json:"state,omitempty"`

	User *FlowFrameworkCommonUser `json:"user,omitempty"`

	// WorkflowID is the ID of the workflow.
	WorkflowID *string `json:"workflow_id,omitempty"`
}

// FlowFrameworkCommonResourcesCreated is a typed component of the flow_framework.search_state operation.
type FlowFrameworkCommonResourcesCreated struct {
	// ResourceID is the unique identifier for the created resource.
	ResourceID *string `json:"resource_id,omitempty"`

	// ResourceType is the type of resource created.
	ResourceType *string `json:"resource_type,omitempty"`

	// WorkflowStepID is the unique identifier for the workflow step.
	WorkflowStepID *string `json:"workflow_step_id,omitempty"`

	// WorkflowStepName is the name of the workflow step.
	WorkflowStepName *string `json:"workflow_step_name,omitempty"`
}

// FlowFrameworkCommonSearchStateRespResourcesCreated is a oneOf union whose branches decode from different JSON tokens.
// The spec declares no discriminator, but each branch is a different JSON token
// class (object, array, string, number, boolean), so the payload's first byte
// selects one.
//
// Use Type() to determine which branch was decoded, then call
// the corresponding accessor.
type FlowFrameworkCommonSearchStateRespResourcesCreated struct {
	typ   FlowFrameworkCommonSearchStateRespResourcesCreatedType
	raw   json.RawMessage
	value any
}

// FlowFrameworkCommonSearchStateRespResourcesCreatedType names which branch of FlowFrameworkCommonSearchStateRespResourcesCreated is set.
type FlowFrameworkCommonSearchStateRespResourcesCreatedType int

const (
	FlowFrameworkCommonSearchStateRespResourcesCreatedUnknownType FlowFrameworkCommonSearchStateRespResourcesCreatedType = iota
	FlowFrameworkCommonSearchStateRespResourcesCreatedResourcesCreatedType
	FlowFrameworkCommonSearchStateRespResourcesCreatedArrayType
)

// String names the branch, for diagnostics. Returns "unknown" when no branch has
// been decoded.
func (t FlowFrameworkCommonSearchStateRespResourcesCreatedType) String() string {
	switch t {
	case FlowFrameworkCommonSearchStateRespResourcesCreatedResourcesCreatedType:
		return "ResourcesCreated"
	case FlowFrameworkCommonSearchStateRespResourcesCreatedArrayType:
		return "Array"
	default:
		return "unknown"
	}
}

// Type returns which union branch was populated during decoding.
// Returns FlowFrameworkCommonSearchStateRespResourcesCreatedUnknownType if the value has not been decoded.
func (u *FlowFrameworkCommonSearchStateRespResourcesCreated) Type() FlowFrameworkCommonSearchStateRespResourcesCreatedType {
	return u.typ
}

// RawJSON returns the union's JSON bytes. After decoding these are borrowed
// from the response buffer: valid only while the owning response value is
// reachable, must not be mutated, and must be copied if retained beyond it.
func (u *FlowFrameworkCommonSearchStateRespResourcesCreated) RawJSON() json.RawMessage { return u.raw }

// SetRaw stages pre-encoded JSON for marshaling. MarshalJSON emits raw
// verbatim when no typed branch is set. Use the NewFlowFrameworkCommonSearchStateRespResourcesCreatedFrom*
// constructors to populate a typed branch instead; SetRaw is the typed
// escape hatch for callers that already have wire-format bytes.
func (u *FlowFrameworkCommonSearchStateRespResourcesCreated) SetRaw(raw json.RawMessage) {
	u.raw = raw
	u.value = nil
	u.typ = FlowFrameworkCommonSearchStateRespResourcesCreatedUnknownType
}

// ResourcesCreated returns the FlowFrameworkCommonResourcesCreated branch value. It returns a
// *UnionBranchError when the union holds a different branch, naming the branch
// that is set; the returned value is the zero FlowFrameworkCommonResourcesCreated in that case,
// which is indistinguishable from a decoded one, so check the error.
func (u *FlowFrameworkCommonSearchStateRespResourcesCreated) ResourcesCreated() (FlowFrameworkCommonResourcesCreated, error) {
	if v, ok := u.value.(*FlowFrameworkCommonResourcesCreated); ok {
		return *v, nil
	}
	var zero FlowFrameworkCommonResourcesCreated
	return zero, &opensearchapi.UnionBranchError{Union: "FlowFrameworkCommonSearchStateRespResourcesCreated", Want: "ResourcesCreated", Got: u.typ.String()}
}

// NewFlowFrameworkCommonSearchStateRespResourcesCreatedFromResourcesCreated returns a FlowFrameworkCommonSearchStateRespResourcesCreated populated with v
// on the ResourcesCreated branch.
func NewFlowFrameworkCommonSearchStateRespResourcesCreatedFromResourcesCreated(v FlowFrameworkCommonResourcesCreated) FlowFrameworkCommonSearchStateRespResourcesCreated {
	return FlowFrameworkCommonSearchStateRespResourcesCreated{
		typ:   FlowFrameworkCommonSearchStateRespResourcesCreatedResourcesCreatedType,
		value: &v,
	}
}

// Array returns the []FlowFrameworkCommonResourcesCreated branch value. It returns a
// *UnionBranchError when the union holds a different branch, naming the branch
// that is set; the returned value is the zero []FlowFrameworkCommonResourcesCreated in that case,
// which is indistinguishable from a decoded one, so check the error.
func (u *FlowFrameworkCommonSearchStateRespResourcesCreated) Array() ([]FlowFrameworkCommonResourcesCreated, error) {
	if v, ok := u.value.(*[]FlowFrameworkCommonResourcesCreated); ok {
		return *v, nil
	}
	var zero []FlowFrameworkCommonResourcesCreated
	return zero, &opensearchapi.UnionBranchError{Union: "FlowFrameworkCommonSearchStateRespResourcesCreated", Want: "Array", Got: u.typ.String()}
}

// NewFlowFrameworkCommonSearchStateRespResourcesCreatedFromArray returns a FlowFrameworkCommonSearchStateRespResourcesCreated populated with v
// on the Array branch.
func NewFlowFrameworkCommonSearchStateRespResourcesCreatedFromArray(v []FlowFrameworkCommonResourcesCreated) FlowFrameworkCommonSearchStateRespResourcesCreated {
	return FlowFrameworkCommonSearchStateRespResourcesCreated{
		typ:   FlowFrameworkCommonSearchStateRespResourcesCreatedArrayType,
		value: &v,
	}
}

func (u *FlowFrameworkCommonSearchStateRespResourcesCreated) UnmarshalJSON(data []byte) error {
	u.raw = data
	u.value = nil
	u.typ = FlowFrameworkCommonSearchStateRespResourcesCreatedUnknownType
	if len(data) == 0 || bytes.Equal(data, build.NullJSON) {
		return nil
	}
	switch {
	case data[0] == '{':
		var v FlowFrameworkCommonResourcesCreated
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.typ = FlowFrameworkCommonSearchStateRespResourcesCreatedResourcesCreatedType
		u.value = &v
	case data[0] == '[':
		var v []FlowFrameworkCommonResourcesCreated
		if err := json.Unmarshal(data, &v); err != nil {
			return err
		}
		u.typ = FlowFrameworkCommonSearchStateRespResourcesCreatedArrayType
		u.value = &v
	default:
		return fmt.Errorf("FlowFrameworkCommonSearchStateRespResourcesCreated: unexpected JSON token: %s", data[:1])
	}
	return nil
}

func (u FlowFrameworkCommonSearchStateRespResourcesCreated) MarshalJSON() ([]byte, error) {
	if u.value != nil {
		return json.Marshal(u.value)
	}
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return build.NullJSON, nil
}
