// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package flow_framework

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
	"strconv"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
	"github.com/opensearch-project/opensearch-go/v5/opensearchapi"
)

// UpdateReq represents the request for the flow_framework.update operation.
//
// Updates a workflow template that has not been provisioned.
//
// PUT /_plugins/_flow_framework/workflow/{workflow_id}
//
// Available: >= 2.12.0.
//
// See: https://opensearch.org/docs/latest/automating-configurations/api/create-workflow/
type UpdateReq struct {
	// WorkflowID specifies the path segment for the request URL.
	WorkflowID string

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *FlowFrameworkCommonFlowFrameworkUpdate

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *UpdateParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r UpdateReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.FlowFrameworkUpdatePath{
		WorkflowID: r.WorkflowID,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		bodyData, err := json.Marshal(r.Body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// UpdateParams represents query parameters for the UpdateReq.
type UpdateParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
	// Default: false.
	Provision *bool

	// Available: >= 2.17.0.
	// Default: false.
	Reprovision *bool

	// Default: false.
	UpdateFields *bool

	// Specifies the workflow template to use.
	UseCase string

	// Default: all.
	Validation string
}

func (r UpdateParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	if r.Provision != nil {
		set("provision", strconv.FormatBool(*r.Provision))
	}

	if r.Reprovision != nil {
		set("reprovision", strconv.FormatBool(*r.Reprovision))
	}

	if r.UpdateFields != nil {
		set("update_fields", strconv.FormatBool(*r.UpdateFields))
	}

	if r.UseCase != "" {
		set("use_case", r.UseCase)
	}

	if r.Validation != "" {
		set("validation", r.Validation)
	}

	return params
}

// UpdateResp represents the response for the flow_framework.update operation.
//
// Updates a workflow template that has not been provisioned.
//
// Available: >= 2.12.0.
//
// See: https://opensearch.org/docs/latest/automating-configurations/api/create-workflow/
type UpdateResp struct {
	// The ID of the workflow to be updated. Required for the PUT method.
	WorkflowID string `json:"workflow_id"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r UpdateResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r UpdateResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// FlowFrameworkCommonFlowFrameworkUpdate is a typed component of the flow_framework.update operation.
type FlowFrameworkCommonFlowFrameworkUpdate struct {
	// A description of the workflow.
	Description *string `json:"description,omitempty"`

	// The name of the workflow.
	Name *string `json:"name,omitempty"`

	// A use case ID, which can be used with the Search Workflow API to find
	// related workflows.
	UseCase *string `json:"use_case,omitempty"`

	// A key-value map with two fields, template, which identifies the template
	// version, and compatibility, which identifies a list of minimum required
	// OpenSearch versions.
	Version *FlowFrameworkCommonVersion `json:"version,omitempty"`

	Workflows json.RawMessage `json:"workflows"`
}
