// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package search_relevance

import (
	"bytes"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
	"github.com/opensearch-project/opensearch-go/v5/opensearchapi"
)

// DeleteSearchConfigurationsReq represents the request for the search_relevance.delete_search_configurations operation.
//
// Deletes a specified search configuration.
//
// DELETE /_plugins/_search_relevance/search_configurations/{search_configuration_id}
//
// Available: >= 3.1.0.
type DeleteSearchConfigurationsReq struct {
	// SearchConfigurationID specifies the path segment for the request URL.
	SearchConfigurationID string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *DeleteSearchConfigurationsParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r DeleteSearchConfigurationsReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.SearchRelevanceDeleteSearchConfigurationsPath{
		SearchConfigurationID: r.SearchConfigurationID,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// DeleteSearchConfigurationsParams represents query parameters for the DeleteSearchConfigurationsReq.
type DeleteSearchConfigurationsParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
}

func (r DeleteSearchConfigurationsParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// DeleteSearchConfigurationsResp represents the response for the search_relevance.delete_search_configurations operation.
//
// Deletes a specified search configuration.
//
// Available: >= 3.1.0.
type DeleteSearchConfigurationsResp struct {
	// The unique identifier for a resource.
	ID string `json:"_id"`

	Index string `json:"_index"`

	// The primary term of the document.
	PrimaryTerm int64 `json:"_primary_term"`

	// The sequence number of the document.
	SeqNo int64 `json:"_seq_no"`

	Shards opensearchapi.ShardStatistics `json:"_shards"`

	// The type of document or resource.
	Type *string `json:"_type,omitempty"`

	Version       int64                `json:"_version"`
	ForcedRefresh *bool                `json:"forced_refresh,omitempty"`
	Result        opensearchapi.Result `json:"result"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r DeleteSearchConfigurationsResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r DeleteSearchConfigurationsResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
