// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package transforms_test

import (
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/plugins/transforms"
)

func TestExplainReq_GetRequest(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name       string
		req        transforms.ExplainReq
		wantMethod string
		wantPath   string
		wantErr    bool
	}{
		{
			name:       "missing required fields",
			req:        transforms.ExplainReq{},
			wantMethod: "",
			wantPath:   "",
			wantErr:    true,
		},
		{
			name:       "all path fields",
			req:        transforms.ExplainReq{ID: "test-id"},
			wantMethod: http.MethodGet,
			wantPath:   "/_plugins/_transform/test-id/_explain",
			wantErr:    false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			httpReq, err := tt.req.GetRequest(tt.wantMethod)
			if tt.wantErr {
				require.Error(t, err)
				return
			}
			require.NoError(t, err)
			require.Equal(t, tt.wantMethod, httpReq.Method)
			require.Equal(t, tt.wantPath, httpReq.URL.Path)
		})
	}
}

func TestExplain_Roundtrip(t *testing.T) {
	t.Parallel()

	t.Run("success", func(t *testing.T) {
		t.Parallel()
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusOK)
			_, _ = io.WriteString(w, `{}`)
		}))
		t.Cleanup(ts.Close)

		osClient, err := opensearch.NewClient(opensearch.Config{Addresses: []string{ts.URL}})
		require.NoError(t, err)
		client := transforms.NewClient(osClient)

		resp, err := client.Explain(t.Context(), transforms.ExplainReq{ID: "test"})
		require.NoError(t, err)
		require.NotNil(t, resp)
		require.NotNil(t, resp.Inspect().Response)
	})

	t.Run("error", func(t *testing.T) {
		t.Parallel()
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusBadRequest)
			_, _ = io.WriteString(w, `{"status":400,"error":{"reason":"test error","type":"invalid_request"}}`)
		}))
		t.Cleanup(ts.Close)

		osClient, err := opensearch.NewClient(opensearch.Config{Addresses: []string{ts.URL}})
		require.NoError(t, err)
		errClient := transforms.NewClient(osClient)

		resp, err := errClient.Explain(t.Context(), transforms.ExplainReq{ID: "test"})
		require.Error(t, err)
		require.NotNil(t, resp)
	})
}
