// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package observability

import (
	"bytes"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v5"
	"github.com/opensearch-project/opensearch-go/v5/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v5/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v5/internal/path"
	"github.com/opensearch-project/opensearch-go/v5/opensearchapi"
)

// ListObjectsReq represents the request for the observability.list_objects operation.
//
// Retrieves list of all observability objects.
//
// GET /_plugins/_observability/object
//
// Available: >= 1.1.0.
type ListObjectsReq struct {

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *ListObjectsParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r ListObjectsReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.ObservabilityListObjectsPath{}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// ListObjectsParams represents query parameters for the ListObjectsReq.
type ListObjectsParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
}

func (r ListObjectsParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// ListObjectsResp represents the response for the observability.list_objects operation.
//
// Retrieves list of all observability objects.
//
// Available: >= 1.1.0.
type ListObjectsResp struct {
	// The list of observability objects.
	ObservabilityObjectList []opensearchapi.ObservabilityObject `json:"observabilityObjectList"`

	// The starting index of the returned objects.
	StartIndex int `json:"startIndex"`

	// The relationship of total hits to the query.
	TotalHitRelation string `json:"totalHitRelation"`

	// The total number of matching objects.
	TotalHits int `json:"totalHits"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r ListObjectsResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r ListObjectsResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
