// Code generated by cmd/osgen; DO NOT EDIT.

package ltr

import (
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// DeleteDefaultStoreReq represents the request for the ltr.delete_default_store operation.
//
// Deletes the default feature store.
//
// DELETE /_ltr
//
// Available: >= 2.17.1.
type DeleteDefaultStoreReq struct {

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params DeleteDefaultStoreParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r DeleteDefaultStoreReq) GetRequest() (*http.Request, error) {
	path, err := ospath.LtrDeleteDefaultStorePath{}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodDelete,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// DeleteDefaultStoreParams represents query parameters for the DeleteDefaultStoreReq.
type DeleteDefaultStoreParams struct {

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r DeleteDefaultStoreParams) get() map[string]string {
	params := make(map[string]string, 0)

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// DeleteDefaultStoreResp represents the response for the ltr.delete_default_store operation.
//
// Deletes the default feature store.
//
// Available: >= 2.17.1.
type DeleteDefaultStoreResp struct {
	// Indicates whether the request was acknowledged.
	Acknowledged *bool `json:"acknowledged,omitempty"`

	// The name of the index.
	Index *string `json:"index,omitempty"`

	// Indicates whether the required active shards were acknowledged.
	ShardsAcknowledged *bool `json:"shards_acknowledged,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r DeleteDefaultStoreResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}
