// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package ltr_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v4/osapi/plugins/ltr"
)

func TestSearchFeaturesetsReq_GetRequest(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name       string
		req        ltr.SearchFeaturesetsReq
		wantMethod string
		wantPath   string
		wantErr    bool
	}{
		{
			name:       "empty request",
			req:        ltr.SearchFeaturesetsReq{},
			wantMethod: "GET",
			wantPath:   "/_ltr/_featureset",
			wantErr:    false,
		},
		{
			name:       "all path fields",
			req:        ltr.SearchFeaturesetsReq{Store: "test-store"},
			wantMethod: "GET",
			wantPath:   "/_ltr/test-store/_featureset",
			wantErr:    false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			httpReq, err := tt.req.GetRequest(tt.wantMethod)
			if tt.wantErr {
				require.Error(t, err)
				return
			}
			require.NoError(t, err)
			require.Equal(t, tt.wantMethod, httpReq.Method)
			require.Equal(t, tt.wantPath, httpReq.URL.Path)
		})
	}
}
