// Code generated by cmd/osgen; DO NOT EDIT.

package notifications

import (
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/osapi"
)

// GetConfigReq represents the request for the notifications.get_config operation.
//
// Get a specific channel configuration.
//
// GET /_plugins/_notifications/configs/{config_id}
//
// Available: >= 2.0.0.
type GetConfigReq struct {
	// ConfigID specifies the path segment for the request URL.
	ConfigID string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params GetConfigParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r GetConfigReq) GetRequest() (*http.Request, error) {
	path, err := ospath.NotificationsGetConfigPath{
		ConfigID: r.ConfigID,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodGet,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// GetConfigParams represents query parameters for the GetConfigReq.
type GetConfigParams struct {

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r GetConfigParams) get() map[string]string {
	params := make(map[string]string, 0)

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// GetConfigResp represents the response for the notifications.get_config operation.
//
// Get a specific channel configuration.
//
// Available: >= 2.0.0.
type GetConfigResp struct {
	ConfigList       []osapi.NotificationsConfigsOutputItem `json:"config_list,omitempty"`
	StartIndex       *int64                                 `json:"start_index,omitempty"`
	TotalHitRelation *string                                `json:"total_hit_relation,omitempty"`
	TotalHits        *int64                                 `json:"total_hits,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r GetConfigResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}
