// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package opensearchapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"strconv"
	"strings"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	"github.com/opensearch-project/opensearch-go/v4/internal/errmask"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// BulkReq represents the request for the bulk operation.
//
// Allows to perform multiple index/update/delete operations in a single request.
//
// Path: /_bulk
//
// Methods: POST, PUT
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/document-apis/bulk/
type BulkReq struct {
	// Index specifies the path segment for the request URL.
	Index string

	// Body is the request payload, typically JSON-encoded.
	Body io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *BulkParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r BulkReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.BulkPath{
		Index: r.Index,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	// _bulk and _msearch take application/x-ndjson; build.Request defaults
	// to application/json when the caller leaves Content-Type unset, so
	// we set it here. Caller-provided Content-Type still wins.
	headers := r.Header
	if headers.Get(build.HeaderContentType) == "" {
		headers = headers.Clone()
		if headers == nil {
			headers = make(http.Header, 1)
		}
		headers.Set(build.HeaderContentType, build.ContentTypeNDJSON)
	}

	return build.Request(
		method,
		path,
		r.Body,
		params,
		headers,
	)
}

// BulkParams represents query parameters for the BulkReq.
type BulkParams struct {
	TimeoutParams
	DebugParams
	// `true` or `false` to return the `_source` field or not, or a list of
	// fields to return.
	Source string

	// A comma-separated list of source fields to exclude from the response.
	SourceExcludes []string

	// A comma-separated list of source fields to include in the response.
	SourceIncludes []string

	// Name of the data stream, index, or index alias to perform bulk actions
	// on.
	Index string

	// ID of the pipeline to use to preprocess incoming documents. If the index
	// has a default ingest pipeline specified, then setting the value to
	// `_none` disables the default ingest pipeline for this request. If a
	// final pipeline is configured it will always run, regardless of the value
	// of this parameter.
	Pipeline string

	// If `true`, OpenSearch refreshes the affected shards to make this
	// operation visible to search, if `wait_for` then wait for a refresh to
	// make this operation visible to search, if `false` do nothing with
	// refreshes. Valid values: `true`, `false`, `wait_for`.
	Refresh string

	// If `true`, the request's actions must target an index alias.
	//
	// Default: false.
	RequireAlias *bool

	// A custom value used to route operations to a specific shard.
	Routing string

	// Default document type for items which don't provide one.
	Type string

	// The number of shard copies that must be active before proceeding with
	// the operation. Set to all or any positive integer up to the total number
	// of shards in the index (`number_of_replicas+1`).
	WaitForActiveShards string
}

func (r BulkParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	if r.Source != "" {
		set("_source", r.Source)
	}

	if len(r.SourceExcludes) > 0 {
		set("_source_excludes", strings.Join(r.SourceExcludes, ","))
	}

	if len(r.SourceIncludes) > 0 {
		set("_source_includes", strings.Join(r.SourceIncludes, ","))
	}

	if r.Index != "" {
		set("index", r.Index)
	}

	if r.Pipeline != "" {
		set("pipeline", r.Pipeline)
	}

	if r.Refresh != "" {
		set("refresh", r.Refresh)
	}

	if r.RequireAlias != nil {
		set("require_alias", strconv.FormatBool(*r.RequireAlias))
	}

	if r.Routing != "" {
		set("routing", r.Routing)
	}

	if r.Type != "" {
		set("type", r.Type)
	}

	if r.WaitForActiveShards != "" {
		set("wait_for_active_shards", r.WaitForActiveShards)
	}

	return params
}

// BulkResp represents the response for the bulk operation.
//
// Allows to perform multiple index/update/delete operations in a single request.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/document-apis/bulk/
type BulkResp struct {
	Errors     bool       `json:"errors"`
	IngestTook *int64     `json:"ingest_took,omitempty"`
	Items      []BulkItem `json:"items"`
	Took       int64      `json:"took"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r BulkResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r BulkResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// BulkItemFailures detects partial failures on a Bulk response by
// scanning every per-item op for a non-nil Error. Returns nil when no
// items failed.
func (r *BulkResp) BulkItemFailures() *PartialBulkError {
	if r == nil || !r.Errors {
		return nil
	}
	var failed []BulkResponseItem
	succeeded := 0
	for _, item := range r.Items {
		for _, v := range []*BulkResponseItem{item.Create, item.Delete, item.Index, item.Update} {
			if v == nil {
				continue
			}
			if v.Error != nil {
				failed = append(failed, *v)
			} else {
				succeeded++
			}
		}
	}
	if len(failed) == 0 {
		return nil
	}
	return &PartialBulkError{
		FailedItems:    failed,
		SucceededCount: succeeded,
	}
}

// PartialFailures returns the partial-failure sub-errors detected on the
// BulkResp, gated by mask. Mask bits suppress their corresponding
// wrapper category.
func (r *BulkResp) PartialFailures(mask errmask.ErrorMask) []error {
	var errs []error
	if !mask.Has(errmask.BulkItems) {
		if e := r.BulkItemFailures(); e != nil {
			errs = append(errs, e)
		}
	}
	return errs
}

// Bulk allows to perform multiple index/update/delete operations in a single request.
//
// Path: /_bulk
//
// Methods: POST, PUT
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/document-apis/bulk/
func (c Client) Bulk(ctx context.Context, req BulkReq) (*BulkResp, error) {
	var (
		data BulkResp
		err  error
	)
	if data.response, err = do(
		ctx,
		&c,
		http.MethodPost,
		req, &data,
	); err != nil {
		return &data, err
	}
	return &data, collapsePerOpErrors(data.PartialFailures(c.errors), nil)
}
