// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build integration

package osapi_test

import (
	"context"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v4/osapi"
	osapitest "github.com/opensearch-project/opensearch-go/v4/osapi/internal/test"
	"github.com/opensearch-project/opensearch-go/v4/osapi/testutil"
)

func TestDeleteScript(t *testing.T) {
	client, err := testutil.NewClient(t)
	require.NoError(t, err)

	index := testutil.MustUniqueString(t, "test-delete-script")
	docID := testutil.MustUniqueString(t, "test-delete-script")
	t.Cleanup(func() {
		_, _ = client.Indices.Delete(context.Background(), &osapi.IndicesDeleteReq{Index: []string{index}})
	})

	_, err = client.PutScript(t.Context(), osapi.PutScriptReq{
		ID:         docID,
		BodyReader: strings.NewReader(`{"script":{"lang":"painless","source":"doc['title'].value"}}`),
	})
	require.NoError(t, err)
	t.Cleanup(func() {
		_, _ = client.DeleteScript(context.Background(), osapi.DeleteScriptReq{ID: docID})
	})

	t.Run("success", func(t *testing.T) {
		resp, err := client.DeleteScript(t.Context(), osapi.DeleteScriptReq{ID: docID})
		require.NoError(t, err)
		require.NotNil(t, resp)
		testutil.CompareRawJSONwithParsedJSON(t, resp, resp.Inspect().Response)
	})

	t.Run("inspect", func(t *testing.T) {
		failingClient, err := osapitest.CreateFailingClient(t)
		require.NoError(t, err)

		res, err := failingClient.DeleteScript(t.Context(), osapi.DeleteScriptReq{ID: docID})
		require.Error(t, err)
		require.NotNil(t, res)
		osapitest.VerifyInspect(t, res.Inspect())
	})
}
