// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"bytes"
	"context"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// IndicesDataStreamsStatsReq represents the request for the indices.data_streams_stats operation.
//
// Provides statistics on operations happening in a data stream.
//
// GET /_data_stream/_stats
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/im-plugin/data-streams/
type IndicesDataStreamsStatsReq struct {
	// Name specifies the list of path segments for the request URL.
	Name []string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *IndicesDataStreamsStatsParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r IndicesDataStreamsStatsReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.IndicesDataStreamsStatsPath{
		Name: r.Name,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// IndicesDataStreamsStatsParams represents query parameters for the IndicesDataStreamsStatsReq.
type IndicesDataStreamsStatsParams struct {
	TimeoutParams
	DebugParams
}

func (r IndicesDataStreamsStatsParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// IndicesDataStreamsStatsResp represents the response for the indices.data_streams_stats operation.
//
// Provides statistics on operations happening in a data stream.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/im-plugin/data-streams/
type IndicesDataStreamsStatsResp struct {
	Shards ShardStatistics `json:"_shards"`

	// Total number of backing indexes for the selected data streams.
	BackingIndices int `json:"backing_indices"`

	// Total number of selected data streams.
	DataStreamCount int `json:"data_stream_count"`

	// Contains statistics for the selected data streams.
	DataStreams []IndicesDataStreamStats `json:"data_streams"`

	// The unique identifier of a node.
	TotalStoreSize *string `json:"total_store_size,omitempty"`

	// Total size, in bytes, of all shards for the selected data streams.
	TotalStoreSizeBytes int64 `json:"total_store_size_bytes"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r IndicesDataStreamsStatsResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r IndicesDataStreamsStatsResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// DataStreamsStats provides statistics on operations happening in a data stream.
//
// GET /_data_stream/_stats
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/im-plugin/data-streams/
func (c indicesClient) DataStreamsStats(ctx context.Context, req *IndicesDataStreamsStatsReq) (*IndicesDataStreamsStatsResp, error) {
	if req == nil {
		req = &IndicesDataStreamsStatsReq{}
	}

	var (
		data IndicesDataStreamsStatsResp
		err  error
	)
	if data.response, err = do(
		ctx,
		c.apiClient,
		http.MethodGet,
		req, &data,
	); err != nil {
		return &data, err
	}

	return &data, nil
}
