// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package opensearchapi

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// IndicesPutTemplateReq represents the request for the indices.put_template operation.
//
// Creates or updates an index template.
//
// Path: /_template/{name}
//
// Methods: POST, PUT
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/im-plugin/index-templates/
type IndicesPutTemplateReq struct {
	// Name specifies the path segment for the request URL.
	Name string

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *IndicesPutTemplateBody

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *IndicesPutTemplateParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r IndicesPutTemplateReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.IndicesPutTemplatePath{
		Name: r.Name,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		bodyData, err := json.Marshal(r.Body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// IndicesPutTemplateParams represents query parameters for the IndicesPutTemplateReq.
type IndicesPutTemplateParams struct {
	TimeoutParams
	DebugParams
	// If `true`, this request cannot replace or update existing index
	// templates.
	//
	// Default: false.
	Create *bool

	// Order in which OpenSearch applies this template if index matches
	// multiple templates. Templates with lower 'order' values are merged
	// first. Templates with higher 'order' values are merged later, overriding
	// templates with lower values.
	Order int
}

func (r IndicesPutTemplateParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	if r.Create != nil {
		set("create", strconv.FormatBool(*r.Create))
	}

	if r.Order != 0 {
		set("order", strconv.Itoa(r.Order))
	}

	return params
}

// IndicesPutTemplateResp represents the response for the indices.put_template operation.
//
// Creates or updates an index template.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/im-plugin/index-templates/
type IndicesPutTemplateResp struct {
	// For a successful response, this value is always true. On failure, an
	// exception is returned instead.
	Acknowledged bool `json:"acknowledged"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r IndicesPutTemplateResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r IndicesPutTemplateResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// IndicesPutTemplateBody is a typed component of the indices.put_template operation.
//
// The template definition
type IndicesPutTemplateBody struct {
	// Aliases for the index.
	Aliases map[string]IndicesAlias `json:"aliases,omitempty"`

	// Array of wildcard expressions used to match the names of indexes during
	// creation.
	IndexPatterns *IndicesPutTemplateBodyIndexPatterns `json:"index_patterns,omitempty"`

	Mappings *CommonMappingType `json:"mappings,omitempty"`

	// Order in which OpenSearch applies this template if index matches
	// multiple templates. Templates with lower 'order' values are merged
	// first. Templates with higher 'order' values are merged later, overriding
	// templates with lower values.
	Order *int `json:"order,omitempty"`

	// Configuration options for the index.
	Settings map[string]json.RawMessage `json:"settings,omitempty"`

	Version *int64 `json:"version,omitempty"`
}

// IndicesPutTemplateBodyIndexPatterns is a typed component of the indices.put_template operation.
//
// Array of wildcard expressions used to match the names
// of indexes during creation.
type IndicesPutTemplateBodyIndexPatterns struct {
}

// PutTemplate creates or updates an index template.
//
// Path: /_template/{name}
//
// Methods: POST, PUT
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/im-plugin/index-templates/
func (c indicesClient) PutTemplate(ctx context.Context, req IndicesPutTemplateReq) (*IndicesPutTemplateResp, error) {
	var (
		data IndicesPutTemplateResp
		err  error
	)
	if data.response, err = do(
		ctx,
		c.apiClient,
		http.MethodPost,
		req, &data,
	); err != nil {
		return &data, err
	}
	return &data, nil
}
