// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
	"time"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// IndicesShrinkReq represents the request for the indices.shrink operation.
//
// Allow to shrink an existing index into a new index with fewer primary shards.
//
// Path: /{index}/_shrink/{target}
//
// Methods: POST, PUT
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/index-apis/shrink-index/
type IndicesShrinkReq struct {
	// Index specifies the path segment for the request URL.
	Index string

	// Target specifies the path segment for the request URL.
	Target string

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *IndicesShrinkBody

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *IndicesShrinkParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r IndicesShrinkReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.IndicesShrinkPath{
		Index:  r.Index,
		Target: r.Target,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		bodyData, err := json.Marshal(r.Body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// IndicesShrinkParams represents query parameters for the IndicesShrinkReq.
type IndicesShrinkParams struct {
	TimeoutParams
	DebugParams
	// whether or not to copy settings from the source index.
	//
	// Default: false.
	CopySettings *bool

	// Explicit task execution timeout, only useful when `wait_for_completion`
	// is false, defaults to `1h`.
	TaskExecutionTimeout time.Duration

	// The number of shard copies that must be active before proceeding with
	// the operation. Set to `all` or any positive integer up to the total
	// number of shards in the index (`number_of_replicas+1`).
	WaitForActiveShards string

	// Should this request wait until the operation has completed before
	// returning.
	//
	// Available: >= 2.7.0.
	//
	// Default: true.
	WaitForCompletion *bool
}

func (r IndicesShrinkParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	if r.CopySettings != nil {
		set("copy_settings", strconv.FormatBool(*r.CopySettings))
	}

	if r.TaskExecutionTimeout != 0 {
		set("task_execution_timeout", formatDuration(r.TaskExecutionTimeout))
	}

	if r.WaitForActiveShards != "" {
		set("wait_for_active_shards", r.WaitForActiveShards)
	}

	if r.WaitForCompletion != nil {
		set("wait_for_completion", strconv.FormatBool(*r.WaitForCompletion))
	}

	return params
}

// IndicesShrinkResp represents the response for the indices.shrink operation.
//
// Allow to shrink an existing index into a new index with fewer primary shards.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/index-apis/shrink-index/
type IndicesShrinkResp struct {
	AcknowledgedResponseBase
	Index              string `json:"index"`
	ShardsAcknowledged bool   `json:"shards_acknowledged"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r IndicesShrinkResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r IndicesShrinkResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// IndicesShrinkBody is a typed component of the indices.shrink operation.
//
// The configuration for the target index (`settings` and `aliases`)
type IndicesShrinkBody struct {
	// The key is the alias name. Index alias names support date math.
	Aliases map[string]IndicesAlias `json:"aliases,omitempty"`

	// Configuration options for the target index.
	Settings map[string]json.RawMessage `json:"settings,omitempty"`
}

// Shrink allow to shrink an existing index into a new index with fewer primary shards.
//
// Path: /{index}/_shrink/{target}
//
// Methods: POST, PUT
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/index-apis/shrink-index/
func (c indicesClient) Shrink(ctx context.Context, req IndicesShrinkReq) (*IndicesShrinkResp, error) {
	var (
		data IndicesShrinkResp
		err  error
	)
	if data.response, err = do(
		ctx,
		c.apiClient,
		http.MethodPost,
		req, &data,
	); err != nil {
		return &data, err
	}

	return &data, nil
}
