// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package osapi

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestIndicesGetParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params IndicesGetParams
		want   map[string]string
	}{
		{name: "empty", params: IndicesGetParams{}, want: nil},
		{
			name:   "allow_no_indices=true",
			params: IndicesGetParams{AllowNoIndices: func(b bool) *bool { return &b }(true)},
			want:   map[string]string{"allow_no_indices": "true"},
		},
		{
			name:   "allow_no_indices=false",
			params: IndicesGetParams{AllowNoIndices: func(b bool) *bool { return &b }(false)},
			want:   map[string]string{"allow_no_indices": "false"},
		},
		{
			name:   "expand_wildcards",
			params: IndicesGetParams{ExpandWildcards: []string{"a", "b"}},
			want:   map[string]string{"expand_wildcards": "a,b"},
		},
		{
			name:   "flat_settings=true",
			params: IndicesGetParams{FlatSettings: func(b bool) *bool { return &b }(true)},
			want:   map[string]string{"flat_settings": "true"},
		},
		{
			name:   "flat_settings=false",
			params: IndicesGetParams{FlatSettings: func(b bool) *bool { return &b }(false)},
			want:   map[string]string{"flat_settings": "false"},
		},
		{
			name:   "ignore_unavailable=true",
			params: IndicesGetParams{IgnoreUnavailable: func(b bool) *bool { return &b }(true)},
			want:   map[string]string{"ignore_unavailable": "true"},
		},
		{
			name:   "ignore_unavailable=false",
			params: IndicesGetParams{IgnoreUnavailable: func(b bool) *bool { return &b }(false)},
			want:   map[string]string{"ignore_unavailable": "false"},
		},
		{
			name:   "include_defaults=true",
			params: IndicesGetParams{IncludeDefaults: func(b bool) *bool { return &b }(true)},
			want:   map[string]string{"include_defaults": "true"},
		},
		{
			name:   "include_defaults=false",
			params: IndicesGetParams{IncludeDefaults: func(b bool) *bool { return &b }(false)},
			want:   map[string]string{"include_defaults": "false"},
		},
		{
			name:   "local=true",
			params: IndicesGetParams{Local: func(b bool) *bool { return &b }(true)},
			want:   map[string]string{"local": "true"},
		},
		{
			name:   "local=false",
			params: IndicesGetParams{Local: func(b bool) *bool { return &b }(false)},
			want:   map[string]string{"local": "false"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
