// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package opensearchapi

import (
	"bytes"
	"context"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// InfoReq represents the request for the info operation.
//
// Returns basic information about the cluster.
//
// GET /
//
// Available: >= 1.0.0.
//
// Not available on: amazon-serverless.
//
// See: https://opensearch.org/docs/latest
type InfoReq struct {

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *InfoParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r InfoReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.InfoPath{}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// InfoParams represents query parameters for the InfoReq.
type InfoParams struct {
	TimeoutParams
	DebugParams
}

func (r InfoParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// InfoResp represents the response for the info operation.
//
// Returns basic information about the cluster.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest
type InfoResp struct {
	// The name of a resource or configuration element.
	ClusterName string `json:"cluster_name"`

	// The universally unique identifier.
	ClusterUUID string `json:"cluster_uuid"`

	// The name of a resource or configuration element.
	Name string `json:"name"`

	Tagline string `json:"tagline"`

	// The version information for OpenSearch.
	Version OpenSearchVersionInfo `json:"version"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r InfoResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r InfoResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// Info returns basic information about the cluster.
//
// GET /
//
// Available: >= 1.0.0.
//
// Not available on: amazon-serverless.
//
// See: https://opensearch.org/docs/latest
func (c Client) Info(ctx context.Context, req *InfoReq) (*InfoResp, error) {
	if req == nil {
		req = &InfoReq{}
	}

	var (
		data InfoResp
		err  error
	)
	if data.response, err = do(
		ctx,
		&c,
		http.MethodGet,
		req, &data,
	); err != nil {
		return &data, err
	}

	return &data, nil
}
