// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package opensearchapi

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestReindexParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params ReindexParams
		want   map[string]string
	}{
		{name: "empty", params: ReindexParams{}, want: nil},
		{
			name:   "max_docs",
			params: ReindexParams{MaxDocs: 42},
			want:   map[string]string{"max_docs": "42"},
		},
		{
			name:   "refresh",
			params: ReindexParams{Refresh: "test-value"},
			want:   map[string]string{"refresh": "test-value"},
		},
		{
			name:   "requests_per_second",
			params: ReindexParams{RequestsPerSecond: 42},
			want:   map[string]string{"requests_per_second": "42"},
		},
		{
			name:   "require_alias=true",
			params: ReindexParams{RequireAlias: func(b bool) *bool { return &b }(true)},
			want:   map[string]string{"require_alias": "true"},
		},
		{
			name:   "require_alias=false",
			params: ReindexParams{RequireAlias: func(b bool) *bool { return &b }(false)},
			want:   map[string]string{"require_alias": "false"},
		},
		{
			name:   "scroll",
			params: ReindexParams{Scroll: 5 * time.Second},
			want:   map[string]string{"scroll": "5000ms"},
		},
		{
			name:   "slices",
			params: ReindexParams{Slices: "test-value"},
			want:   map[string]string{"slices": "test-value"},
		},
		{
			name:   "wait_for_active_shards",
			params: ReindexParams{WaitForActiveShards: "test-value"},
			want:   map[string]string{"wait_for_active_shards": "test-value"},
		},
		{
			name:   "wait_for_completion=true",
			params: ReindexParams{WaitForCompletion: func(b bool) *bool { return &b }(true)},
			want:   map[string]string{"wait_for_completion": "true"},
		},
		{
			name:   "wait_for_completion=false",
			params: ReindexParams{WaitForCompletion: func(b bool) *bool { return &b }(false)},
			want:   map[string]string{"wait_for_completion": "false"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
