// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"strconv"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// SnapshotStatusReq represents the request for the snapshot.status operation.
//
// Returns information about the status of a snapshot.
//
// GET /_snapshot/_status
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/snapshots/get-snapshot-status/
type SnapshotStatusReq struct {
	// Repository specifies the path segment for the request URL.
	Repository string

	// Snapshot specifies the list of path segments for the request URL.
	Snapshot []string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *SnapshotStatusParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r SnapshotStatusReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.SnapshotStatusPath{
		Repository: r.Repository,
		Snapshot:   r.Snapshot,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// SnapshotStatusParams represents query parameters for the SnapshotStatusReq.
type SnapshotStatusParams struct {
	TimeoutParams
	DebugParams
	// Whether to ignore any unavailable snapshots, When `false`, a
	// `SnapshotMissingException` is thrown.
	//
	// Default: false.
	IgnoreUnavailable *bool
}

func (r SnapshotStatusParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	if r.IgnoreUnavailable != nil {
		set("ignore_unavailable", strconv.FormatBool(*r.IgnoreUnavailable))
	}

	return params
}

// SnapshotStatusResp represents the response for the snapshot.status operation.
//
// Returns information about the status of a snapshot.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/snapshots/get-snapshot-status/
type SnapshotStatusResp struct {
	Snapshots []SnapshotStatus `json:"snapshots"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r SnapshotStatusResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r SnapshotStatusResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// Status returns information about the status of a snapshot.
//
// GET /_snapshot/_status
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/snapshots/get-snapshot-status/
func (c snapshotClient) Status(ctx context.Context, req SnapshotStatusReq) (*SnapshotStatusResp, error) {
	var (
		data SnapshotStatusResp
		err  error
	)
	if data.response, err = do(
		ctx,
		c.apiClient,
		http.MethodGet,
		req, &data,
	); err != nil {
		return &data, err
	}

	return &data, nil
}
