// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package opensearchapi

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strconv"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// SnapshotRestoreReq represents the request for the snapshot.restore operation.
//
// Restores a snapshot.
//
// POST /_snapshot/{repository}/{snapshot}/_restore
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/snapshots/restore-snapshot/
type SnapshotRestoreReq struct {
	// Repository specifies the path segment for the request URL.
	Repository string

	// Snapshot specifies the path segment for the request URL.
	Snapshot string

	// Body specifies the typed request body. When non-nil, it is
	// marshaled to JSON for the request payload.
	Body *SnapshotRestoreBody

	// BodyReader provides an escape hatch for sending a raw request
	// body. It is used only when Body is nil.
	BodyReader io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *SnapshotRestoreParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r SnapshotRestoreReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.SnapshotRestorePath{
		Repository: r.Repository,
		Snapshot:   r.Snapshot,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	var bodyReader io.Reader
	if r.Body != nil {
		bodyData, err := json.Marshal(r.Body)
		if err != nil {
			return nil, err
		}
		bodyReader = bytes.NewReader(bodyData)
	} else if r.BodyReader != nil {
		bodyReader = r.BodyReader
	}

	return build.Request(
		method,
		path,
		bodyReader,
		params,
		r.Header,
	)
}

// SnapshotRestoreParams represents query parameters for the SnapshotRestoreReq.
type SnapshotRestoreParams struct {
	TimeoutParams
	DebugParams
	// -| Whether to return a response after the restore operation has
	// completed. When `false`, the request returns a response when the restore
	// operation initializes. When `true`, the request returns a response when
	// the restore operation completes.
	//
	// Default: false.
	WaitForCompletion *bool
}

func (r SnapshotRestoreParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	if r.WaitForCompletion != nil {
		set("wait_for_completion", strconv.FormatBool(*r.WaitForCompletion))
	}

	return params
}

// SnapshotRestoreResp represents the response for the snapshot.restore operation.
//
// Restores a snapshot.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/snapshots/restore-snapshot/
type SnapshotRestoreResp struct {
	// Returns `true` if the restore was accepted. Present when the request had
	// `wait_for_completion` set to `false`.
	Accepted *bool `json:"accepted,omitempty"`

	Snapshot *SnapshotRestoreSnapshot `json:"snapshot,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r SnapshotRestoreResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r SnapshotRestoreResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}

// SnapshotRestoreSnapshot is a typed component of the snapshot.restore operation.
type SnapshotRestoreSnapshot struct {
	// The list of indexes that were restored.
	Indices []string `json:"indices"`

	// Any statistics about the restored shards.
	Shards ShardStatistics `json:"shards"`

	// The name of the snapshot that was restored.
	Snapshot string `json:"snapshot"`
}

// SnapshotRestoreBody is a typed component of the snapshot.restore operation.
//
// Determines which settings and indexes to restore when restoring a snapshot
type SnapshotRestoreBody struct {
	// A comma-delimited list of index settings to ignore when restoring
	// indexes from a snapshot.
	IgnoreIndexSettings []string `json:"ignore_index_settings,omitempty"`

	// How to handle data streams or indexes that are missing or closed. When
	// `false`, the request returns an error for any data stream or index that
	// is missing or closed. When `true`, the request ignores data streams and
	// indexes in indexes that are missing or closed.
	IgnoreUnavailable *bool `json:"ignore_unavailable,omitempty"`

	// How to handle index aliases from the original snapshot. When `true`,
	// index aliases from the original snapshot are restored. When `false`,
	// aliases along with associated indexes are not restored.
	IncludeAliases *bool `json:"include_aliases,omitempty"`

	// Whether to restore the current cluster state. When `false`, the cluster
	// state is not restored. When `true`, the current cluster state is
	// restored.
	IncludeGlobalState *bool `json:"include_global_state,omitempty"`

	// A comma-delimited list of settings to add or change in all restored
	// indexes. Use this parameter to override index settings during snapshot
	// restoration. For data streams, these index settings are applied to the
	// restored backing indexes.
	IndexSettings *IndicesIndexSettings `json:"index_settings,omitempty"`

	// A comma-separated list of data streams, indexes, and aliases used to
	// limit the request. Supports wildcards (`*`). To target all data streams
	// and indexes, omit this parameter or use `*` or `_all`.
	Indices []string `json:"indices,omitempty"`

	// How the restore operation will behave if indexes in the snapshot do not
	// have all primary shards available. When `false`, the entire restore
	// operation fails if any indexes in the snapshot do not have all primary
	// shards available. When `true`, allows the restoration of a partial
	// snapshot of indexes with unavailable shards. Only shards that were
	// successfully included in the snapshot are restored. All missing shards
	// are recreated as empty. By default, the entire restore operation fails
	// if one or more indexes included in the snapshot do not have all primary
	// shards available. To change this behavior, set `partial` to `true`.
	Partial *bool `json:"partial,omitempty"`

	// The pattern to apply to the restored aliases. Aliases matching the
	// rename pattern will be renamed according to the
	// `rename_alias_replacement` setting. The rename pattern is applied as
	// defined by the regular expression that supports referencing the original
	// text. If two or more aliases are renamed into the same name, these
	// aliases will be merged into one.
	//
	// Available: >= 2.18.0.
	RenameAliasPattern *string `json:"rename_alias_pattern,omitempty"`

	// The rename replacement string for aliases.
	//
	// Available: >= 2.18.0.
	RenameAliasReplacement *string `json:"rename_alias_replacement,omitempty"`

	// The pattern to apply to the restored data streams and indexes. Data
	// streams and indexes matching the rename pattern will be renamed
	// according to the `rename_replacement` setting. The rename pattern is
	// applied as defined by the regular expression that supports referencing
	// the original text. The request fails if two or more data streams or
	// indexes are renamed into the same name. If you rename a restored data
	// stream, its backing indexes are also renamed. For example, if you rename
	// the logs data stream to `recovered-logs`, the backing index `.ds-logs-1`
	// is renamed to `.ds-recovered-logs-1`. If you rename a restored stream,
	// ensure an index template matches the new stream name. If there are no
	// matching index template names, the stream cannot roll over and new
	// backing indexes are not created.
	RenamePattern *string `json:"rename_pattern,omitempty"`

	// The rename replacement string.
	RenameReplacement *string `json:"rename_replacement,omitempty"`

	// The name of the remote store repository of the source index being
	// restored. If not provided, the Snapshot Restore API will use the
	// repository that was registered when the snapshot was created.
	//
	// Available: >= 2.10.0.
	SourceRemoteStoreRepository *string `json:"source_remote_store_repository,omitempty"`

	// Where will be the authoritative store of the restored indexes' data. A
	// value of `local` indicates that all snapshot metadata and index data
	// will be downloaded to local storage. A value of `remote_snapshot`
	// indicates that snapshot metadata will be downloaded to the cluster, but
	// the remote repository will remain the authoritative store of the index
	// data. Data will be downloaded and cached as necessary to service
	// queries. At least one node in the cluster must be configured with the
	// search role in order to restore a snapshot using the type
	// `remote_snapshot`.
	//
	// Available: >= 2.7.0.
	StorageType *string `json:"storage_type,omitempty"`
}

// Restore restores a snapshot.
//
// POST /_snapshot/{repository}/{snapshot}/_restore
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/snapshots/restore-snapshot/
func (c snapshotClient) Restore(ctx context.Context, req SnapshotRestoreReq) (*SnapshotRestoreResp, error) {
	var (
		data SnapshotRestoreResp
		err  error
	)
	if data.response, err = do(
		ctx,
		c.apiClient,
		http.MethodPost,
		req, &data,
	); err != nil {
		return &data, err
	}
	return &data, nil
}
