// Code generated by cmd/osgen; DO NOT EDIT.

//go:build integration

package asynchronous_search_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	osapitest "github.com/opensearch-project/opensearch-go/v4/osapi/internal/test"
	"github.com/opensearch-project/opensearch-go/v4/osapi/plugins/asynchronous_search"
	plugintest "github.com/opensearch-project/opensearch-go/v4/osapi/plugins/asynchronous_search/internal/test"
	"github.com/opensearch-project/opensearch-go/v4/osapi/testutil"
)

func TestSearch(t *testing.T) {
	client, err := plugintest.NewClient(t)
	require.NoError(t, err)

	t.Run("success", func(t *testing.T) {
		resp, err := client.Search(t.Context(), &asynchronous_search.SearchReq{Body: strings.NewReader("{}")})
		require.NoError(t, err)
		require.NotNil(t, resp)
		testutil.CompareRawJSONwithParsedJSON(t, resp, resp.Inspect().Response)
	})

	t.Run("inspect", func(t *testing.T) {
		failingClient, err := plugintest.CreateFailingClient(t)
		require.NoError(t, err)

		res, err := failingClient.Search(t.Context(), &asynchronous_search.SearchReq{Body: strings.NewReader("{}")})
		require.Error(t, err)
		require.NotNil(t, res)
		osapitest.VerifyInspect(t, res.Inspect())
	})
}
