// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build integration

package transforms_test

import (
	"context"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v4/osapi"
	"github.com/opensearch-project/opensearch-go/v4/osapi/plugins/transforms"
	plugintest "github.com/opensearch-project/opensearch-go/v4/osapi/plugins/transforms/internal/test"
	"github.com/opensearch-project/opensearch-go/v4/osapi/testutil"
)

func TestGet(t *testing.T) {
	t.Skip("requires transform job configuration") //nolint:gocritic // FIXME: implement proper test fixture
	client, err := plugintest.NewClient(t)
	require.NoError(t, err)

	osClient, err := testutil.NewClient(t)
	require.NoError(t, err)

	index := testutil.MustUniqueString(t, "test-get")
	docID := testutil.MustUniqueString(t, "test-get")
	t.Cleanup(func() {
		_, _ = osClient.Indices.Delete(context.Background(), &osapi.IndicesDeleteReq{Index: []string{index}})
	})

	_, err = osClient.Indices.Create(t.Context(), osapi.IndicesCreateReq{Index: index})
	require.NoError(t, err)

	_, err = osClient.Index(t.Context(), osapi.IndexReq{
		Index:  index,
		ID:     docID,
		Body:   strings.NewReader(`{"title":"fixture"}`),
		Params: &osapi.IndexParams{Refresh: "true"},
	})
	require.NoError(t, err)

	t.Run("success", func(t *testing.T) {
		resp, err := client.Get(t.Context(), transforms.GetReq{ID: docID})
		require.NoError(t, err)
		require.NotNil(t, resp)
		testutil.CompareRawJSONwithParsedJSON(t, resp, resp.Inspect().Response)
	})

	t.Run("inspect", func(t *testing.T) {
		failingClient, err := plugintest.CreateFailingClient(t)
		require.NoError(t, err)

		res, err := failingClient.Get(t.Context(), transforms.GetReq{ID: docID})
		require.Error(t, err)
		require.NotNil(t, res)
		plugintest.VerifyInspect(t, res.Inspect())
	})
}
