// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build integration

package transforms_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi"
	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi/plugins/transforms"
	plugintest "github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi/plugins/transforms/internal/transformstest"
	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi/testutil"
)

func TestPreview(t *testing.T) {
	t.Skip("requires transform job configuration") //nolint:gocritic // FIXME: implement proper test fixture
	client, err := plugintest.NewClient(t)
	require.NoError(t, err)

	t.Run("success", func(t *testing.T) {
		resp, err := client.Preview(t.Context(), &transforms.PreviewReq{Body: &opensearchapi.TransformsTransformRequest{}})
		require.NoError(t, err)
		require.NotNil(t, resp)
		testutil.CompareRawJSONwithParsedJSON(t, resp, resp.Inspect().Response)
	})

	t.Run("inspect", func(t *testing.T) {
		failingClient, err := plugintest.CreateFailingClient(t)
		require.NoError(t, err)

		res, err := failingClient.Preview(t.Context(), &transforms.PreviewReq{Body: &opensearchapi.TransformsTransformRequest{}})
		require.Error(t, err)
		require.NotNil(t, res)
		plugintest.VerifyInspect(t, res.Inspect())
	})
}
