// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package osapi

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestCatHealthParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params CatHealthParams
		want   map[string]string
	}{
		{name: "empty", params: CatHealthParams{}, want: map[string]string{}},
		{
			name:   "format",
			params: CatHealthParams{Format: "test-value"},
			want:   map[string]string{"format": "test-value"},
		},
		{
			name:   "h",
			params: CatHealthParams{H: []string{"a", "b"}},
			want:   map[string]string{"h": "a,b"},
		},
		{
			name:   "help",
			params: CatHealthParams{Help: true},
			want:   map[string]string{"help": "true"},
		},
		{
			name:   "s",
			params: CatHealthParams{S: []string{"a", "b"}},
			want:   map[string]string{"s": "a,b"},
		},
		{
			name:   "time",
			params: CatHealthParams{Time: "test-value"},
			want:   map[string]string{"time": "test-value"},
		},
		{
			name:   "ts",
			params: CatHealthParams{Ts: true},
			want:   map[string]string{"ts": "true"},
		},
		{
			name:   "v",
			params: CatHealthParams{V: true},
			want:   map[string]string{"v": "true"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
