// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package osapi

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestCatIndicesParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params CatIndicesParams
		want   map[string]string
	}{
		{name: "empty", params: CatIndicesParams{}, want: map[string]string{}},
		{
			name:   "bytes",
			params: CatIndicesParams{Bytes: "test-value"},
			want:   map[string]string{"bytes": "test-value"},
		},
		{
			name:   "cluster_manager_timeout",
			params: CatIndicesParams{ClusterManagerTimeout: 5 * time.Second},
			want:   map[string]string{"cluster_manager_timeout": "5000ms"},
		},
		{
			name:   "expand_wildcards",
			params: CatIndicesParams{ExpandWildcards: []string{"a", "b"}},
			want:   map[string]string{"expand_wildcards": "a,b"},
		},
		{
			name:   "format",
			params: CatIndicesParams{Format: "test-value"},
			want:   map[string]string{"format": "test-value"},
		},
		{
			name:   "h",
			params: CatIndicesParams{H: []string{"a", "b"}},
			want:   map[string]string{"h": "a,b"},
		},
		{
			name:   "health",
			params: CatIndicesParams{Health: "test-value"},
			want:   map[string]string{"health": "test-value"},
		},
		{
			name:   "help",
			params: CatIndicesParams{Help: true},
			want:   map[string]string{"help": "true"},
		},
		{
			name:   "include_unloaded_segments",
			params: CatIndicesParams{IncludeUnloadedSegments: true},
			want:   map[string]string{"include_unloaded_segments": "true"},
		},
		{
			name:   "local",
			params: CatIndicesParams{Local: true},
			want:   map[string]string{"local": "true"},
		},
		{
			name:   "master_timeout",
			params: CatIndicesParams{MasterTimeout: 5 * time.Second},
			want:   map[string]string{"master_timeout": "5000ms"},
		},
		{
			name:   "pri",
			params: CatIndicesParams{Pri: true},
			want:   map[string]string{"pri": "true"},
		},
		{
			name:   "s",
			params: CatIndicesParams{S: []string{"a", "b"}},
			want:   map[string]string{"s": "a,b"},
		},
		{
			name:   "time",
			params: CatIndicesParams{Time: "test-value"},
			want:   map[string]string{"time": "test-value"},
		},
		{
			name:   "v",
			params: CatIndicesParams{V: true},
			want:   map[string]string{"v": "true"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
