// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package osapi

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestCatAllocationParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params CatAllocationParams
		want   map[string]string
	}{
		{name: "empty", params: CatAllocationParams{}, want: map[string]string{"format": "json"}},
		{
			name:   "bytes",
			params: CatAllocationParams{Bytes: "test-value"},
			want:   map[string]string{"format": "json", "bytes": "test-value"},
		},
		{
			name:   "local=true",
			params: CatAllocationParams{Local: func(b bool) *bool { return &b }(true)},
			want:   map[string]string{"format": "json", "local": "true"},
		},
		{
			name:   "local=false",
			params: CatAllocationParams{Local: func(b bool) *bool { return &b }(false)},
			want:   map[string]string{"format": "json", "local": "false"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
