// Code generated by cmd/osgen; DO NOT EDIT.

//go:build integration

package osapi_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v4/osapi"
	osapitest "github.com/opensearch-project/opensearch-go/v4/osapi/internal/test"
	"github.com/opensearch-project/opensearch-go/v4/osapi/testutil"
)

func TestDanglingIndicesDeleteDanglingIndex(t *testing.T) {
	client, err := testutil.NewClient(t)
	require.NoError(t, err)

	t.Skip("requires dangling index state from node failure")

	t.Run("success", func(t *testing.T) {
		resp, err := client.Dangling.DeleteDanglingIndex(t.Context(), osapi.DanglingIndicesDeleteDanglingIndexReq{IndexUUID: "test-value"})
		require.NoError(t, err)
		require.NotNil(t, resp)
		testutil.CompareRawJSONwithParsedJSON(t, resp, resp.Inspect().Response)
	})

	t.Run("inspect", func(t *testing.T) {
		failingClient, err := osapitest.CreateFailingClient(t)
		require.NoError(t, err)

		res, err := failingClient.Dangling.DeleteDanglingIndex(t.Context(), osapi.DanglingIndicesDeleteDanglingIndexReq{IndexUUID: "test-value"})
		require.Error(t, err)
		require.NotNil(t, res)
		osapitest.VerifyInspect(t, res.Inspect())
	})
}
