// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"context"
	"net/http"
	"strconv"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// DeleteByQueryRethrottleReq represents the request for the delete_by_query_rethrottle operation.
//
// Changes the number of requests per second for a particular Delete By Query operation.
//
// POST /_delete_by_query/{task_id}/_rethrottle
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest
type DeleteByQueryRethrottleReq struct {
	// TaskID specifies the path segment for the request URL.
	TaskID string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params DeleteByQueryRethrottleParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r DeleteByQueryRethrottleReq) GetRequest() (*http.Request, error) {
	path, err := ospath.DeleteByQueryRethrottlePath{
		TaskID: r.TaskID,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodPost,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// DeleteByQueryRethrottleParams represents query parameters for the DeleteByQueryRethrottleReq.
type DeleteByQueryRethrottleParams struct {
	// The throttle for this request in sub-requests per second.
	RequestsPerSecond int

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r DeleteByQueryRethrottleParams) get() map[string]string {
	params := make(map[string]string, 1)

	if r.RequestsPerSecond != 0 {
		params["requests_per_second"] = strconv.Itoa(r.RequestsPerSecond)
	}

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// DeleteByQueryRethrottleResp represents the response for the delete_by_query_rethrottle operation.
//
// Changes the number of requests per second for a particular Delete By Query operation.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest
type DeleteByQueryRethrottleResp struct {
	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r DeleteByQueryRethrottleResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

func (c Client) DeleteByQueryRethrottle(ctx context.Context, req DeleteByQueryRethrottleReq) (*DeleteByQueryRethrottleResp, error) {
	var (
		data DeleteByQueryRethrottleResp
		err  error
	)
	if data.response, err = do(ctx, &c, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}
