// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package osapi

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestExplainParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params ExplainParams
		want   map[string]string
	}{
		{name: "empty", params: ExplainParams{}, want: nil},
		{
			name:   "_source",
			params: ExplainParams{Source: "test-value"},
			want:   map[string]string{"_source": "test-value"},
		},
		{
			name:   "_source_excludes",
			params: ExplainParams{SourceExcludes: []string{"a", "b"}},
			want:   map[string]string{"_source_excludes": "a,b"},
		},
		{
			name:   "_source_includes",
			params: ExplainParams{SourceIncludes: []string{"a", "b"}},
			want:   map[string]string{"_source_includes": "a,b"},
		},
		{
			name:   "analyze_wildcard=true",
			params: ExplainParams{AnalyzeWildcard: func(b bool) *bool { return &b }(true)},
			want:   map[string]string{"analyze_wildcard": "true"},
		},
		{
			name:   "analyze_wildcard=false",
			params: ExplainParams{AnalyzeWildcard: func(b bool) *bool { return &b }(false)},
			want:   map[string]string{"analyze_wildcard": "false"},
		},
		{
			name:   "analyzer",
			params: ExplainParams{Analyzer: "test-value"},
			want:   map[string]string{"analyzer": "test-value"},
		},
		{
			name:   "default_operator",
			params: ExplainParams{DefaultOperator: "test-value"},
			want:   map[string]string{"default_operator": "test-value"},
		},
		{
			name:   "df",
			params: ExplainParams{Df: "test-value"},
			want:   map[string]string{"df": "test-value"},
		},
		{
			name:   "lenient=true",
			params: ExplainParams{Lenient: func(b bool) *bool { return &b }(true)},
			want:   map[string]string{"lenient": "true"},
		},
		{
			name:   "lenient=false",
			params: ExplainParams{Lenient: func(b bool) *bool { return &b }(false)},
			want:   map[string]string{"lenient": "false"},
		},
		{
			name:   "preference",
			params: ExplainParams{Preference: "test-value"},
			want:   map[string]string{"preference": "test-value"},
		},
		{
			name:   "q",
			params: ExplainParams{Q: "test-value"},
			want:   map[string]string{"q": "test-value"},
		},
		{
			name:   "routing",
			params: ExplainParams{Routing: []string{"a", "b"}},
			want:   map[string]string{"routing": "a,b"},
		},
		{
			name:   "stored_fields",
			params: ExplainParams{StoredFields: []string{"a", "b"}},
			want:   map[string]string{"stored_fields": "a,b"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
