// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"context"
	"io"
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// FieldCapsReq represents the request for the field_caps operation.
//
// Returns the information about the capabilities of fields among multiple indexes.
//
// Path: /_field_caps
//
// Methods: GET, POST
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/field-types/supported-field-types/alias/#using-aliases-in-field-capabilities-api-operations
type FieldCapsReq struct {
	// Index specifies the list of path segments for the request URL.
	Index []string

	// Body is the request payload, typically JSON-encoded.
	Body io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params FieldCapsParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r FieldCapsReq) GetRequest() (*http.Request, error) {
	path, err := ospath.FieldCapsPath{
		Index: r.Index,
	}.Build()
	if err != nil {
		return nil, err
	}
	method := http.MethodGet
	if r.Body != nil {
		method = http.MethodPost
	}

	return opensearch.BuildRequest(
		method,
		path,
		r.Body,
		r.Params.get(),
		r.Header,
	)
}

// FieldCapsParams represents query parameters for the FieldCapsReq.
type FieldCapsParams struct {
	// If `false`, the request returns an error if any wildcard expression,
	// index alias, or `_all` value targets only missing or closed indexes.
	// This behavior applies even if the request targets other open indexes.
	// For example, a request targeting `foo*,bar*` returns an error if an
	// index starts with foo but no index starts with bar.
	AllowNoIndices bool

	// Type of index that wildcard patterns can match. If the request can
	// target data streams, this argument determines whether wildcard
	// expressions match hidden data streams. Supports comma-separated values,
	// such as `open,hidden`.
	ExpandWildcards []string

	// Comma-separated list of fields to retrieve capabilities for. Wildcard
	// (`*`) expressions are supported.
	Fields []string

	// If `true`, missing or closed indexes are not included in the response.
	IgnoreUnavailable bool

	// If `true`, unmapped fields are included in the response.
	//
	// Default: false.
	IncludeUnmapped bool

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r FieldCapsParams) get() map[string]string {
	params := make(map[string]string, 5)

	if r.AllowNoIndices {
		params["allow_no_indices"] = "true"
	}

	if len(r.ExpandWildcards) > 0 {
		params["expand_wildcards"] = strings.Join(r.ExpandWildcards, ",")
	}

	if len(r.Fields) > 0 {
		params["fields"] = strings.Join(r.Fields, ",")
	}

	if r.IgnoreUnavailable {
		params["ignore_unavailable"] = "true"
	}

	if r.IncludeUnmapped {
		params["include_unmapped"] = "true"
	}

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// FieldCapsResp represents the response for the field_caps operation.
//
// Returns the information about the capabilities of fields among multiple indexes.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/field-types/supported-field-types/alias/#using-aliases-in-field-capabilities-api-operations
type FieldCapsResp struct {
	Fields map[string]map[string]FieldCapsFieldCapability `json:"fields"`

	// A comma-separated list of data streams, indexes, and aliases used to
	// limit the request. Supports wildcards (`*`). To target all data streams
	// and indexes, omit this parameter or use `*` or `_all`.
	Indices string `json:"indices"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r FieldCapsResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// FieldCapsFieldCapability is a typed component of the field_caps response.
type FieldCapsFieldCapability struct {
	// Whether this field can be aggregated on all indexes.
	Aggregatable bool `json:"aggregatable"`

	// A comma-separated list of data streams, indexes, and aliases used to
	// limit the request. Supports wildcards (`*`). To target all data streams
	// and indexes, omit this parameter or use `*` or `_all`.
	Indices *string `json:"indices,omitempty"`

	Meta map[string][]string `json:"meta,omitempty"`

	// Whether this field is registered as a metadata field.
	MetadataField *bool `json:"metadata_field,omitempty"`

	// A comma-separated list of data streams, indexes, and aliases used to
	// limit the request. Supports wildcards (`*`). To target all data streams
	// and indexes, omit this parameter or use `*` or `_all`.
	NonAggregatableIndices *string `json:"non_aggregatable_indices,omitempty"`

	// A comma-separated list of data streams, indexes, and aliases used to
	// limit the request. Supports wildcards (`*`). To target all data streams
	// and indexes, omit this parameter or use `*` or `_all`.
	NonSearchableIndices *string `json:"non_searchable_indices,omitempty"`

	// Whether this field is indexed for search on all indexes.
	Searchable bool `json:"searchable"`

	Type string `json:"type"`
}

func (c Client) FieldCaps(ctx context.Context, req *FieldCapsReq) (*FieldCapsResp, error) {
	if req == nil {
		req = &FieldCapsReq{}
	}

	var (
		data FieldCapsResp
		err  error
	)
	if data.response, err = do(ctx, &c, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}
