// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package osapi

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestIndicesPutMappingParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params IndicesPutMappingParams
		want   map[string]string
	}{
		{name: "empty", params: IndicesPutMappingParams{}, want: map[string]string{}},
		{
			name:   "allow_no_indices",
			params: IndicesPutMappingParams{AllowNoIndices: true},
			want:   map[string]string{"allow_no_indices": "true"},
		},
		{
			name:   "cluster_manager_timeout",
			params: IndicesPutMappingParams{ClusterManagerTimeout: 5 * time.Second},
			want:   map[string]string{"cluster_manager_timeout": "5000ms"},
		},
		{
			name:   "expand_wildcards",
			params: IndicesPutMappingParams{ExpandWildcards: []string{"a", "b"}},
			want:   map[string]string{"expand_wildcards": "a,b"},
		},
		{
			name:   "ignore_unavailable",
			params: IndicesPutMappingParams{IgnoreUnavailable: true},
			want:   map[string]string{"ignore_unavailable": "true"},
		},
		{
			name:   "master_timeout",
			params: IndicesPutMappingParams{MasterTimeout: 5 * time.Second},
			want:   map[string]string{"master_timeout": "5000ms"},
		},
		{
			name:   "timeout",
			params: IndicesPutMappingParams{Timeout: 5 * time.Second},
			want:   map[string]string{"timeout": "5000ms"},
		},
		{
			name:   "write_index_only",
			params: IndicesPutMappingParams{WriteIndexOnly: true},
			want:   map[string]string{"write_index_only": "true"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
