// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package osapi

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestIndicesGetAliasParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params IndicesGetAliasParams
		want   map[string]string
	}{
		{name: "empty", params: IndicesGetAliasParams{}, want: map[string]string{}},
		{
			name:   "allow_no_indices",
			params: IndicesGetAliasParams{AllowNoIndices: true},
			want:   map[string]string{"allow_no_indices": "true"},
		},
		{
			name:   "expand_wildcards",
			params: IndicesGetAliasParams{ExpandWildcards: []string{"a", "b"}},
			want:   map[string]string{"expand_wildcards": "a,b"},
		},
		{
			name:   "ignore_unavailable",
			params: IndicesGetAliasParams{IgnoreUnavailable: true},
			want:   map[string]string{"ignore_unavailable": "true"},
		},
		{
			name:   "local",
			params: IndicesGetAliasParams{Local: true},
			want:   map[string]string{"local": "true"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
