// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"context"
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// IndicesGetFieldMappingReq represents the request for the indices.get_field_mapping operation.
//
// Returns mapping for one or more fields.
//
// GET /_mapping/field/{fields}
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/field-types/index/
type IndicesGetFieldMappingReq struct {
	// Fields specifies the list of path segments for the request URL.
	Fields []string

	// Index specifies the list of path segments for the request URL.
	Index []string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params IndicesGetFieldMappingParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r IndicesGetFieldMappingReq) GetRequest() (*http.Request, error) {
	path, err := ospath.IndicesGetFieldMappingPath{
		Fields: r.Fields,
		Index:  r.Index,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodGet,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// IndicesGetFieldMappingParams represents query parameters for the IndicesGetFieldMappingReq.
type IndicesGetFieldMappingParams struct {
	// If `false`, the request returns an error if any wildcard expression,
	// index alias, or `_all` value targets only missing or closed indexes.
	// This behavior applies even if the request targets other open indexes.
	AllowNoIndices bool

	// Type of index that wildcard patterns can match. If the request can
	// target data streams, this argument determines whether wildcard
	// expressions match hidden data streams. Supports comma-separated values,
	// such as `open,hidden`. Valid values are: `all`, `open`, `closed`,
	// `hidden`, `none`.
	ExpandWildcards []string

	// If `false`, the request returns an error if it targets a missing or
	// closed index.
	IgnoreUnavailable bool

	// If `true`, return all default settings in the response.
	IncludeDefaults bool

	// If `true`, the request retrieves information from the local node only.
	//
	// Default: false.
	Local bool

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r IndicesGetFieldMappingParams) get() map[string]string {
	params := make(map[string]string, 5)

	if r.AllowNoIndices {
		params["allow_no_indices"] = "true"
	}

	if len(r.ExpandWildcards) > 0 {
		params["expand_wildcards"] = strings.Join(r.ExpandWildcards, ",")
	}

	if r.IgnoreUnavailable {
		params["ignore_unavailable"] = "true"
	}

	if r.IncludeDefaults {
		params["include_defaults"] = "true"
	}

	if r.Local {
		params["local"] = "true"
	}

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// IndicesGetFieldMappingResp represents the response for the indices.get_field_mapping operation.
//
// Returns mapping for one or more fields.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/field-types/index/
type IndicesGetFieldMappingResp struct {
	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r IndicesGetFieldMappingResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// IndicesGetFieldMappingTypeFieldMappings is a typed component of the indices.get_field_mapping response.
//
// The field mapping configuration for a type.
type IndicesGetFieldMappingTypeFieldMappings struct {
	// The map of field names to their mapping definitions.
	Mappings map[string]CommonMappingField `json:"mappings"`
}

func (c indicesClient) GetFieldMapping(ctx context.Context, req *IndicesGetFieldMappingReq) (*IndicesGetFieldMappingResp, error) {
	if req == nil {
		req = &IndicesGetFieldMappingReq{}
	}

	var (
		data IndicesGetFieldMappingResp
		err  error
	)
	if data.response, err = do(ctx, c.apiClient, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}

// Deprecated: use IndicesGetFieldMapping via the parent client instead.
func (c mappingClient) Field(ctx context.Context, req *IndicesGetFieldMappingReq) (*IndicesGetFieldMappingResp, error) {
	if req == nil {
		req = &IndicesGetFieldMappingReq{}
	}

	var (
		data IndicesGetFieldMappingResp
		err  error
	)
	if data.response, err = do(ctx, c.apiClient, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}
