// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"context"
	"net/http"
	"strings"
	"time"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// IndicesGetSettingsReq represents the request for the indices.get_settings operation.
//
// Returns settings for one or more indexes.
//
// GET /_settings
//
// Available: >= 1.0.0.
//
// Not available on: amazon-managed, amazon-serverless.
//
// See: https://opensearch.org/docs/latest/api-reference/index-apis/get-settings/
type IndicesGetSettingsReq struct {
	// Name specifies the list of path segments for the request URL.
	Name []string

	// Index specifies the list of path segments for the request URL.
	Index []string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params IndicesGetSettingsParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r IndicesGetSettingsReq) GetRequest() (*http.Request, error) {
	path, err := ospath.IndicesGetSettingsPath{
		Name:  r.Name,
		Index: r.Index,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodGet,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// IndicesGetSettingsParams represents query parameters for the IndicesGetSettingsReq.
type IndicesGetSettingsParams struct {
	// If `false`, the request returns an error if any wildcard expression,
	// index alias, or `_all` value targets only missing or closed indexes.
	// This behavior applies even if the request targets other open indexes.
	// For example, a request targeting `foo*,bar*` returns an error if an
	// index starts with foo but no index starts with `bar`.
	AllowNoIndices bool

	// Operation timeout for connection to cluster-manager node.
	//
	// Available: >= 2.0.0.
	ClusterManagerTimeout time.Duration

	// Type of index that wildcard patterns can match. If the request can
	// target data streams, this argument determines whether wildcard
	// expressions match hidden data streams. Supports comma-separated values,
	// such as `open,hidden`.
	ExpandWildcards []string

	// If `true`, returns settings in flat format.
	//
	// Default: false.
	FlatSettings bool

	// If `false`, the request returns an error if it targets a missing or
	// closed index.
	IgnoreUnavailable bool

	// If `true`, return all default settings in the response.
	//
	// Default: false.
	IncludeDefaults bool

	// If `true`, the request retrieves information from the local node only.
	// If `false`, information is retrieved from the cluster-manager node.
	//
	// Default: false.
	Local bool

	// Period to wait for a connection to the cluster-manager node. If no
	// response is received before the timeout expires, the request fails and
	// returns an error.
	//
	// Deprecated: since 2.0.0. To promote inclusive language, use
	// `cluster_manager_timeout` instead.
	MasterTimeout time.Duration

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r IndicesGetSettingsParams) get() map[string]string {
	params := make(map[string]string, 8)

	if r.AllowNoIndices {
		params["allow_no_indices"] = "true"
	}

	if r.ClusterManagerTimeout != 0 {
		params["cluster_manager_timeout"] = formatDuration(r.ClusterManagerTimeout)
	}

	if len(r.ExpandWildcards) > 0 {
		params["expand_wildcards"] = strings.Join(r.ExpandWildcards, ",")
	}

	if r.FlatSettings {
		params["flat_settings"] = "true"
	}

	if r.IgnoreUnavailable {
		params["ignore_unavailable"] = "true"
	}

	if r.IncludeDefaults {
		params["include_defaults"] = "true"
	}

	if r.Local {
		params["local"] = "true"
	}

	if r.MasterTimeout != 0 {
		params["master_timeout"] = formatDuration(r.MasterTimeout)
	}

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// IndicesGetSettingsResp represents the response for the indices.get_settings operation.
//
// Returns settings for one or more indexes.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/index-apis/get-settings/
type IndicesGetSettingsResp struct {
	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r IndicesGetSettingsResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

func (c indicesClient) GetSettings(ctx context.Context, req *IndicesGetSettingsReq) (*IndicesGetSettingsResp, error) {
	if req == nil {
		req = &IndicesGetSettingsReq{}
	}

	var (
		data IndicesGetSettingsResp
		err  error
	)
	if data.response, err = do(ctx, c.apiClient, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}

// Deprecated: use IndicesGetSettings via the parent client instead.
func (c settingsClient) Get(ctx context.Context, req *IndicesGetSettingsReq) (*IndicesGetSettingsResp, error) {
	if req == nil {
		req = &IndicesGetSettingsReq{}
	}

	var (
		data IndicesGetSettingsResp
		err  error
	)
	if data.response, err = do(ctx, c.apiClient, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}
