// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"context"
	"encoding/json"
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// IndicesRecoveryReq represents the request for the indices.recovery operation.
//
// Returns information about ongoing index shard recoveries.
//
// GET /_recovery
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest
type IndicesRecoveryReq struct {
	// Index specifies the list of path segments for the request URL.
	Index []string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params IndicesRecoveryParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r IndicesRecoveryReq) GetRequest() (*http.Request, error) {
	path, err := ospath.IndicesRecoveryPath{
		Index: r.Index,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodGet,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// IndicesRecoveryParams represents query parameters for the IndicesRecoveryReq.
type IndicesRecoveryParams struct {
	// If `true`, the response only includes ongoing shard recoveries.
	//
	// Default: false.
	ActiveOnly bool

	// If `true`, the response includes detailed information about shard
	// recoveries.
	//
	// Default: false.
	Detailed bool

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r IndicesRecoveryParams) get() map[string]string {
	params := make(map[string]string, 2)

	if r.ActiveOnly {
		params["active_only"] = "true"
	}

	if r.Detailed {
		params["detailed"] = "true"
	}

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// IndicesRecoveryResp represents the response for the indices.recovery operation.
//
// Returns information about ongoing index shard recoveries.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest
type IndicesRecoveryResp struct {
	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r IndicesRecoveryResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// IndicesRecoveryBytes is a typed component of the indices.recovery response.
//
// The byte-level recovery statistics.
type IndicesRecoveryBytes struct {
	// The percentage value as a string.
	Percent string `json:"percent"`

	// The unique identifier of a node.
	Recovered *string `json:"recovered,omitempty"`

	// The unique identifier of a node.
	RecoveredFromSnapshot *string `json:"recovered_from_snapshot,omitempty"`

	// The size in bytes.
	RecoveredFromSnapshotInBytes *int64 `json:"recovered_from_snapshot_in_bytes,omitempty"`

	// The size in bytes.
	RecoveredInBytes int64 `json:"recovered_in_bytes"`

	// The unique identifier of a node.
	Reused *string `json:"reused,omitempty"`

	// The size in bytes.
	ReusedInBytes int64 `json:"reused_in_bytes"`

	// The unique identifier of a node.
	Total *string `json:"total,omitempty"`

	// The size in bytes.
	TotalInBytes int64 `json:"total_in_bytes"`
}

// IndicesRecoveryFileDetails is a typed component of the indices.recovery response.
//
// The details of a recovered file.
type IndicesRecoveryFileDetails struct {
	// The length of the file in bytes.
	Length int64 `json:"length"`

	// The name of the file.
	Name string `json:"name"`

	// The number of bytes recovered.
	Recovered int64 `json:"recovered"`
}

// IndicesRecoveryFiles is a typed component of the indices.recovery response.
//
// The file-level recovery statistics.
type IndicesRecoveryFiles struct {
	// The detailed information about recovered files.
	Details []IndicesRecoveryFileDetails `json:"details,omitempty"`

	// The percentage value as a string.
	Percent string `json:"percent"`

	// The number of recovered files.
	Recovered int64 `json:"recovered"`

	// The number of reused files.
	Reused int64 `json:"reused"`

	// The total number of files.
	Total int64 `json:"total"`
}

// IndicesRecoveryIndexStatus is a typed component of the indices.recovery response.
//
// The index recovery status.
type IndicesRecoveryIndexStatus struct {
	// The byte-level recovery statistics.
	Bytes *IndicesRecoveryBytes `json:"bytes,omitempty"`

	// The file-level recovery statistics.
	Files IndicesRecoveryFiles `json:"files"`

	// The byte-level recovery statistics.
	Size IndicesRecoveryBytes `json:"size"`

	// A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s`
	// (seconds), `m` (minutes), `h` (hours) and `d` (days). Also accepts `0`
	// without a unit and `-1` to indicate an unspecified value.
	SourceThrottleTime *string `json:"source_throttle_time,omitempty"`

	// The time unit for milliseconds.
	SourceThrottleTimeInMillis int64 `json:"source_throttle_time_in_millis"`

	// A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s`
	// (seconds), `m` (minutes), `h` (hours) and `d` (days). Also accepts `0`
	// without a unit and `-1` to indicate an unspecified value.
	TargetThrottleTime *string `json:"target_throttle_time,omitempty"`

	// The time unit for milliseconds.
	TargetThrottleTimeInMillis int64 `json:"target_throttle_time_in_millis"`

	// A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s`
	// (seconds), `m` (minutes), `h` (hours) and `d` (days). Also accepts `0`
	// without a unit and `-1` to indicate an unspecified value.
	TotalTime *string `json:"total_time,omitempty"`

	// The time unit for milliseconds.
	TotalTimeInMillis int64 `json:"total_time_in_millis"`
}

// IndicesRecoveryOrigin is a typed component of the indices.recovery response.
//
// The source or target of a recovery operation.
type IndicesRecoveryOrigin struct {
	// Whether a new history UUID was bootstrapped.
	BootstrapNewHistoryUUID *bool `json:"bootstrap_new_history_uuid,omitempty"`

	// The hostname or IP address.
	Host *string `json:"host,omitempty"`

	// The hostname of the node.
	Hostname *string `json:"hostname,omitempty"`

	// The unique identifier for a resource.
	ID *string `json:"id,omitempty"`

	Index *string `json:"index,omitempty"`

	// The IP address.
	IP *string `json:"ip,omitempty"`

	// Whether this is a searchable snapshot.
	IsSearchableSnapshot *bool `json:"isSearchableSnapshot,omitempty"`

	// The name of a resource or configuration element.
	Name *string `json:"name,omitempty"`

	// Whether this is a shallow copy from a remote store.
	RemoteStoreIndexShallowCopy *bool `json:"remoteStoreIndexShallowCopy,omitempty"`

	// The name of a resource or configuration element.
	Repository *string `json:"repository,omitempty"`

	// The universally unique identifier.
	RestoreUUID *string `json:"restoreUUID,omitempty"`

	// The name of a resource or configuration element.
	Snapshot *string `json:"snapshot,omitempty"`

	// The source remote store repository.
	SourceRemoteStoreRepository *json.RawMessage `json:"sourceRemoteStoreRepository,omitempty"`

	// The source remote translog repository.
	SourceRemoteTranslogRepository *json.RawMessage `json:"sourceRemoteTranslogRepository,omitempty"`

	// The transport address of a node.
	TransportAddress *string `json:"transport_address,omitempty"`

	Version *string `json:"version,omitempty"`
}

// IndicesRecoveryStartStatus is a typed component of the indices.recovery response.
//
// The status at the start of recovery.
type IndicesRecoveryStartStatus struct {
	// A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s`
	// (seconds), `m` (minutes), `h` (hours) and `d` (days). Also accepts `0`
	// without a unit and `-1` to indicate an unspecified value.
	CheckIndexTime *string `json:"check_index_time,omitempty"`

	// The time unit for milliseconds.
	CheckIndexTimeInMillis int64 `json:"check_index_time_in_millis"`

	// A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s`
	// (seconds), `m` (minutes), `h` (hours) and `d` (days). Also accepts `0`
	// without a unit and `-1` to indicate an unspecified value.
	TotalTime *string `json:"total_time,omitempty"`

	// The time unit for milliseconds.
	TotalTimeInMillis int64 `json:"total_time_in_millis"`
}

// IndicesRecoveryTranslogStatus is a typed component of the indices.recovery response.
//
// The transaction log recovery status.
type IndicesRecoveryTranslogStatus struct {
	// The percentage value as a string.
	Percent string `json:"percent"`

	// The number of recovered transaction log operations.
	Recovered int `json:"recovered"`

	// The total number of transaction log operations.
	Total int `json:"total"`

	// The number of transaction log operations at start.
	TotalOnStart int `json:"total_on_start"`

	// A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s`
	// (seconds), `m` (minutes), `h` (hours) and `d` (days). Also accepts `0`
	// without a unit and `-1` to indicate an unspecified value.
	TotalTime *string `json:"total_time,omitempty"`

	// The time unit for milliseconds.
	TotalTimeInMillis int64 `json:"total_time_in_millis"`
}

// IndicesRecoveryVerifyIndex is a typed component of the indices.recovery response.
//
// The index verification status.
type IndicesRecoveryVerifyIndex struct {
	// A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s`
	// (seconds), `m` (minutes), `h` (hours) and `d` (days). Also accepts `0`
	// without a unit and `-1` to indicate an unspecified value.
	CheckIndexTime *string `json:"check_index_time,omitempty"`

	// The time unit for milliseconds.
	CheckIndexTimeInMillis int64 `json:"check_index_time_in_millis"`

	// A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s`
	// (seconds), `m` (minutes), `h` (hours) and `d` (days). Also accepts `0`
	// without a unit and `-1` to indicate an unspecified value.
	TotalTime *string `json:"total_time,omitempty"`

	// The time unit for milliseconds.
	TotalTimeInMillis int64 `json:"total_time_in_millis"`
}

// IndicesRecoveryShard is a typed component of the indices.recovery response.
//
// The recovery status of a shard.
type IndicesRecoveryShard struct {
	// The shard ID.
	ID int `json:"id"`

	// The index recovery status.
	Index IndicesRecoveryIndexStatus `json:"index"`

	// Whether this is a primary shard.
	Primary bool `json:"primary"`

	// The source or target of a recovery operation.
	Source IndicesRecoveryOrigin `json:"source"`

	// The current recovery stage.
	Stage string `json:"stage"`

	// The status at the start of recovery.
	Start *IndicesRecoveryStartStatus `json:"start,omitempty"`

	// A date and time, either as a string whose format depends on the context
	// (defaulting to ISO_8601) or the number of milliseconds since the epoch.
	// OpenSearch accepts both as an input but will generally output a string.
	// representation.
	StartTime *string `json:"start_time,omitempty"`

	// The time unit for milliseconds.
	StartTimeInMillis int64 `json:"start_time_in_millis"`

	// A date and time, either as a string whose format depends on the context
	// (defaulting to ISO_8601) or the number of milliseconds since the epoch.
	// OpenSearch accepts both as an input but will generally output a string.
	// representation.
	StopTime *string `json:"stop_time,omitempty"`

	// The time unit for milliseconds.
	StopTimeInMillis *int64 `json:"stop_time_in_millis,omitempty"`

	// The source or target of a recovery operation.
	Target IndicesRecoveryOrigin `json:"target"`

	// A duration. Units can be `nanos`, `micros`, `ms` (milliseconds), `s`
	// (seconds), `m` (minutes), `h` (hours) and `d` (days). Also accepts `0`
	// without a unit and `-1` to indicate an unspecified value.
	TotalTime *string `json:"total_time,omitempty"`

	// The time unit for milliseconds.
	TotalTimeInMillis int64 `json:"total_time_in_millis"`

	// The transaction log recovery status.
	Translog IndicesRecoveryTranslogStatus `json:"translog"`

	// The type of recovery operation.
	Type string `json:"type"`

	// The index verification status.
	VerifyIndex IndicesRecoveryVerifyIndex `json:"verify_index"`
}

// IndicesRecoveryStatus is a typed component of the indices.recovery response.
//
// The status of recovery operations.
type IndicesRecoveryStatus struct {
	// The list of shard recovery statuses.
	Shards []IndicesRecoveryShard `json:"shards"`
}

func (c indicesClient) Recovery(ctx context.Context, req *IndicesRecoveryReq) (*IndicesRecoveryResp, error) {
	if req == nil {
		req = &IndicesRecoveryReq{}
	}

	var (
		data IndicesRecoveryResp
		err  error
	)
	if data.response, err = do(ctx, c.apiClient, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}
