// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"context"
	"net/http"
	"strings"
	"time"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// IndicesGetMappingReq represents the request for the indices.get_mapping operation.
//
// Returns mappings for one or more indexes.
//
// GET /_mapping
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/field-types/index/#get-a-mapping
type IndicesGetMappingReq struct {
	// Index specifies the list of path segments for the request URL.
	Index []string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params IndicesGetMappingParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r IndicesGetMappingReq) GetRequest() (*http.Request, error) {
	path, err := ospath.IndicesGetMappingPath{
		Index: r.Index,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodGet,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// IndicesGetMappingParams represents query parameters for the IndicesGetMappingReq.
type IndicesGetMappingParams struct {
	// If `false`, the request returns an error if any wildcard expression,
	// index alias, or `_all` value targets only missing or closed indexes.
	// This behavior applies even if the request targets other open indexes.
	AllowNoIndices bool

	// Operation timeout for connection to cluster-manager node.
	//
	// Available: >= 2.0.0.
	ClusterManagerTimeout time.Duration

	// Type of index that wildcard patterns can match. If the request can
	// target data streams, this argument determines whether wildcard
	// expressions match hidden data streams. Supports comma-separated values,
	// such as `open,hidden`. Valid values are: `all`, `open`, `closed`,
	// `hidden`, `none`.
	ExpandWildcards []string

	// If `false`, the request returns an error if it targets a missing or
	// closed index.
	IgnoreUnavailable bool

	// Comma-separated list of data streams, indexes, and aliases used to limit
	// the request. Supports wildcards (`*`). To target all data streams and
	// indexes, omit this parameter or use `*` or `_all`.
	Index []string

	// If `true`, the request retrieves information from the local node only.
	//
	// Default: false.
	Local bool

	// Period to wait for a connection to the cluster-manager node. If no
	// response is received before the timeout expires, the request fails and
	// returns an error.
	//
	// Deprecated: since 2.0.0. To promote inclusive language, use
	// `cluster_manager_timeout` instead.
	MasterTimeout time.Duration

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r IndicesGetMappingParams) get() map[string]string {
	params := make(map[string]string, 7)

	if r.AllowNoIndices {
		params["allow_no_indices"] = "true"
	}

	if r.ClusterManagerTimeout != 0 {
		params["cluster_manager_timeout"] = formatDuration(r.ClusterManagerTimeout)
	}

	if len(r.ExpandWildcards) > 0 {
		params["expand_wildcards"] = strings.Join(r.ExpandWildcards, ",")
	}

	if r.IgnoreUnavailable {
		params["ignore_unavailable"] = "true"
	}

	if len(r.Index) > 0 {
		params["index"] = strings.Join(r.Index, ",")
	}

	if r.Local {
		params["local"] = "true"
	}

	if r.MasterTimeout != 0 {
		params["master_timeout"] = formatDuration(r.MasterTimeout)
	}

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// IndicesGetMappingResp represents the response for the indices.get_mapping operation.
//
// Returns mappings for one or more indexes.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/field-types/index/#get-a-mapping
type IndicesGetMappingResp struct {
	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r IndicesGetMappingResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// IndicesGetMappingIndexMappingRecord is a typed component of the indices.get_mapping response.
//
// The mapping configuration for an index.
type IndicesGetMappingIndexMappingRecord struct {
	Item     *CommonMappingType `json:"item,omitempty"`
	Mappings CommonMappingType  `json:"mappings"`
}

func (c indicesClient) GetMapping(ctx context.Context, req *IndicesGetMappingReq) (*IndicesGetMappingResp, error) {
	if req == nil {
		req = &IndicesGetMappingReq{}
	}

	var (
		data IndicesGetMappingResp
		err  error
	)
	if data.response, err = do(ctx, c.apiClient, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}

// Deprecated: use IndicesGetMapping via the parent client instead.
func (c mappingClient) Get(ctx context.Context, req *IndicesGetMappingReq) (*IndicesGetMappingResp, error) {
	if req == nil {
		req = &IndicesGetMappingReq{}
	}

	var (
		data IndicesGetMappingResp
		err  error
	)
	if data.response, err = do(ctx, c.apiClient, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}
