// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package osapi

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestIndicesPutSettingsParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params IndicesPutSettingsParams
		want   map[string]string
	}{
		{name: "empty", params: IndicesPutSettingsParams{}, want: map[string]string{}},
		{
			name:   "allow_no_indices",
			params: IndicesPutSettingsParams{AllowNoIndices: true},
			want:   map[string]string{"allow_no_indices": "true"},
		},
		{
			name:   "cluster_manager_timeout",
			params: IndicesPutSettingsParams{ClusterManagerTimeout: 5 * time.Second},
			want:   map[string]string{"cluster_manager_timeout": "5000ms"},
		},
		{
			name:   "expand_wildcards",
			params: IndicesPutSettingsParams{ExpandWildcards: []string{"a", "b"}},
			want:   map[string]string{"expand_wildcards": "a,b"},
		},
		{
			name:   "flat_settings",
			params: IndicesPutSettingsParams{FlatSettings: true},
			want:   map[string]string{"flat_settings": "true"},
		},
		{
			name:   "ignore_unavailable",
			params: IndicesPutSettingsParams{IgnoreUnavailable: true},
			want:   map[string]string{"ignore_unavailable": "true"},
		},
		{
			name:   "master_timeout",
			params: IndicesPutSettingsParams{MasterTimeout: 5 * time.Second},
			want:   map[string]string{"master_timeout": "5000ms"},
		},
		{
			name:   "preserve_existing",
			params: IndicesPutSettingsParams{PreserveExisting: true},
			want:   map[string]string{"preserve_existing": "true"},
		},
		{
			name:   "timeout",
			params: IndicesPutSettingsParams{Timeout: 5 * time.Second},
			want:   map[string]string{"timeout": "5000ms"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
