// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"context"
	"net/http"
	"strconv"
	"strings"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// IndicesExistsAliasReq represents the request for the indices.exists_alias operation.
//
// Returns information about whether a particular alias exists.
//
// HEAD /_alias/{name}
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest
type IndicesExistsAliasReq struct {
	// Name specifies the list of path segments for the request URL.
	Name []string

	// Index specifies the list of path segments for the request URL.
	Index []string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *IndicesExistsAliasParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r IndicesExistsAliasReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.IndicesExistsAliasPath{
		Name:  r.Name,
		Index: r.Index,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// IndicesExistsAliasParams represents query parameters for the IndicesExistsAliasReq.
type IndicesExistsAliasParams struct {
	TimeoutParams
	DebugParams
	// If `false`, the request returns an error if any wildcard expression,
	// index alias, or `_all` value targets only missing or closed indexes.
	// This behavior applies even if the request targets other open indexes.
	AllowNoIndices *bool

	// Type of index that wildcard patterns can match. If the request can
	// target data streams, this argument determines whether wildcard
	// expressions match hidden data streams. Supports comma-separated values,
	// such as `open,hidden`. Valid values are: `all`, `open`, `closed`,
	// `hidden`, `none`.
	ExpandWildcards []string

	// If `false`, requests that include a missing data stream or index in the
	// target indexes or data streams return an error.
	IgnoreUnavailable *bool

	// If `true`, the request retrieves information from the local node only.
	//
	// Default: false.
	Local *bool
}

func (r IndicesExistsAliasParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	if r.AllowNoIndices != nil {
		set("allow_no_indices", strconv.FormatBool(*r.AllowNoIndices))
	}

	if len(r.ExpandWildcards) > 0 {
		set("expand_wildcards", strings.Join(r.ExpandWildcards, ","))
	}

	if r.IgnoreUnavailable != nil {
		set("ignore_unavailable", strconv.FormatBool(*r.IgnoreUnavailable))
	}

	if r.Local != nil {
		set("local", strconv.FormatBool(*r.Local))
	}

	return params
}

// ExistsAlias returns information about whether a particular alias exists.
//
// HEAD /_alias/{name}
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest
func (c indicesClient) ExistsAlias(ctx context.Context, req *IndicesExistsAliasReq) (*opensearch.Response, error) {
	if req == nil {
		req = &IndicesExistsAliasReq{}
	}

	return do(ctx, c.apiClient, http.MethodHead, req, noBody)
}

// Deprecated: use IndicesExistsAlias via the parent client instead.
func (c aliasClient) Exists(ctx context.Context, req *IndicesExistsAliasReq) (*opensearch.Response, error) {
	if req == nil {
		req = &IndicesExistsAliasReq{}
	}

	return do(ctx, c.apiClient, http.MethodHead, req, noBody)
}
