// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"context"
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// IndicesGetUpgradeReq represents the request for the indices.get_upgrade operation.
//
// The `_upgrade` API is no longer useful and will be removed.
//
// GET /_upgrade
//
// Deprecated: since 1.0.0. Available >= 1.0.0.
//
// See: https://opensearch.org/docs/latest
type IndicesGetUpgradeReq struct {
	// Index specifies the list of path segments for the request URL.
	Index []string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params IndicesGetUpgradeParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r IndicesGetUpgradeReq) GetRequest() (*http.Request, error) {
	path, err := ospath.IndicesGetUpgradePath{
		Index: r.Index,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodGet,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// IndicesGetUpgradeParams represents query parameters for the IndicesGetUpgradeReq.
type IndicesGetUpgradeParams struct {
	// Whether to ignore if a wildcard indexes expression resolves into no
	// concrete indexes. (This includes `_all` string or when no indexes have
	// been specified).
	AllowNoIndices bool

	// Whether to expand wildcard expression to concrete indexes that are open,
	// closed or both.
	ExpandWildcards []string

	// Whether specified concrete indexes should be ignored when unavailable
	// (missing or closed).
	IgnoreUnavailable bool

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r IndicesGetUpgradeParams) get() map[string]string {
	params := make(map[string]string, 3)

	if r.AllowNoIndices {
		params["allow_no_indices"] = "true"
	}

	if len(r.ExpandWildcards) > 0 {
		params["expand_wildcards"] = strings.Join(r.ExpandWildcards, ",")
	}

	if r.IgnoreUnavailable {
		params["ignore_unavailable"] = "true"
	}

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// IndicesGetUpgradeResp represents the response for the indices.get_upgrade operation.
//
// The `_upgrade` API is no longer useful and will be removed.
//
// Deprecated: since 1.0.0. Available >= 1.0.0.
//
// See: https://opensearch.org/docs/latest
type IndicesGetUpgradeResp struct {
	// The upgrade status for individual indexes.
	Indices map[string]IndicesUpgradeStatus `json:"indices,omitempty"`

	// The size in bytes.
	SizeInBytes *int64 `json:"size_in_bytes,omitempty"`

	// The size in bytes.
	SizeToUpgradeAncientInBytes *int64 `json:"size_to_upgrade_ancient_in_bytes,omitempty"`

	// The size in bytes.
	SizeToUpgradeInBytes *int64 `json:"size_to_upgrade_in_bytes,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r IndicesGetUpgradeResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

func (c indicesClient) GetUpgrade(ctx context.Context, req *IndicesGetUpgradeReq) (*IndicesGetUpgradeResp, error) {
	if req == nil {
		req = &IndicesGetUpgradeReq{}
	}

	var (
		data IndicesGetUpgradeResp
		err  error
	)
	if data.response, err = do(ctx, c.apiClient, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}
