// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package osapi

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestNodesStatsParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params NodesStatsParams
		want   map[string]string
	}{
		{name: "empty", params: NodesStatsParams{}, want: map[string]string{}},
		{
			name:   "completion_fields",
			params: NodesStatsParams{CompletionFields: []string{"a", "b"}},
			want:   map[string]string{"completion_fields": "a,b"},
		},
		{
			name:   "fielddata_fields",
			params: NodesStatsParams{FielddataFields: []string{"a", "b"}},
			want:   map[string]string{"fielddata_fields": "a,b"},
		},
		{
			name:   "fields",
			params: NodesStatsParams{Fields: []string{"a", "b"}},
			want:   map[string]string{"fields": "a,b"},
		},
		{
			name:   "groups",
			params: NodesStatsParams{Groups: []string{"a", "b"}},
			want:   map[string]string{"groups": "a,b"},
		},
		{
			name:   "include_segment_file_sizes",
			params: NodesStatsParams{IncludeSegmentFileSizes: true},
			want:   map[string]string{"include_segment_file_sizes": "true"},
		},
		{
			name:   "level",
			params: NodesStatsParams{Level: "test-value"},
			want:   map[string]string{"level": "test-value"},
		},
		{
			name:   "timeout",
			params: NodesStatsParams{Timeout: 5 * time.Second},
			want:   map[string]string{"timeout": "5000ms"},
		},
		{
			name:   "types",
			params: NodesStatsParams{Types: []string{"a", "b"}},
			want:   map[string]string{"types": "a,b"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
