// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strings"

	"fmt"
	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// ScriptsPainlessExecuteReq represents the request for the scripts_painless_execute operation.
//
// Allows an arbitrary script to be executed and a result to be returned.
//
// Path: /_scripts/painless/_execute
//
// Methods: GET, POST
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/script-apis/exec-script/
type ScriptsPainlessExecuteReq struct {

	// Body is the request payload, typically JSON-encoded.
	Body io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params ScriptsPainlessExecuteParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r ScriptsPainlessExecuteReq) GetRequest() (*http.Request, error) {
	path, err := ospath.ScriptsPainlessExecutePath{}.Build()
	if err != nil {
		return nil, err
	}
	method := http.MethodGet
	if r.Body != nil {
		method = http.MethodPost
	}

	return opensearch.BuildRequest(
		method,
		path,
		r.Body,
		r.Params.get(),
		r.Header,
	)
}

// ScriptsPainlessExecuteParams represents query parameters for the ScriptsPainlessExecuteReq.
type ScriptsPainlessExecuteParams struct {

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r ScriptsPainlessExecuteParams) get() map[string]string {
	params := make(map[string]string, 0)

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// ScriptsPainlessExecuteResp represents the response for the scripts_painless_execute operation.
//
// Allows an arbitrary script to be executed and a result to be returned.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/script-apis/exec-script/
type ScriptsPainlessExecuteResp struct {
	Result ScriptsPainlessExecuteResponseBodyResult `json:"result"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r ScriptsPainlessExecuteResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

func (c Client) ScriptsPainlessExecute(ctx context.Context, req *ScriptsPainlessExecuteReq) (*ScriptsPainlessExecuteResp, error) {
	if req == nil {
		req = &ScriptsPainlessExecuteReq{}
	}

	var (
		data ScriptsPainlessExecuteResp
		err  error
	)
	if data.response, err = do(ctx, &c, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}

// ScriptsPainlessExecuteResponseBodyResult is a discriminated union type.
// Use Type() to determine which branch was decoded, then call
// the corresponding accessor.
type ScriptsPainlessExecuteResponseBodyResult struct {
	typ        ScriptsPainlessExecuteResponseBodyResultType
	raw        json.RawMessage
	float64Val float64
	stringVal  string
	boolVal    bool
}

// ScriptsPainlessExecuteResponseBodyResultType discriminates the branches of ScriptsPainlessExecuteResponseBodyResult.
type ScriptsPainlessExecuteResponseBodyResultType int

const (
	ScriptsPainlessExecuteResponseBodyResultUnknownType ScriptsPainlessExecuteResponseBodyResultType = iota
	ScriptsPainlessExecuteResponseBodyResultFloat64Type
	ScriptsPainlessExecuteResponseBodyResultStringType
	ScriptsPainlessExecuteResponseBodyResultBoolType
)

// Type returns which union branch was populated during decoding.
// Returns ScriptsPainlessExecuteResponseBodyResultUnknownType if the value has not been decoded.
func (u *ScriptsPainlessExecuteResponseBodyResult) Type() ScriptsPainlessExecuteResponseBodyResultType {
	return u.typ
}

// RawJSON returns the original JSON bytes for escape-hatch decoding.
func (u *ScriptsPainlessExecuteResponseBodyResult) RawJSON() json.RawMessage { return u.raw }

// Float64 returns the float64 branch value.
func (u *ScriptsPainlessExecuteResponseBodyResult) Float64() float64 { return u.float64Val }

// String returns the string branch value.
func (u *ScriptsPainlessExecuteResponseBodyResult) String() string { return u.stringVal }

// Bool returns the bool branch value.
func (u *ScriptsPainlessExecuteResponseBodyResult) Bool() bool { return u.boolVal }

func (u *ScriptsPainlessExecuteResponseBodyResult) UnmarshalJSON(data []byte) error {
	u.raw = append(u.raw[:0], data...)
	if len(data) == 0 || string(data) == "null" {
		return nil
	}
	switch {
	case data[0] >= '0' && data[0] <= '9' || data[0] == '-':
		u.typ = ScriptsPainlessExecuteResponseBodyResultFloat64Type
		return json.Unmarshal(data, &u.float64Val)
	case data[0] == '"':
		u.typ = ScriptsPainlessExecuteResponseBodyResultStringType
		return json.Unmarshal(data, &u.stringVal)
	case data[0] == 't' || data[0] == 'f':
		u.typ = ScriptsPainlessExecuteResponseBodyResultBoolType
		return json.Unmarshal(data, &u.boolVal)
	default:
		return fmt.Errorf("ScriptsPainlessExecuteResponseBodyResult: unexpected JSON token: %s", data[:1])
	}
	return nil
}

func (u ScriptsPainlessExecuteResponseBodyResult) MarshalJSON() ([]byte, error) {
	switch u.typ {
	case ScriptsPainlessExecuteResponseBodyResultFloat64Type:
		return json.Marshal(u.float64Val)
	case ScriptsPainlessExecuteResponseBodyResultStringType:
		return json.Marshal(u.stringVal)
	case ScriptsPainlessExecuteResponseBodyResultBoolType:
		return json.Marshal(u.boolVal)
	default:
		if len(u.raw) > 0 {
			return u.raw, nil
		}
		return []byte("null"), nil
	}
}
