// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package osapi

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestScrollParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params ScrollParams
		want   map[string]string
	}{
		{name: "empty", params: ScrollParams{}, want: map[string]string{}},
		{
			name:   "rest_total_hits_as_int",
			params: ScrollParams{RestTotalHitsAsInt: true},
			want:   map[string]string{"rest_total_hits_as_int": "true"},
		},
		{
			name:   "scroll",
			params: ScrollParams{Scroll: 5 * time.Second},
			want:   map[string]string{"scroll": "5000ms"},
		},
		{
			name:   "scroll_id",
			params: ScrollParams{ScrollID: "test-value"},
			want:   map[string]string{"scroll_id": "test-value"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
