// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// SearchTemplateReq represents the request for the search_template operation.
//
// Allows to use the Mustache language to pre-render a search definition.
//
// Path: /_search/template
//
// Methods: GET, POST
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/search-plugins/search-template/
type SearchTemplateReq struct {
	// Index specifies the list of path segments for the request URL.
	Index []string

	// Body is the request payload, typically JSON-encoded.
	Body io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params SearchTemplateParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r SearchTemplateReq) GetRequest() (*http.Request, error) {
	path, err := ospath.SearchTemplatePath{
		Index: r.Index,
	}.Build()
	if err != nil {
		return nil, err
	}
	method := http.MethodGet
	if r.Body != nil {
		method = http.MethodPost
	}

	return opensearch.BuildRequest(
		method,
		path,
		r.Body,
		r.Params.get(),
		r.Header,
	)
}

// SearchTemplateParams represents query parameters for the SearchTemplateReq.
type SearchTemplateParams struct {
	// If `false`, the request returns an error if any wildcard expression,
	// index alias, or `_all` value targets only missing or closed indexes.
	// This behavior applies even if the request targets other open indexes.
	// For example, a request targeting `foo*,bar*` returns an error if an
	// index starts with `foo` but no index starts with `bar`.
	AllowNoIndices bool

	// If `true`, network round-trips are minimized for cross-cluster search
	// requests.
	//
	// Default: true.
	CcsMinimizeRoundtrips bool

	// Type of index that wildcard patterns can match. If the request can
	// target data streams, this argument determines whether wildcard
	// expressions match hidden data streams. Supports comma-separated values,
	// such as `open,hidden`. Valid values are: `all`, `open`, `closed`,
	// `hidden`, `none`.
	ExpandWildcards []string

	// If `true`, the response includes additional details about score
	// computation as part of a hit.
	Explain bool

	// If `true`, specified concrete, expanded, or aliased indexes are not
	// included in the response when throttled.
	IgnoreThrottled bool

	// If `false`, the request returns an error if it targets a missing or
	// closed index.
	IgnoreUnavailable bool

	// Specifies the node or shard the operation should be performed on. Random
	// by default.
	//
	// Default: random.
	Preference string

	// If `true`, the query execution is profiled.
	Profile bool

	// If `true`, `hits.total` are rendered as an integer in the response.
	//
	// Default: false.
	RestTotalHitsAsInt bool

	// Custom value used to route operations to a specific shard.
	Routing []string

	// Specifies how long a consistent view of the index should be maintained
	// for scrolled search.
	Scroll time.Duration

	// The type of the search operation.
	SearchType string

	// If `true`, the response prefixes aggregation and suggester names with
	// their respective types.
	TypedKeys bool

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r SearchTemplateParams) get() map[string]string {
	params := make(map[string]string, 13)

	if r.AllowNoIndices {
		params["allow_no_indices"] = "true"
	}

	if r.CcsMinimizeRoundtrips {
		params["ccs_minimize_roundtrips"] = "true"
	}

	if len(r.ExpandWildcards) > 0 {
		params["expand_wildcards"] = strings.Join(r.ExpandWildcards, ",")
	}

	if r.Explain {
		params["explain"] = "true"
	}

	if r.IgnoreThrottled {
		params["ignore_throttled"] = "true"
	}

	if r.IgnoreUnavailable {
		params["ignore_unavailable"] = "true"
	}

	if r.Preference != "" {
		params["preference"] = r.Preference
	}

	if r.Profile {
		params["profile"] = "true"
	}

	if r.RestTotalHitsAsInt {
		params["rest_total_hits_as_int"] = "true"
	}

	if len(r.Routing) > 0 {
		params["routing"] = strings.Join(r.Routing, ",")
	}

	if r.Scroll != 0 {
		params["scroll"] = formatDuration(r.Scroll)
	}

	if r.SearchType != "" {
		params["search_type"] = r.SearchType
	}

	if r.TypedKeys {
		params["typed_keys"] = "true"
	}

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// SearchTemplateResp represents the response for the search_template operation.
//
// Allows to use the Mustache language to pre-render a search definition.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/search-plugins/search-template/
type SearchTemplateResp struct {
	Clusters        *ClusterStatistics                                     `json:"_clusters,omitempty"`
	ScrollID        *string                                                `json:"_scroll_id,omitempty"`
	Shards          ShardStatistics                                        `json:"_shards"`
	Aggregations    map[string]SearchTemplateResponseBodyAggregationsValue `json:"aggregations,omitempty"`
	Fields          map[string]json.RawMessage                             `json:"fields,omitempty"`
	Hits            SearchHitsMetadata                                     `json:"hits"`
	MaxScore        *float32                                               `json:"max_score,omitempty"`
	NumReducePhases *int                                                   `json:"num_reduce_phases,omitempty"`

	// The unique identifier for a resource.
	PitID *string `json:"pit_id,omitempty"`

	Profile         *SearchProfile                                          `json:"profile,omitempty"`
	Status          *float64                                                `json:"status,omitempty"`
	Suggest         map[string][]SearchTemplateResponseBodySuggestValueItem `json:"suggest,omitempty"`
	TerminatedEarly *bool                                                   `json:"terminated_early,omitempty"`
	TimedOut        bool                                                    `json:"timed_out"`
	Took            int64                                                   `json:"took"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r SearchTemplateResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

func (c Client) SearchTemplate(ctx context.Context, req *SearchTemplateReq) (*SearchTemplateResp, error) {
	if req == nil {
		req = &SearchTemplateReq{}
	}

	var (
		data SearchTemplateResp
		err  error
	)
	if data.response, err = do(ctx, &c, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}

// SearchTemplateResponseBodyAggregationsValue is a lazy-decoded discriminated union type.
// Call the typed accessor for the branch you expect; it decodes on demand.
type SearchTemplateResponseBodyAggregationsValue struct {
	raw json.RawMessage
}

func (u *SearchTemplateResponseBodyAggregationsValue) UnmarshalJSON(data []byte) error {
	u.raw = append(u.raw[:0], data...)
	return nil
}

func (u SearchTemplateResponseBodyAggregationsValue) MarshalJSON() ([]byte, error) {
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return []byte("null"), nil
}

// RawJSON returns the original JSON bytes for escape-hatch decoding.
func (u *SearchTemplateResponseBodyAggregationsValue) RawJSON() json.RawMessage { return u.raw }

// CommonAggregationsAdjacencyMatrixAggregate decodes the raw JSON into CommonAggregationsAdjacencyMatrixAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsAdjacencyMatrixAggregate() (CommonAggregationsAdjacencyMatrixAggregate, error) {
	var v CommonAggregationsAdjacencyMatrixAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsAutoDateHistogramAggregate decodes the raw JSON into CommonAggregationsAutoDateHistogramAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsAutoDateHistogramAggregate() (CommonAggregationsAutoDateHistogramAggregate, error) {
	var v CommonAggregationsAutoDateHistogramAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsAvgAggregate decodes the raw JSON into CommonAggregationsAvgAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsAvgAggregate() (CommonAggregationsAvgAggregate, error) {
	var v CommonAggregationsAvgAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsBoxPlotAggregate decodes the raw JSON into CommonAggregationsBoxPlotAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsBoxPlotAggregate() (CommonAggregationsBoxPlotAggregate, error) {
	var v CommonAggregationsBoxPlotAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsBucketMetricValueAggregate decodes the raw JSON into CommonAggregationsBucketMetricValueAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsBucketMetricValueAggregate() (CommonAggregationsBucketMetricValueAggregate, error) {
	var v CommonAggregationsBucketMetricValueAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsCardinalityAggregate decodes the raw JSON into CommonAggregationsCardinalityAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsCardinalityAggregate() (CommonAggregationsCardinalityAggregate, error) {
	var v CommonAggregationsCardinalityAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsChildrenAggregate decodes the raw JSON into CommonAggregationsChildrenAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsChildrenAggregate() (CommonAggregationsChildrenAggregate, error) {
	var v CommonAggregationsChildrenAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsCompositeAggregate decodes the raw JSON into CommonAggregationsCompositeAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsCompositeAggregate() (CommonAggregationsCompositeAggregate, error) {
	var v CommonAggregationsCompositeAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsDateHistogramAggregate decodes the raw JSON into CommonAggregationsDateHistogramAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsDateHistogramAggregate() (CommonAggregationsDateHistogramAggregate, error) {
	var v CommonAggregationsDateHistogramAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsDateRangeAggregate decodes the raw JSON into CommonAggregationsDateRangeAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsDateRangeAggregate() (CommonAggregationsDateRangeAggregate, error) {
	var v CommonAggregationsDateRangeAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsDerivativeAggregate decodes the raw JSON into CommonAggregationsDerivativeAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsDerivativeAggregate() (CommonAggregationsDerivativeAggregate, error) {
	var v CommonAggregationsDerivativeAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsDoubleTermsAggregate decodes the raw JSON into CommonAggregationsDoubleTermsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsDoubleTermsAggregate() (CommonAggregationsDoubleTermsAggregate, error) {
	var v CommonAggregationsDoubleTermsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsExtendedStatsAggregate decodes the raw JSON into CommonAggregationsExtendedStatsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsExtendedStatsAggregate() (CommonAggregationsExtendedStatsAggregate, error) {
	var v CommonAggregationsExtendedStatsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsExtendedStatsBucketAggregate decodes the raw JSON into CommonAggregationsExtendedStatsBucketAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsExtendedStatsBucketAggregate() (CommonAggregationsExtendedStatsBucketAggregate, error) {
	var v CommonAggregationsExtendedStatsBucketAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsFilterAggregate decodes the raw JSON into CommonAggregationsFilterAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsFilterAggregate() (CommonAggregationsFilterAggregate, error) {
	var v CommonAggregationsFilterAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsFiltersAggregate decodes the raw JSON into CommonAggregationsFiltersAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsFiltersAggregate() (CommonAggregationsFiltersAggregate, error) {
	var v CommonAggregationsFiltersAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsGeoBoundsAggregate decodes the raw JSON into CommonAggregationsGeoBoundsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsGeoBoundsAggregate() (CommonAggregationsGeoBoundsAggregate, error) {
	var v CommonAggregationsGeoBoundsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsGeoCentroidAggregate decodes the raw JSON into CommonAggregationsGeoCentroidAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsGeoCentroidAggregate() (CommonAggregationsGeoCentroidAggregate, error) {
	var v CommonAggregationsGeoCentroidAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsGeoDistanceAggregate decodes the raw JSON into CommonAggregationsGeoDistanceAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsGeoDistanceAggregate() (CommonAggregationsGeoDistanceAggregate, error) {
	var v CommonAggregationsGeoDistanceAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsGeoHashGridAggregate decodes the raw JSON into CommonAggregationsGeoHashGridAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsGeoHashGridAggregate() (CommonAggregationsGeoHashGridAggregate, error) {
	var v CommonAggregationsGeoHashGridAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsGeoTileGridAggregate decodes the raw JSON into CommonAggregationsGeoTileGridAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsGeoTileGridAggregate() (CommonAggregationsGeoTileGridAggregate, error) {
	var v CommonAggregationsGeoTileGridAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsGlobalAggregate decodes the raw JSON into CommonAggregationsGlobalAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsGlobalAggregate() (CommonAggregationsGlobalAggregate, error) {
	var v CommonAggregationsGlobalAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsHdrPercentilesAggregate decodes the raw JSON into CommonAggregationsHdrPercentilesAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsHdrPercentilesAggregate() (CommonAggregationsHdrPercentilesAggregate, error) {
	var v CommonAggregationsHdrPercentilesAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsHdrPercentileRanksAggregate decodes the raw JSON into CommonAggregationsHdrPercentileRanksAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsHdrPercentileRanksAggregate() (CommonAggregationsHdrPercentileRanksAggregate, error) {
	var v CommonAggregationsHdrPercentileRanksAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsHistogramAggregate decodes the raw JSON into CommonAggregationsHistogramAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsHistogramAggregate() (CommonAggregationsHistogramAggregate, error) {
	var v CommonAggregationsHistogramAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsIpRangeAggregate decodes the raw JSON into CommonAggregationsIpRangeAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsIpRangeAggregate() (CommonAggregationsIpRangeAggregate, error) {
	var v CommonAggregationsIpRangeAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsLongRareTermsAggregate decodes the raw JSON into CommonAggregationsLongRareTermsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsLongRareTermsAggregate() (CommonAggregationsLongRareTermsAggregate, error) {
	var v CommonAggregationsLongRareTermsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsLongTermsAggregate decodes the raw JSON into CommonAggregationsLongTermsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsLongTermsAggregate() (CommonAggregationsLongTermsAggregate, error) {
	var v CommonAggregationsLongTermsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsMatrixStatsAggregate decodes the raw JSON into CommonAggregationsMatrixStatsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsMatrixStatsAggregate() (CommonAggregationsMatrixStatsAggregate, error) {
	var v CommonAggregationsMatrixStatsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsMaxAggregate decodes the raw JSON into CommonAggregationsMaxAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsMaxAggregate() (CommonAggregationsMaxAggregate, error) {
	var v CommonAggregationsMaxAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsMedianAbsoluteDeviationAggregate decodes the raw JSON into CommonAggregationsMedianAbsoluteDeviationAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsMedianAbsoluteDeviationAggregate() (CommonAggregationsMedianAbsoluteDeviationAggregate, error) {
	var v CommonAggregationsMedianAbsoluteDeviationAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsMinAggregate decodes the raw JSON into CommonAggregationsMinAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsMinAggregate() (CommonAggregationsMinAggregate, error) {
	var v CommonAggregationsMinAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsMissingAggregate decodes the raw JSON into CommonAggregationsMissingAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsMissingAggregate() (CommonAggregationsMissingAggregate, error) {
	var v CommonAggregationsMissingAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsMultiTermsAggregate decodes the raw JSON into CommonAggregationsMultiTermsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsMultiTermsAggregate() (CommonAggregationsMultiTermsAggregate, error) {
	var v CommonAggregationsMultiTermsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsNestedAggregate decodes the raw JSON into CommonAggregationsNestedAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsNestedAggregate() (CommonAggregationsNestedAggregate, error) {
	var v CommonAggregationsNestedAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsParentAggregate decodes the raw JSON into CommonAggregationsParentAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsParentAggregate() (CommonAggregationsParentAggregate, error) {
	var v CommonAggregationsParentAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsPercentilesBucketAggregate decodes the raw JSON into CommonAggregationsPercentilesBucketAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsPercentilesBucketAggregate() (CommonAggregationsPercentilesBucketAggregate, error) {
	var v CommonAggregationsPercentilesBucketAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsRangeAggregate decodes the raw JSON into CommonAggregationsRangeAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsRangeAggregate() (CommonAggregationsRangeAggregate, error) {
	var v CommonAggregationsRangeAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsRateAggregate decodes the raw JSON into CommonAggregationsRateAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsRateAggregate() (CommonAggregationsRateAggregate, error) {
	var v CommonAggregationsRateAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsReverseNestedAggregate decodes the raw JSON into CommonAggregationsReverseNestedAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsReverseNestedAggregate() (CommonAggregationsReverseNestedAggregate, error) {
	var v CommonAggregationsReverseNestedAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsSamplerAggregate decodes the raw JSON into CommonAggregationsSamplerAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsSamplerAggregate() (CommonAggregationsSamplerAggregate, error) {
	var v CommonAggregationsSamplerAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsScriptedMetricAggregate decodes the raw JSON into CommonAggregationsScriptedMetricAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsScriptedMetricAggregate() (CommonAggregationsScriptedMetricAggregate, error) {
	var v CommonAggregationsScriptedMetricAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsSignificantLongTermsAggregate decodes the raw JSON into CommonAggregationsSignificantLongTermsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsSignificantLongTermsAggregate() (CommonAggregationsSignificantLongTermsAggregate, error) {
	var v CommonAggregationsSignificantLongTermsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsSignificantStringTermsAggregate decodes the raw JSON into CommonAggregationsSignificantStringTermsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsSignificantStringTermsAggregate() (CommonAggregationsSignificantStringTermsAggregate, error) {
	var v CommonAggregationsSignificantStringTermsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsCumulativeCardinalityAggregate decodes the raw JSON into CommonAggregationsCumulativeCardinalityAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsCumulativeCardinalityAggregate() (CommonAggregationsCumulativeCardinalityAggregate, error) {
	var v CommonAggregationsCumulativeCardinalityAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsSimpleValueAggregate decodes the raw JSON into CommonAggregationsSimpleValueAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsSimpleValueAggregate() (CommonAggregationsSimpleValueAggregate, error) {
	var v CommonAggregationsSimpleValueAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsStatsAggregate decodes the raw JSON into CommonAggregationsStatsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsStatsAggregate() (CommonAggregationsStatsAggregate, error) {
	var v CommonAggregationsStatsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsStatsBucketAggregate decodes the raw JSON into CommonAggregationsStatsBucketAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsStatsBucketAggregate() (CommonAggregationsStatsBucketAggregate, error) {
	var v CommonAggregationsStatsBucketAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsStringRareTermsAggregate decodes the raw JSON into CommonAggregationsStringRareTermsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsStringRareTermsAggregate() (CommonAggregationsStringRareTermsAggregate, error) {
	var v CommonAggregationsStringRareTermsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsStringTermsAggregate decodes the raw JSON into CommonAggregationsStringTermsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsStringTermsAggregate() (CommonAggregationsStringTermsAggregate, error) {
	var v CommonAggregationsStringTermsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsSumAggregate decodes the raw JSON into CommonAggregationsSumAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsSumAggregate() (CommonAggregationsSumAggregate, error) {
	var v CommonAggregationsSumAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsTDigestPercentilesAggregate decodes the raw JSON into CommonAggregationsTDigestPercentilesAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsTDigestPercentilesAggregate() (CommonAggregationsTDigestPercentilesAggregate, error) {
	var v CommonAggregationsTDigestPercentilesAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsTDigestPercentileRanksAggregate decodes the raw JSON into CommonAggregationsTDigestPercentileRanksAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsTDigestPercentileRanksAggregate() (CommonAggregationsTDigestPercentileRanksAggregate, error) {
	var v CommonAggregationsTDigestPercentileRanksAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsTTestAggregate decodes the raw JSON into CommonAggregationsTTestAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsTTestAggregate() (CommonAggregationsTTestAggregate, error) {
	var v CommonAggregationsTTestAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsTopHitsAggregate decodes the raw JSON into CommonAggregationsTopHitsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsTopHitsAggregate() (CommonAggregationsTopHitsAggregate, error) {
	var v CommonAggregationsTopHitsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsUnmappedRareTermsAggregate decodes the raw JSON into CommonAggregationsUnmappedRareTermsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsUnmappedRareTermsAggregate() (CommonAggregationsUnmappedRareTermsAggregate, error) {
	var v CommonAggregationsUnmappedRareTermsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsUnmappedSignificantTermsAggregate decodes the raw JSON into CommonAggregationsUnmappedSignificantTermsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsUnmappedSignificantTermsAggregate() (CommonAggregationsUnmappedSignificantTermsAggregate, error) {
	var v CommonAggregationsUnmappedSignificantTermsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsUnmappedTermsAggregate decodes the raw JSON into CommonAggregationsUnmappedTermsAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsUnmappedTermsAggregate() (CommonAggregationsUnmappedTermsAggregate, error) {
	var v CommonAggregationsUnmappedTermsAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsValueCountAggregate decodes the raw JSON into CommonAggregationsValueCountAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsValueCountAggregate() (CommonAggregationsValueCountAggregate, error) {
	var v CommonAggregationsValueCountAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsVariableWidthHistogramAggregate decodes the raw JSON into CommonAggregationsVariableWidthHistogramAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsVariableWidthHistogramAggregate() (CommonAggregationsVariableWidthHistogramAggregate, error) {
	var v CommonAggregationsVariableWidthHistogramAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// CommonAggregationsWeightedAvgAggregate decodes the raw JSON into CommonAggregationsWeightedAvgAggregate.
func (u *SearchTemplateResponseBodyAggregationsValue) CommonAggregationsWeightedAvgAggregate() (CommonAggregationsWeightedAvgAggregate, error) {
	var v CommonAggregationsWeightedAvgAggregate
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// SearchTemplateResponseBodySuggestValueItem is a lazy-decoded discriminated union type.
// Call the typed accessor for the branch you expect; it decodes on demand.
type SearchTemplateResponseBodySuggestValueItem struct {
	raw json.RawMessage
}

func (u *SearchTemplateResponseBodySuggestValueItem) UnmarshalJSON(data []byte) error {
	u.raw = append(u.raw[:0], data...)
	return nil
}

func (u SearchTemplateResponseBodySuggestValueItem) MarshalJSON() ([]byte, error) {
	if len(u.raw) > 0 {
		return u.raw, nil
	}
	return []byte("null"), nil
}

// RawJSON returns the original JSON bytes for escape-hatch decoding.
func (u *SearchTemplateResponseBodySuggestValueItem) RawJSON() json.RawMessage { return u.raw }

// SearchCompletionSuggest decodes the raw JSON into SearchCompletionSuggest.
func (u *SearchTemplateResponseBodySuggestValueItem) SearchCompletionSuggest() (SearchCompletionSuggest, error) {
	var v SearchCompletionSuggest
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// SearchPhraseSuggest decodes the raw JSON into SearchPhraseSuggest.
func (u *SearchTemplateResponseBodySuggestValueItem) SearchPhraseSuggest() (SearchPhraseSuggest, error) {
	var v SearchPhraseSuggest
	err := json.Unmarshal(u.raw, &v)
	return v, err
}

// SearchTermSuggest decodes the raw JSON into SearchTermSuggest.
func (u *SearchTemplateResponseBodySuggestValueItem) SearchTermSuggest() (SearchTermSuggest, error) {
	var v SearchTermSuggest
	err := json.Unmarshal(u.raw, &v)
	return v, err
}
