// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"context"
	"net/http"
	"strings"
	"time"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// SearchPipelineDeleteReq represents the request for the search_pipeline.delete operation.
//
// Deletes the specified search pipeline.
//
// DELETE /_search/pipeline/{id}
//
// Available: >= 2.9.0.
type SearchPipelineDeleteReq struct {
	// ID specifies the path segment for the request URL.
	ID string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params SearchPipelineDeleteParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r SearchPipelineDeleteReq) GetRequest() (*http.Request, error) {
	path, err := ospath.SearchPipelineDeletePath{
		ID: r.ID,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodDelete,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// SearchPipelineDeleteParams represents query parameters for the SearchPipelineDeleteReq.
type SearchPipelineDeleteParams struct {
	// Operation timeout for connection to cluster-manager node.
	//
	// Available: >= 2.0.0.
	ClusterManagerTimeout time.Duration

	// Operation timeout.
	Timeout time.Duration

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r SearchPipelineDeleteParams) get() map[string]string {
	params := make(map[string]string, 2)

	if r.ClusterManagerTimeout != 0 {
		params["cluster_manager_timeout"] = formatDuration(r.ClusterManagerTimeout)
	}

	if r.Timeout != 0 {
		params["timeout"] = formatDuration(r.Timeout)
	}

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// SearchPipelineDeleteResp represents the response for the search_pipeline.delete operation.
//
// Deletes the specified search pipeline.
//
// Available: >= 2.9.0.
type SearchPipelineDeleteResp struct {
	Acknowledged *bool `json:"acknowledged,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r SearchPipelineDeleteResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

func (c searchPipelineClient) Delete(ctx context.Context, req SearchPipelineDeleteReq) (*SearchPipelineDeleteResp, error) {
	var (
		data SearchPipelineDeleteResp
		err  error
	)
	if data.response, err = do(ctx, c.apiClient, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}
