// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package osapi

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestSnapshotStatusParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params SnapshotStatusParams
		want   map[string]string
	}{
		{name: "empty", params: SnapshotStatusParams{}, want: map[string]string{}},
		{
			name:   "cluster_manager_timeout",
			params: SnapshotStatusParams{ClusterManagerTimeout: 5 * time.Second},
			want:   map[string]string{"cluster_manager_timeout": "5000ms"},
		},
		{
			name:   "ignore_unavailable",
			params: SnapshotStatusParams{IgnoreUnavailable: true},
			want:   map[string]string{"ignore_unavailable": "true"},
		},
		{
			name:   "master_timeout",
			params: SnapshotStatusParams{MasterTimeout: 5 * time.Second},
			want:   map[string]string{"master_timeout": "5000ms"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
