// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"context"
	"net/http"
	"strings"
	"time"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// SnapshotDeleteRepositoryReq represents the request for the snapshot.delete_repository operation.
//
// Deletes a snapshot repository.
//
// DELETE /_snapshot/{repository}
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/snapshots/delete-snapshot-repository/
type SnapshotDeleteRepositoryReq struct {
	// Repository specifies the list of path segments for the request URL.
	Repository []string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params SnapshotDeleteRepositoryParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r SnapshotDeleteRepositoryReq) GetRequest() (*http.Request, error) {
	path, err := ospath.SnapshotDeleteRepositoryPath{
		Repository: r.Repository,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodDelete,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// SnapshotDeleteRepositoryParams represents query parameters for the SnapshotDeleteRepositoryReq.
type SnapshotDeleteRepositoryParams struct {
	// The amount of time to wait for a response from the cluster manager node.
	// For more information about supported time units, see [Common
	// parameters](https://opensearch.org/docs/latest/api-reference/common-parameters/#time-units).
	//
	// Available: >= 2.0.0.
	ClusterManagerTimeout time.Duration

	// Explicit operation timeout for connection to cluster-manager node
	//
	// Deprecated: since 2.0.0. To promote inclusive language, use
	// `cluster_manager_timeout` instead.
	MasterTimeout time.Duration

	// The amount of time to wait for a response.
	Timeout time.Duration

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r SnapshotDeleteRepositoryParams) get() map[string]string {
	params := make(map[string]string, 3)

	if r.ClusterManagerTimeout != 0 {
		params["cluster_manager_timeout"] = formatDuration(r.ClusterManagerTimeout)
	}

	if r.MasterTimeout != 0 {
		params["master_timeout"] = formatDuration(r.MasterTimeout)
	}

	if r.Timeout != 0 {
		params["timeout"] = formatDuration(r.Timeout)
	}

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// SnapshotDeleteRepositoryResp represents the response for the snapshot.delete_repository operation.
//
// Deletes a snapshot repository.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/snapshots/delete-snapshot-repository/
type SnapshotDeleteRepositoryResp struct {
	// For a successful response, this value is always true. On failure, an
	// exception is returned instead.
	Acknowledged bool `json:"acknowledged"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r SnapshotDeleteRepositoryResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

func (c snapshotClient) DeleteRepository(ctx context.Context, req *SnapshotDeleteRepositoryReq) (*SnapshotDeleteRepositoryResp, error) {
	if req == nil {
		req = &SnapshotDeleteRepositoryReq{}
	}

	var (
		data SnapshotDeleteRepositoryResp
		err  error
	)
	if data.response, err = do(ctx, c.apiClient, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}

// Deprecated: use SnapshotDeleteRepository via the parent client instead.
func (c repositoryClient) Delete(ctx context.Context, req *SnapshotDeleteRepositoryReq) (*SnapshotDeleteRepositoryResp, error) {
	if req == nil {
		req = &SnapshotDeleteRepositoryReq{}
	}

	var (
		data SnapshotDeleteRepositoryResp
		err  error
	)
	if data.response, err = do(ctx, c.apiClient, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}
