// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package osapi

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestTasksCancelParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params TasksCancelParams
		want   map[string]string
	}{
		{name: "empty", params: TasksCancelParams{}, want: map[string]string{}},
		{
			name:   "actions",
			params: TasksCancelParams{Actions: []string{"a", "b"}},
			want:   map[string]string{"actions": "a,b"},
		},
		{
			name:   "nodes",
			params: TasksCancelParams{Nodes: []string{"a", "b"}},
			want:   map[string]string{"nodes": "a,b"},
		},
		{
			name:   "parent_task_id",
			params: TasksCancelParams{ParentTaskID: "test-value"},
			want:   map[string]string{"parent_task_id": "test-value"},
		},
		{
			name:   "wait_for_completion",
			params: TasksCancelParams{WaitForCompletion: true},
			want:   map[string]string{"wait_for_completion": "true"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
