// Code generated by cmd/osgen; DO NOT EDIT.

package osapi

import (
	"context"
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// TasksCancelReq represents the request for the tasks.cancel operation.
//
// Cancels a task, if it can be cancelled through an API.
//
// POST /_tasks/_cancel
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/tasks/#task-canceling
type TasksCancelReq struct {
	// TaskID specifies the path segment for the request URL.
	TaskID string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params TasksCancelParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r TasksCancelReq) GetRequest() (*http.Request, error) {
	path, err := ospath.TasksCancelPath{
		TaskID: r.TaskID,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodPost,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// TasksCancelParams represents query parameters for the TasksCancelReq.
type TasksCancelParams struct {
	// A comma-separated list of actions that should be returned. Keep empty to
	// return all.
	Actions []string

	// A comma-separated list of node IDs or names used to limit the returned
	// information. Use `_local` to return information from the node you're
	// connecting to, specify the node name to get information from a specific
	// node, or keep the parameter empty to get information from all nodes.
	Nodes []string

	// Returns tasks with a specified parent task ID (`node_id:task_number`).
	// Keep empty or set to -1 to return all.
	ParentTaskID string

	// Waits for the matching task to complete. When `true`, the request is
	// blocked until the task has completed.
	//
	// Default: false.
	WaitForCompletion bool

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r TasksCancelParams) get() map[string]string {
	params := make(map[string]string, 4)

	if len(r.Actions) > 0 {
		params["actions"] = strings.Join(r.Actions, ",")
	}

	if len(r.Nodes) > 0 {
		params["nodes"] = strings.Join(r.Nodes, ",")
	}

	if r.ParentTaskID != "" {
		params["parent_task_id"] = r.ParentTaskID
	}

	if r.WaitForCompletion {
		params["wait_for_completion"] = "true"
	}

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// TasksCancelResp represents the response for the tasks.cancel operation.
//
// Cancels a task, if it can be cancelled through an API.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/api-reference/tasks/#task-canceling
type TasksCancelResp struct {
	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r TasksCancelResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

func (c tasksClient) Cancel(ctx context.Context, req TasksCancelReq) (*TasksCancelResp, error) {
	var (
		data TasksCancelResp
		err  error
	)
	if data.response, err = do(ctx, c.apiClient, req, &data); err != nil {
		return &data, err
	}

	return &data, nil
}
