// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package osapi

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestTermvectorsParams_get(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name   string
		params TermvectorsParams
		want   map[string]string
	}{
		{name: "empty", params: TermvectorsParams{}, want: map[string]string{}},
		{
			name:   "field_statistics",
			params: TermvectorsParams{FieldStatistics: true},
			want:   map[string]string{"field_statistics": "true"},
		},
		{
			name:   "fields",
			params: TermvectorsParams{Fields: []string{"a", "b"}},
			want:   map[string]string{"fields": "a,b"},
		},
		{
			name:   "offsets",
			params: TermvectorsParams{Offsets: true},
			want:   map[string]string{"offsets": "true"},
		},
		{
			name:   "payloads",
			params: TermvectorsParams{Payloads: true},
			want:   map[string]string{"payloads": "true"},
		},
		{
			name:   "positions",
			params: TermvectorsParams{Positions: true},
			want:   map[string]string{"positions": "true"},
		},
		{
			name:   "preference",
			params: TermvectorsParams{Preference: "test-value"},
			want:   map[string]string{"preference": "test-value"},
		},
		{
			name:   "realtime",
			params: TermvectorsParams{Realtime: true},
			want:   map[string]string{"realtime": "true"},
		},
		{
			name:   "routing",
			params: TermvectorsParams{Routing: []string{"a", "b"}},
			want:   map[string]string{"routing": "a,b"},
		},
		{
			name:   "term_statistics",
			params: TermvectorsParams{TermStatistics: true},
			want:   map[string]string{"term_statistics": "true"},
		},
		{
			name:   "version",
			params: TermvectorsParams{Version: 42},
			want:   map[string]string{"version": "42"},
		},
		{
			name:   "version_type",
			params: TermvectorsParams{VersionType: "test-value"},
			want:   map[string]string{"version_type": "test-value"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, tt.params.get())
		})
	}
}
