// Code generated by cmd/osgen; DO NOT EDIT.

package ml

import (
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/osapi"
)

// DeleteModelGroupReq represents the request for the ml.delete_model_group operation.
//
// Deletes a model group.
//
// DELETE /_plugins/_ml/model_groups/{model_group_id}
type DeleteModelGroupReq struct {
	// ModelGroupID specifies the path segment for the request URL.
	ModelGroupID string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params DeleteModelGroupParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r DeleteModelGroupReq) GetRequest() (*http.Request, error) {
	path, err := ospath.MlDeleteModelGroupPath{
		ModelGroupID: r.ModelGroupID,
	}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodDelete,
		path,
		nil,
		r.Params.get(),
		r.Header,
	)
}

// DeleteModelGroupParams represents query parameters for the DeleteModelGroupReq.
type DeleteModelGroupParams struct {

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r DeleteModelGroupParams) get() map[string]string {
	params := make(map[string]string, 0)

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// DeleteModelGroupResp represents the response for the ml.delete_model_group operation.
//
// Deletes a model group.
type DeleteModelGroupResp struct {
	// The unique identifier for a resource.
	ID string `json:"_id"`

	Index string `json:"_index"`

	// The primary term of the document.
	PrimaryTerm int64 `json:"_primary_term"`

	// The sequence number of the document.
	SeqNo int64 `json:"_seq_no"`

	Shards osapi.ShardStatistics `json:"_shards"`

	// The type of document or resource.
	Type *string `json:"_type,omitempty"`

	Version       int64  `json:"_version"`
	ForcedRefresh *bool  `json:"forced_refresh,omitempty"`
	Result        string `json:"result"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r DeleteModelGroupResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}
