// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package ml_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v4/osapi/plugins/ml"
)

func TestGetAgentReq_GetRequest(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name       string
		req        ml.GetAgentReq
		wantMethod string
		wantPath   string
		wantErr    bool
	}{
		{
			name:       "missing required fields",
			req:        ml.GetAgentReq{},
			wantMethod: "",
			wantPath:   "",
			wantErr:    true,
		},
		{
			name:       "all path fields",
			req:        ml.GetAgentReq{AgentID: "test-agentid"},
			wantMethod: "GET",
			wantPath:   "/_plugins/_ml/agents/test-agentid",
			wantErr:    false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			httpReq, err := tt.req.GetRequest()
			if tt.wantErr {
				require.Error(t, err)
				return
			}
			require.NoError(t, err)
			require.Equal(t, tt.wantMethod, httpReq.Method)
			require.Equal(t, tt.wantPath, httpReq.URL.Path)
		})
	}
}
