// Code generated by cmd/osgen; DO NOT EDIT.

//go:build integration

package ml_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	osapitest "github.com/opensearch-project/opensearch-go/v4/osapi/internal/test"
	"github.com/opensearch-project/opensearch-go/v4/osapi/plugins/ml"
	plugintest "github.com/opensearch-project/opensearch-go/v4/osapi/plugins/ml/internal/test"
	"github.com/opensearch-project/opensearch-go/v4/osapi/testutil"
)

func TestGetStats(t *testing.T) {
	client, err := plugintest.NewClient(t)
	require.NoError(t, err)

	osClient, err := testutil.NewClient(t)
	require.NoError(t, err)
	testutil.SkipIfVersion(t, osClient, "<", "1.3", "GetStats")

	t.Run("success", func(t *testing.T) {
		resp, err := client.GetStats(t.Context(), ml.GetStatsReq{})
		require.NoError(t, err)
		require.NotNil(t, resp)
		testutil.CompareRawJSONwithParsedJSON(t, resp, resp.Inspect().Response)
	})

	t.Run("inspect", func(t *testing.T) {
		failingClient, err := plugintest.CreateFailingClient(t)
		require.NoError(t, err)

		res, err := failingClient.GetStats(t.Context(), ml.GetStatsReq{})
		require.Error(t, err)
		require.NotNil(t, res)
		osapitest.VerifyInspect(t, res.Inspect())
	})
}
