// Code generated by cmd/osgen; DO NOT EDIT.

//go:build !integration

package ml_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v4/osapi/plugins/ml"
)

func TestSearchMemoryReq_GetRequest(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name       string
		req        ml.SearchMemoryReq
		wantMethod string
		wantPath   string
		wantErr    bool
	}{
		{
			name:       "empty request",
			req:        ml.SearchMemoryReq{},
			wantMethod: "GET",
			wantPath:   "/_plugins/_ml/memory/_search",
			wantErr:    false,
		},
		{
			name:       "body triggers POST",
			req:        ml.SearchMemoryReq{Body: strings.NewReader("{}")},
			wantMethod: "POST",
			wantPath:   "/_plugins/_ml/memory/_search",
			wantErr:    false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			httpReq, err := tt.req.GetRequest()
			if tt.wantErr {
				require.Error(t, err)
				return
			}
			require.NoError(t, err)
			require.Equal(t, tt.wantMethod, httpReq.Method)
			require.Equal(t, tt.wantPath, httpReq.URL.Path)
		})
	}
}
