// Code generated by cmd/osgen; DO NOT EDIT.

package ml

import (
	"io"
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// SearchModelGroupReq represents the request for the ml.search_model_group operation.
//
// Searches for model groups.
//
// Path: /_plugins/_ml/model_groups/_search
//
// Methods: GET, POST
//
// Available: >= 2.9.0.
type SearchModelGroupReq struct {

	// Body is the request payload, typically JSON-encoded.
	Body io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params SearchModelGroupParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r SearchModelGroupReq) GetRequest() (*http.Request, error) {
	path, err := ospath.MlSearchModelGroupPath{}.Build()
	if err != nil {
		return nil, err
	}
	method := http.MethodGet
	if r.Body != nil {
		method = http.MethodPost
	}

	return opensearch.BuildRequest(
		method,
		path,
		r.Body,
		r.Params.get(),
		r.Header,
	)
}

// SearchModelGroupParams represents query parameters for the SearchModelGroupReq.
type SearchModelGroupParams struct {

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r SearchModelGroupParams) get() map[string]string {
	params := make(map[string]string, 0)

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// SearchModelGroupResp represents the response for the ml.search_model_group operation.
//
// Searches for model groups.
//
// Available: >= 2.9.0.
type SearchModelGroupResp struct {
	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r SearchModelGroupResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}
