// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

//go:build integration

package notifications_test

import (
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/opensearch-project/opensearch-go/v5/opensearchapi/testutil"
	"github.com/opensearch-project/opensearch-go/v5/plugins/notifications"
	plugintest "github.com/opensearch-project/opensearch-go/v5/plugins/notifications/internal/notificationstest"
)

func TestDeleteConfig(t *testing.T) {
	t.Skip("requires notification channel or config") //nolint:gocritic // FIXME: implement proper test fixture
	client, err := plugintest.NewClient(t)
	require.NoError(t, err)

	osClient, err := testutil.NewClient(t)
	require.NoError(t, err)
	testutil.SkipIfVersion(t, osClient, "<", "2.0", "DeleteConfig")
	name := testutil.MustUniqueString(t, "test-delete-config")

	t.Run("success", func(t *testing.T) {
		resp, err := client.Config.DeleteConfig(t.Context(), notifications.DeleteConfigReq{ConfigID: name})
		require.NoError(t, err)
		require.NotNil(t, resp)
		testutil.CompareRawJSONwithParsedJSON(t, resp, resp.Inspect().Response)
	})

	t.Run("inspect", func(t *testing.T) {
		failingClient, err := plugintest.CreateFailingClient(t)
		require.NoError(t, err)

		res, err := failingClient.Config.DeleteConfig(t.Context(), notifications.DeleteConfigReq{ConfigID: name})
		require.Error(t, err)
		require.NotNil(t, res)
		plugintest.VerifyInspect(t, res.Inspect())
	})
}
