// Code generated by cmd/osgen; DO NOT EDIT.

package sql

import (
	"encoding/json"
	"io"
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// QueryReq represents the request for the sql.query operation.
//
// Executes SQL or PPL queries against OpenSearch indexes.
//
// POST /_plugins/_sql
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/search-plugins/sql/sql-ppl-api/
type QueryReq struct {

	// Body is the request payload, typically JSON-encoded.
	Body io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params QueryParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r QueryReq) GetRequest() (*http.Request, error) {
	path, err := ospath.SQLQueryPath{}.Build()
	if err != nil {
		return nil, err
	}

	return opensearch.BuildRequest(
		http.MethodPost,
		path,
		r.Body,
		r.Params.get(),
		r.Header,
	)
}

// QueryParams represents query parameters for the QueryReq.
type QueryParams struct {
	// Specifies the response format (JSON or YAML).
	Format string

	// Whether to escape special characters in the results.
	//
	// Default: true.
	Sanitize bool

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r QueryParams) get() map[string]string {
	params := make(map[string]string, 2)

	if r.Format != "" {
		params["format"] = r.Format
	}

	if r.Sanitize {
		params["sanitize"] = "true"
	}

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// QueryResp represents the response for the sql.query operation.
//
// Executes SQL or PPL queries against OpenSearch indexes.
//
// Available: >= 1.0.0.
//
// See: https://opensearch.org/docs/latest/search-plugins/sql/sql-ppl-api/
type QueryResp struct {
	// The cursor identifier for pagination.
	Cursor *string `json:"cursor,omitempty"`

	// The rows of data returned by the query.
	Datarows [][]json.RawMessage `json:"datarows,omitempty"`

	// The schema of the query result.
	Schema []json.RawMessage `json:"schema,omitempty"`

	// The number of rows in the current response.
	Size *int `json:"size,omitempty"`

	// The status code of the response.
	Status *int `json:"status,omitempty"`

	// The total number of hits.
	Total *int `json:"total,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r QueryResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}
