// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package ltr

import (
	"bytes"
	"io"
	"net/http"
	"strconv"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/osapi"
)

// AddFeaturesToSetReq represents the request for the ltr.add_features_to_set operation.
//
// Add features to an existing feature set in the default feature store.
//
// POST /_ltr/_featureset/{name}/_addfeatures
//
// Available: >= 2.19.0.
type AddFeaturesToSetReq struct {
	// Name specifies the path segment for the request URL.
	Name string

	// Store specifies the path segment for the request URL.
	Store string

	// Body is the request payload, typically JSON-encoded.
	Body io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *AddFeaturesToSetParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r AddFeaturesToSetReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.LtrAddFeaturesToSetPath{
		Name:  r.Name,
		Store: r.Store,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		r.Body,
		params,
		r.Header,
	)
}

// AddFeaturesToSetParams represents query parameters for the AddFeaturesToSetReq.
type AddFeaturesToSetParams struct {
	osapi.TimeoutParams
	osapi.DebugParams
	// Whether to merge the feature list or append only.
	//
	// Default: false.
	Merge *bool

	// Specific routing value.
	Routing string

	// Version check to ensure feature set is modified with expected version.
	Version int
}

func (r AddFeaturesToSetParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	if r.Merge != nil {
		set("merge", strconv.FormatBool(*r.Merge))
	}

	if r.Routing != "" {
		set("routing", r.Routing)
	}

	if r.Version != 0 {
		set("version", strconv.Itoa(r.Version))
	}

	return params
}

// AddFeaturesToSetResp represents the response for the ltr.add_features_to_set operation.
//
// Add features to an existing feature set in the default feature store.
//
// Available: >= 2.19.0.
type AddFeaturesToSetResp struct {
	// The unique identifier for a resource.
	ID string `json:"_id"`

	Index string `json:"_index"`

	// The primary term of the document.
	PrimaryTerm int64 `json:"_primary_term"`

	// The sequence number of the document.
	SeqNo int64 `json:"_seq_no"`

	Shards osapi.ShardStatistics `json:"_shards"`

	// The type of document or resource.
	Type *string `json:"_type,omitempty"`

	Version       int64  `json:"_version"`
	ForcedRefresh *bool  `json:"forced_refresh,omitempty"`
	Result        string `json:"result"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r AddFeaturesToSetResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r AddFeaturesToSetResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
