// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package ltr

import (
	"bytes"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/v5preview/opensearchapi"
)

// CreateStoreReq represents the request for the ltr.create_store operation.
//
// Creates a new feature store with the specified name.
//
// PUT /_ltr/{store}
//
// Available: >= 2.17.1.
type CreateStoreReq struct {
	// Store specifies the path segment for the request URL.
	Store string

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *CreateStoreParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r CreateStoreReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.LtrCreateStorePath{
		Store: r.Store,
	}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// CreateStoreParams represents query parameters for the CreateStoreReq.
type CreateStoreParams struct {
	opensearchapi.TimeoutParams
	opensearchapi.DebugParams
}

func (r CreateStoreParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// CreateStoreResp represents the response for the ltr.create_store operation.
//
// Creates a new feature store with the specified name.
//
// Available: >= 2.17.1.
type CreateStoreResp struct {
	// Indicates whether the request was acknowledged.
	Acknowledged *bool `json:"acknowledged,omitempty"`

	// The name of the index.
	Index *string `json:"index,omitempty"`

	// Indicates whether the required active shards were acknowledged.
	ShardsAcknowledged *bool `json:"shards_acknowledged,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r CreateStoreResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r CreateStoreResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
