name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  GITHUB_ACTIONS: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 1 }
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.2
      - name: Install dependencies
        run: go get -u golang.org/x/lint/golint
        env:
          GOBIN: ${{ env.GOROOT }}/bin
        shell: bash
      - run: go version
      - run: make lint
