name: License headers

on: [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check license headers
        run: |
          ./.github/check-license-headers.sh
