// Code generated by cmd/osgen; DO NOT EDIT.

package ism

import (
	"io"
	"net/http"
	"strings"

	"github.com/opensearch-project/opensearch-go/v4"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
)

// ExplainPolicyReq represents the request for the ism.explain_policy operation.
//
// Retrieves the currently applied policy on the specified indexes.
//
// Path: /_plugins/_ism/explain
//
// Methods: GET, POST
//
// See: https://opensearch.org/docs/latest/im-plugin/ism/api/#explain-index
type ExplainPolicyReq struct {
	// Index specifies the list of path segments for the request URL.
	Index []string

	// Body is the request payload, typically JSON-encoded.
	Body io.Reader

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params ExplainPolicyParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r ExplainPolicyReq) GetRequest() (*http.Request, error) {
	path, err := ospath.IsmExplainPolicyPath{
		Index: r.Index,
	}.Build()
	if err != nil {
		return nil, err
	}
	method := http.MethodGet
	if r.Body != nil {
		method = http.MethodPost
	}

	return opensearch.BuildRequest(
		method,
		path,
		r.Body,
		r.Params.get(),
		r.Header,
	)
}

// ExplainPolicyParams represents query parameters for the ExplainPolicyReq.
type ExplainPolicyParams struct {

	// Pretty enables indented JSON responses for debugging readability.
	Pretty bool
	// Human enables human-friendly values in responses (e.g. "1.5gb" instead of bytes).
	Human bool
	// ErrorTrace includes the Java stack trace of errors in the response.
	ErrorTrace bool
	// FilterPath restricts the response to the specified JSON paths.
	FilterPath []string
}

func (r ExplainPolicyParams) get() map[string]string {
	params := make(map[string]string, 0)

	if r.Pretty {
		params["pretty"] = "true"
	}

	if r.Human {
		params["human"] = "true"
	}

	if r.ErrorTrace {
		params["error_trace"] = "true"
	}

	if len(r.FilterPath) > 0 {
		params["filter_path"] = strings.Join(r.FilterPath, ",")
	}

	return params
}

// ExplainPolicyResp represents the response for the ism.explain_policy operation.
//
// Retrieves the currently applied policy on the specified indexes.
//
// See: https://opensearch.org/docs/latest/im-plugin/ism/api/#explain-index
type ExplainPolicyResp struct {
	// The total number of managed indices.
	TotalManagedIndices *float64 `json:"total_managed_indices,omitempty"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r ExplainPolicyResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}
