// SPDX-License-Identifier: Apache-2.0
//
// The OpenSearch Contributors require contributions made to
// this file be licensed under the Apache-2.0 license or a
// compatible open source license.

// Code generated by cmd/osgen; DO NOT EDIT.

package geospatial

import (
	"bytes"
	"io"
	"net/http"

	opensearch "github.com/opensearch-project/opensearch-go/v4"
	"github.com/opensearch-project/opensearch-go/v4/internal/build"
	osparams "github.com/opensearch-project/opensearch-go/v4/internal/params"
	ospath "github.com/opensearch-project/opensearch-go/v4/internal/path"
	"github.com/opensearch-project/opensearch-go/v4/osapi"
)

// GetUploadStatsReq represents the request for the geospatial.get_upload_stats operation.
//
// Retrieves statistics for all geospatial uploads.
//
// GET /_plugins/geospatial/_upload/stats
//
// Available: >= 2.11.0.
type GetUploadStatsReq struct {

	// Header provides additional HTTP headers for the request.
	Header http.Header

	// Params holds optional query parameters for the request.
	Params *GetUploadStatsParams
}

// GetRequest builds the HTTP request from the structured fields.
func (r GetUploadStatsReq) GetRequest(method string) (*http.Request, error) {
	path, err := ospath.GeospatialGetUploadStatsPath{}.Build()
	if err != nil {
		return nil, err
	}

	var params map[string]string
	if r.Params != nil {
		params = r.Params.get()
	}

	return build.Request(
		method,
		path,
		nil,
		params,
		r.Header,
	)
}

// GetUploadStatsParams represents query parameters for the GetUploadStatsReq.
type GetUploadStatsParams struct {
	osapi.TimeoutParams
	osapi.DebugParams
}

func (r GetUploadStatsParams) get() map[string]string {
	var params map[string]string
	set := func(k, v string) {
		if params == nil {
			params = make(map[string]string)
		}
		params[k] = v
	}
	osparams.EncodeTimeout(r.TimeoutParams, set)
	osparams.EncodeDebug(r.DebugParams, set)

	return params
}

// GetUploadStatsResp represents the response for the geospatial.get_upload_stats operation.
//
// Retrieves statistics for all geospatial uploads.
//
// Available: >= 2.11.0.
type GetUploadStatsResp struct {
	Metrics []osapi.GeospatialUploadStatsMetric `json:"metrics"`
	Total   osapi.GeospatialUploadStatsTotal    `json:"total"`

	response *opensearch.Response
}

// Inspect returns the raw OpenSearch response for debugging or advanced use.
func (r GetUploadStatsResp) Inspect() Inspect {
	return Inspect{Response: r.response}
}

// RawBody returns a fresh reader over the original response bytes,
// useful when the typed response struct is incomplete for your use case.
func (r GetUploadStatsResp) RawBody() io.Reader {
	if r.response == nil || len(r.response.RawBody()) == 0 {
		return nil
	}
	return bytes.NewReader(r.response.RawBody())
}
